### ISSUE TITLE
Wifi/BT connection for X96 Max Plus 100W

### ISSUE THREAD

**Issue by trvqhuy** [EmuELEC/EmuELEC#1017]
**General information**
- Name: X96 Max Plus **100W**
- CPU: Amlogic S905X3 quad-core ARM Cortex A55
- GPU: ARM Mali-G31MP
- Radio module: **W522A**
- Memory: DDR3 4GB, FLASH 32GB
- Support 10/100M Ethernet, 2.4GHz and 5GHz WiFi, BT4.0;
- USB3.0 x 1, USB2.0 x 1, TF Card
- HDMI, AV, SPDIF

**Is your feature request related to a problem? Please describe.**
The system cannot establish Wifi/BT connection with the **W522A** chipset because it has not been supported by the main kernel yet.

**Describe the solution you'd like**
After several hours of researching, I figured out that there's zero information about Linux driver for this new module on the Internet.

Given that the Wifi/BT works smoothly in the TV box manufacturer's image (Android TV 9.0 - Linux kernel 4.9.113), I've tried looking for the DTB files and the kernel module from that original image, with the results shown in the [Google Drive Link](https://drive.google.com/drive/folders/19ZoOEo5c5Ca7U48NtAfFLx2ErqLUA2JB?usp=sharing), but alternating these DTB file (after converting DTS to DTB) to `dtb.img` in the `EMUELEC` partition does not help, the boot process always got stuck at the logo.

I know that somehow I need to migrate the Wifi/BT driver from the manufacturer's image to the EMUELEC image, but I don't really have a clue on this.

If only, could you please instruct me a proper way to handle this situation? There are a number of people in my area purchased TV box with the same W522A Wifi chipset, currently we are having the same situation.

Below is the image of the TV box.
Thank you in advance.

![image](https://user-images.githubusercontent.com/88963333/192023643-e8552a7b-b6ff-41cd-9943-b95159bd4c84.png)

**Comment by 7Ji** [comment]
Suggestion change model name ``X96 Max Plus 100W`` => ``X96 Max Plus 100M``, I don't think ``100W`` is a word that'll be used in model name?

For the driver, we are using the kernel from upstream project CoreELEC as-is: https://github.com/CoreELEC/linux-amlogic, with only minumum patches, which is derived from Amlogic's 4.9 vendor kernel. As you said even the mainline kernel does not have this driver, and I doubt the driver could be ported to it (Or at least could you share some link with the driver's source? Then maybe I could try my luck to port it and sumbit to upstream CoreELEC so we could both use it)

**Comment by trvqhuy** [comment]
Thank you for your dedicated support.

I would love to send you all of the files you need, but I don't really know where is the driver directory for the Android, although I had the full access to the root directory of the system.

Could you please show me the location of those drivers?

**Comment by 7Ji** [comment]
> the driver directory for the Android

That will not help for porting but only for figuring out the driver, we need source code to compile it into EmuELC, as ophub said in another issues you opened in his repo: https://github.com/ophub/amlogic-s9xxx-armbian/issues/566

You could try your luck on CoreELEC forum but as I briefly googled there's no source for the chip available, so even team CE probably could not help
https://discourse.coreelec.org/t/looking-for-users-with-no-working-wifi-or-bt/9649

**Comment by trvqhuy** [comment]
Okay, I understand now.

I had tried to find the W522A driver's source but there's none.

But I wonder if there is any possible way to "decompile" the existed code from the manufacturer's image into our source code?

**Comment by shantigilbert** [comment]
> But I wonder if there is any possible way to "decompile" the existed code from the manufacturer's image into our source code?

Possible? maybe, but it is not as easy as you may think. So unless there is source code elsewhere, this is a `nofix`. Sorry

**Comment by luucasmooreira** [comment]
Any solution to properly install armbian on this box? I have the same problem, I managed to install and get the IP, but it only recognizes 2 GB RAM =/
