### ISSUE TITLE
FUSE Pentagon 128K / Scorpion 256 etc

### ISSUE THREAD

**Issue by maver3000** [EmuELEC/EmuELEC#102]
I've tried to run TRD/SCL games but without any luck.
As I know, I have to copy additional roms to BIOS folder, what I did but any time when I'm trying to load game there is error mesage - Failed to load content.
I've tried same on LAKKA but also without luck.
Only works Spectrum 48K/128K .z80 and .tap files.
Any idea how to solve it?

**Comment by shantigilbert** [comment]
No idea. as you mention the same happening on other distros, I assume this is not an EmuELEC issue, so closing now.
