### ISSUE TITLE
EmuELEC 4.5 - ODROID-C4 - Wifi settings not being written to /storage/.cache/connman 

### ISSUE THREAD

**Issue by mvrk69** [EmuELEC/EmuELEC#1041]
Hi, i’ve installed EmuELEC 4.5 on my ODROID-C4 and i have the hardkernel wifi module 5bk plugged in, its detected and i see the wlan0 interface.

On emulationstation i enabled wifi, configured ssid and password, but no connection.

I checked /storage/.cache/connman/ and it seems emulationstation is not writing the configuration there.

**Comment by edouardlicn123** [comment]
Sugget you to send info to the FORUM for Shanti will ALWAYS CLOSE THE TOPIC like you.

**Comment by Langerz82** [comment]
Try updating to 4.6 is this still an issue?
