### ISSUE TITLE
EmuELEC 4.5 - ODROID-C4 - 8Bitdo SN30 Pro+ X input mode doesn't work properly

### ISSUE THREAD

**Issue by mvrk69** [EmuELEC/EmuELEC#1042]
Hi,

If i pair my 8Bitdo SN30 Pro+ controller in X input mode in EmuELEC the controller doesn't stop vibrating and also when mapping buttons doesn't recognized the star button, left and right triggers are mapped to AXIS 2+ / AXIS 5+, which are supposed to be the left up/down analog axis.

Switch and D input modes work fine.

**Comment by shantigilbert** [comment]
Know issue, no fix. This only happens to 8bitdo xinput you already have the solution, use dinput.
