### ISSUE TITLE
Emuelec 4.5 C16/Plus 4 system issue

### ISSUE THREAD

**Issue by kingromi** [EmuELEC/EmuELEC#1048]
I put several roms in .prg .tap format in the C16 folder, I refreshed the game list, but the system does not appear in the main menu. I use Emuelec 4.5 with x96 max plus

**Comment by miwasp** [comment]
The accepted extensions for c16 are
`extension>.d64 .g64 .t64 .x64 .zip .D64 .G64 .T64 .X64 .ZIP</extension> `

**Comment by kingromi** [comment]
great thanks it worked!
