### ISSUE TITLE
Is SHANWAN controller working correctly now ?

### ISSUE THREAD

**Issue by xiaofami** [EmuELEC/EmuELEC#1051]
I have a fake PS3 controller (SHANWAN) and although it could be paired and works in emuelec, it rumbles non-stop. Recently, I found that 

https://github.com/torvalds/linux/blob/master/drivers/hid/hid-sony.c 
has fixed this issuse:

	/*
	 * But the USB interrupt would cause SHANWAN controllers to
	 * start rumbling non-stop, so skip step 3 for these controllers.
	 */
	if (sc->quirks & SHANWAN_GAMEPAD)
		goto out;

So any chances that SHANWAN will work correctly under emuelec ? I'm using S905 box with 3.14 kernel ...

**Comment by shantigilbert** [comment]
> I'm using S905 box with 3.14 kernel ...

No, this kernel and device are no longer supported.
