### ISSUE TITLE
8BitDo controllers

### ISSUE THREAD

**Issue by ghost** [EmuELEC/EmuELEC#1056]
Delete this.

**Comment by Langerz82** [comment]
I think there may be an issue with the xbox drivers, because my gamesir (T3 and T4 Pro) controllers are picked up as xbox controllers too.

**Comment by edouardlicn123** [comment]
Sugget you to send info to the FORUM for Shanti will ALWAYS CLOSE THE TOPIC like yours.

**Comment by Langerz82** [comment]
To fix this you have to do a few things.
1. In /storage/joypads copy "Xbox One S Controller.cfg" to "8BitDo Arcade Stick.cfg" and "8BitDo M30 Bluetooth.cfg". It would be something like:
```
cp "/storage/joypads/Xbox One S Controller.cfg" "/storage/joypads/8BitDo Arcade Stick.cfg"
cp "/storage/joypads/Xbox One S Controller.cfg" "/storage/joypads/8BitDo M30 Bluetooth.cfg"
```
2. Edit those files and replace input_device = "Xbox One S Controller" with the correct names 8BitDo etc.
3. Reboot
4. When launching Retroarch it should detect the correct files, and not Xbox One S Controller. Then you can change the button assignment and it should alter the correct files, no guarantees though you might have to manually alter the button assignments.

**Comment by Langerz82** [comment]
If it works fine paste the controller file assignments and maybe we can include it in ES by default.

**Comment by John7wg** [comment]
I try it but It doesn't work. 

Emulationstation still detects them as "XBOX ONE S CONTROLLER".

**Comment by Langerz82** [comment]
I should have been more specific, even though ES will reccognize them as Xbox One S Controller, the extra profiles should be picked up by retroarch.

**Comment by Langerz82** [comment]
Closing issue. If you still need support let me know.
