### ISSUE TITLE
ColecoVision = ROMS found, they show on menu, but will not play

### ISSUE THREAD

**Issue by Mecha-Weasel** [EmuELEC/EmuELEC#107]
For ColecoVision, are we missing a BIOS file or something?
RetroArch starts, then exits almost immediately after selecting an ColecoVision game from the list.

Basically, same issue as with Intellivision (https://github.com/EmuELEC/EmuELEC/issues/106)

**Comment by Kegg1701** [comment]
Both working beautifully here...Basically you answered your own question.. You have to make sure you have the right bios, databases, and Machine files for both Coleco and Intellivision.. best way to check what bios is needed is to look at the associated libretro core info file (/tmp/cores), and check the listed firmware and possible included notes. then go hunting the net for them.
A hint is to look for full batocera bios pack by mini cake.
