### ISSUE TITLE
4.6-TEST-07082022: version glibcxx_3.4.**' not found (required by retroarch32)

### ISSUE THREAD

**Issue by brolifen** [EmuELEC/EmuELEC#1077]
**Describe the bug**
Error pops up when running psx emulation on the Beelink Super Console X King after upgrading to current test branch.

**Screenshots**
![image](https://user-images.githubusercontent.com/20615514/206849365-a7f62bae-4393-4eea-b29d-5930cd66a3f9.png)

**EmuELEC version:**
4.6-TEST-07082022

**Device (please complete the following information):**
 - SOC: S922X
 - Brand: Beelink
 - Model Super Console X King

**Comment by brolifen** [comment]
Same issue occurs after downgrading to 4.6 stable branch.

**Comment by brolifen** [comment]
Resolved this by going in the game settings -> per system advanced settings and changing the cores to "PCSX rearmed" on auto it seems to choose "PCSX REARMED 32B" which then causes the mentioned issue.

**Comment by miwasp** [comment]
You will have problems with every 32Bit core in your installation.

At first, 4.6 stable is newer than 4.6 TEST, so this is not a downgrade.

It seems you did an update from an older version and you still have old libs in /emuelec/lib32 that are no longer needed. You have 3 options here:
1. Manually delete all libs in /emuelec/lib32 and reboot
2. Use „Reset scripts and binaries“ from the menu
3. Do a fresh install

After that switch back to pcsx_rearmed_32b as it has better performance.

**Comment by brolifen** [comment]
> 2. Use „Reset scripts and binaries“ from the menu

Thank you! This seems to have fixed the problem too and my other open issue too!

https://github.com/EmuELEC/EmuELEC/issues/1078

**Comment by gingerbeardman** [comment]
Thanks. This also fixed it for me. 

Odd how my device could get in this state by following stable updates?
