### ISSUE TITLE
Odroid N2+ do not boot with 4.6 fresh install

### ISSUE THREAD

**Issue by flying-turtle-63** [EmuELEC/EmuELEC#1084]
Dear Emuelec team, 

Just report that I've not been able to boot flashed SDcard (two differents) with 4.6 release on Odroid N2+. 

It work fine with 4.5 release. I've been able to update from 4.5 to 4.6 as well. 

Good work by the way, thanks!

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/604

"PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org/) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!"
