### ISSUE TITLE
Pas de Bluetooth n'y wifi

### ISSUE THREAD

**Issue by rudboy62100** [EmuELEC/EmuELEC#1087]
Bonjour,
Voici le problème que je rencontre 
Je n'obtient de wifi n'y Bluetooth avec cette box 

La puce wifi+BT et k255b-sr

Le EmuELEC version: 4.6

Device - SOC: [S095x4]

Model x96 max pro plus 
 
Version Android 11

Y a til une solution ??

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/604
