### ISSUE TITLE
a95x f4 Bluetooth and wifi don't work

### ISSUE THREAD

**Issue by PonchoNz** [EmuELEC/EmuELEC#1089]
bluetooth and wifi don't works.

EmuELEC version:
 - Version [4.6]

Device 
 - SOC: [S905x4]
 - Brand: [MACHYONG]
 - Model [A95XF4]
 - Version [Android 11 model]

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/604
