### ISSUE TITLE
dosbox cant work properly on OGA

### ISSUE THREAD

**Issue by xxxsen** [EmuELEC/EmuELEC#109]
I download an OGA image(version 3.5) from odroid forum and flash it to my OGA but it cant run any dos game. 
It seems that dosbox cant chdir to a right game dir. After cd into the game folder and run game manually, it works, but in a wrong orientation.

![IMG_20200222_224036](https://user-images.githubusercontent.com/3880276/75094535-f32e3a00-55c6-11ea-920e-61d6a8f324db.jpg)
![IMG_20200222_223947](https://user-images.githubusercontent.com/3880276/75094527-ec072c00-55c6-11ea-8826-96e2caeb55f1.jpg)

**Comment by shantigilbert** [comment]
There are still many things needed to be fixed for the OGA, this being one of them
