### ISSUE TITLE
EmuELEC 4.6 > Duckstation > 'no such file or directory' when trying to run the game

### ISSUE THREAD

**Issue by sanyco92** [EmuELEC/EmuELEC#1097]
Hello, guys!
Installed EmuELEC 4.6, copied some games to PSX ROMs folder, added files to BIOS folder
For Playstation 1 changed the emulator to Duckstation. But when trying to run the game, getting the following error:

![photo_2023-01-06_02-37-40](https://user-images.githubusercontent.com/29158752/210906523-caa01854-7e37-4546-8cbd-f27e8f78926f.jpg)

It looks like it's not installed or something. Can anyone help, how can I add Duckstation?
Unfortunately, I don't have wi-fi on my device, so everything I can do is add files via microSD

**Comment by Langerz82** [comment]
Did you do a clean install from scratch or upgrade? You need to mount the sd-card ext4 storage partition, using linux or an external windows app, and check that you have valid files in: /storage/.config/emuelec/configs/duckstation

**Comment by sanyco92** [comment]
Yes, I did a clean install. 
Where can I get those duckstation files?

**Comment by Langerz82** [comment]
they should automatically copy across, something doesn't seem right, maybe it was your installation process that error'd.

**Comment by sanyco92** [comment]
Could anyone share the files that should be in 
 /storage/.config/emuelec/configs/duckstation
/storage/.local/share/duckstation

I'll try to put files in those directories. Maybe it will help. Because I don't know where to get these files. Thanks!

**Comment by Langerz82** [comment]
Try this in SSH:
```
cp -r /usr/config/emuelec/configs/duckstation /emuelec/configs/duckstation
```

**Comment by Langerz82** [comment]
Considering this fixed as others do not have this issue.

**Comment by AngelTorresGarcia** [comment]
> @sanyco92 -
> Try this in SSH:
> ```
> cp -r /usr/config/emuelec/configs/duckstation /emuelec/configs/duckstation
> ```
> 

Hello!! After that what i have to do? It says press some commands but i don't know if i put the right command, can u help me?

**Comment by AngelTorresGarcia** [comment]
![P_20230724_102819.jpg](https://github.com/EmuELEC/EmuELEC/assets/129403091/4ca65828-bae1-4755-ae48-794bf5ba0b38)

**Comment by Langerz82** [comment]
Whats is your device specifications? Also in ES, press start then go to EmuELEC settings >> danger zone >> Reset script and Binaries.
Did you update EmuELEC, or is this a clean image?

**Comment by AngelTorresGarcia** [comment]
> Whats is your device specifications? Also in ES, press start then go to EmuELEC settings >> danger zone >> Reset script and Binaries.
> Did you update EmuELEC, or is this a clean image?
> 

Amlogic s905x3, I was configuring the emulator and I think leaving it in fullscreen was the main problem since it did start fine but the problem was after I had configured it

**Comment by AngelTorresGarcia** [comment]
> Whats is your device specifications? Also in ES, press start then go to EmuELEC settings >> danger zone >> Reset script and Binaries.
> Did you update EmuELEC, or is this a clean image?
> 

Amlogic s905x3, I was configuring the emulator and I think leaving it in fullscreen was the main problem since it did start fine but the problem was after I had configured it

**Comment by fantasygamessb** [comment]
do this in ES, press start then go to EmuELEC settings >> danger zone >> Reset script and Binaries.

**Comment by AngelTorresGarcia** [comment]
> do this in ES, press start then go to EmuELEC settings >> danger zone >> Reset script and Binaries.

I already did it and it did not give me results, what I did was enter the local network from my cell phone and delete the duckstation folder, then I did emuelec on another sd card and copy the duckstation folder

**Comment by AngelTorresGarcia** [comment]
> do this in ES, press start then go to EmuELEC settings >> danger zone >> Reset script and Binaries.

I already did it and it did not give me results, what I did was enter the local network from my cell phone and delete the duckstation folder, then I did emuelec on another sd card and copy the duckstation folder

**Comment by Kahoned** [comment]
Hi!

I have the same problem
Can I put the directory manually?
Like I'm going to create a folder or is there a way to put this directory automatic?

**Comment by Langerz82** [comment]
If you need to reset the settings, SSH in and run the following commands:
```
rm -r "/storage/.local/share/duckstation"
rm -r "/emuelec/configs/duckstation"
```
then re-run duckstation standalone.

Closing issue.
