### ISSUE TITLE
Request new support for X96 Max Plus 100W (new W522A Radio Module)

### ISSUE THREAD

**Issue by trvqhuy** [EmuELEC/EmuELEC#1098]
### General information:

- Name: X96 Max Plus 100W
- CPU: Amlogic S905X3 quad-core ARM Cortex A55
- GPU: ARM Mali-G31MP
- Radio module: W522A
- Memory: DDR3 4GB, FLASH 32GB
- Support 10/100M Ethernet, 2.4GHz and 5GHz WiFi, BT4.0;
- USB3.0 x 1, USB2.0 x 1, TF Card
- HDMI, AV, SPDIF

### Is your feature request related to a problem? Please describe.
The system cannot establish Wifi/BT connection with the W522A chipset because it has not been supported by the main kernel yet.

### Describe the solution you'd like

I found some information.
The W522A is an Fn-Link K255B-SR.
The Fn-Link K255B-SR is an Amlogic W155S1 chip, with the following datasheet:
https://usermanual.wiki/HUNAN-FN-LINK-TECHNOLOGY/K255B-SR.User-Manual-5353157.pdf

I found two github for the sources of this module:
https://github.com/CoreELEC/w1-aml
https://github.com/adeepn/w1-aml

Tutorials for W155S1
https://blog.csdn.net/zhaojy5453/article/details/115484201

I hope it can help you, thanks for your work.1

**Comment by trvqhuy** [comment]
![192023643-e8552a7b-b6ff-41cd-9943-b95159bd4c84 (1).png](https://user-images.githubusercontent.com/88963333/211357538-e936eb23-719f-4803-ac9a-0e3faabcdd91.png)

**Comment by trvqhuy** [comment]
Hi @shantigilbert @TheLastProject @Langerz82 @7Ji, I tried installing [CoreELEC 20.0-Nexus](https://github.com/CoreELEC/CoreELEC/releases/tag/20.0-Nexus) and the Wifi connection has been obtained by the system.

Therefore, I think the problem could be fixed if we keep the kernel image up to date with CoreELEC's one.

Could you please update the above kernel into EmuELEC?

Thank you in advance for your contribution to the community.

**Comment by trvqhuy** [comment]
![image](https://user-images.githubusercontent.com/88963333/215432696-f6c54d97-f207-43ac-85d6-7412997f7f57.png)

**Comment by 7Ji** [comment]
https://github.com/CoreELEC/CoreELEC/tree/coreelec-20/projects/Amlogic-ce/packages/linux-drivers/amlogic/w1-aml

https://github.com/CoreELEC/CoreELEC/commit/c713c7ae8415121c14dc37cef5e08de5a8a73b80

https://github.com/CoreELEC/CoreELEC/commit/9984764579dd6eafc8d98356958080c9ab2b7b8c

The support should come after a regular sync with upstream source, but about when that will come, only @shantigilbert could answer, as he's the only one that has write permission to this repo and so the one that does all the CE bumps in EE.

You could also bumping your own EmuELEC source and build by yourself, if you can't wait for that.

**Comment by shantigilbert** [comment]
@trvqhuy please don't ping people for stuff like this.

**Comment by trvqhuy** [comment]
Many thanks to @7Ji for your dedicated instruction, I will follow that to build an image for myself.

My apologies for such a disturbance, I will use the ping tool more carefully, I am really sorry guys.

**Comment by trvqhuy** [comment]
Hi @7Ji , sorry for bothering you, I've followed your instruction and successfully build the EmuELEC image with working Wifi for the Amlogic W155S1 chip, thanks to you.

Unfortunately, when I tried to scrape the online videos for the games, it only showed "ArcadeDB" as a source of scraper, with no "ScreenScraper" option.

Could you please tell me if this is an error of the image or my fault?
I had cloned the "master" repo as it is the v4.6 version.

Thank you very much for your support.

**Comment by trvqhuy** [comment]
![20230211_204356.jpg](https://user-images.githubusercontent.com/88963333/218262935-489cb8ea-7187-48d7-8a61-9fef94bfcf8f.jpg)

**Comment by miwasp** [comment]
You need your own api keys. Take a look in
https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emuelec-emulationstation/package.mk
where to put them.

**Comment by 7Ji** [comment]
Wow a quick one miwasp! I was typing about that just before...

Anyway, @trvqhuy, if your issue about wireless driver is solved, you should close the issue and ask about your new problem in a new issue. It would be nicer for future readers when they want to find answer for a similar problem.

**Comment by trvqhuy** [comment]
Wow, thanks guys @7Ji @miwasp, honestly I'm really appreciate that, your supports are amazing!

> Anyway, @trvqhuy, if your issue about wireless driver is solved, you should close the issue and ask about your new problem in a new issue. It would be nicer for future readers when they want to find answer for a similar problem.

I will definitely do that in the future, thank you for your kind help @7Ji .
