### ISSUE TITLE
Make image fails with the Error 127

### ISSUE THREAD

**Issue by mastan30** [EmuELEC/EmuELEC#1104]
/mnt/g/gitProjects/EmuELEC$ PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC make image
./scripts/image mkimage
make: ./scripts/image: No such file or directory
make: *** [Makefile:10: image] Error 127

Seeing the above error whenever I try to create a image of new Emuelec, I am trying to build Emuelec and run emelec-addon but no luck

**Comment by shantigilbert** [comment]
Other than this `make: ./scripts/image: No such file or directory` there is absolutely nothing we can guess from this "issue" please use Github ONLY for bugs as noted here: https://github.com/EmuELEC/EmuELEC/issues/604
