### ISSUE TITLE
add support for RK322x boxes

### ISSUE THREAD

**Issue by prothej227** [EmuELEC/EmuELEC#1118]
Hi! I currently have an MXQ Pro running an RK3229 processor. Can someone here in the dev. team add support for these boxes? And if possible, can you demonstrate how to manually build EmuELEC for RK3229?

![image](https://z3.ax1x.com/2021/09/07/hT8Mrt.png)

**Comment by shantigilbert** [comment]
That chip is no supported. And it won't be supported anytime soon.
