### ISSUE TITLE
480CVBS not correctly centered via composite on CRT

### ISSUE THREAD

**Issue by TimeWarpGamer** [EmuELEC/EmuELEC#1120]
Hello,

In a world where finding a great retro platform with easy composite out for CRTs is surprisingly difficult, I'd love if this feature you be fixed for EmuELEC.  I'm testing on a fresh 4.6 installation with N2+ and here's what I've found so far: once you switch to 480CVBS the image on my CRT (I've tested three different ones, same issue ever time) is skewed to the left with a black bar down the right side of the screen.

I explored previous EE builds and the last time it seems to work properly with a centered image over composite is via 4.2.

I'd be happy to help troubleshoot this if the EE devs have time to work on it.  Thanks for you time :-)

**Comment by Langerz82** [comment]
As per our conversation here will be the fix, needs testing.
https://github.com/EmuELEC/EmuELEC/pull/1121

**Comment by drambit** [comment]
We are actively troubleshooting this over at https://emuelec.discourse.group/t/overscan-on-crt/1849. Just linking it here for completeness.

**Comment by Langerz82** [comment]
Added PR's that allow screen adjustment and custom frame buffers, so considered fixed.
