### ISSUE TITLE
Build error with the new pull

### ISSUE THREAD

**Issue by kylongmu** [EmuELEC/EmuELEC#1125]
[267.log](https://github.com/EmuELEC/EmuELEC/files/10712536/267.log)
This error looks caused by some difine in source code, detail output in the log file.
gmake[1]: *** [Makefile:458: qbitarray.o] Error 1
gmake[1]: *** [Makefile:341: qendian.o] Error 1
gmake[1]: *** [Makefile:467: quuid.o] Error 1
gmake[1]: *** [Makefile:383: qutfcodec.o] Error 1
gmake[1]: *** [Makefile:350: qbytearray.o] Error 1
FAILURE: scripts/build qt-everywhere:target during configure_target (package.mk)
*********** FAILED COMMAND ***********
./configure ${PKG_CONFIGURE_OPTS_TARGET}
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install qt-everywhere:target has failed!

**Comment by shantigilbert** [comment]
just add to this one https://github.com/EmuELEC/EmuELEC/issues/1122 , no need to open any more issues about this.
