### ISSUE TITLE
No Wifi Networks Found - S905x3 - EmuELEC 4.6

### ISSUE THREAD

**Issue by drtrdr23** [EmuELEC/EmuELEC#1127]
Describe the bug
I can't find the wifi network. I have reset many times but the device still says "No Wifi Networks Found". I also tried plugging in the network cable, but the device still say no network.

Expected behavior
Find the wifi network and connect to it

EmuELEC version:

    Version 4.6

Device (please complete the following information):

    SOC: S905x3
    Brand: x96 air
    Ram 4GB

**Comment by shantigilbert** [comment]
duplicate: #1114

**Comment by DavidOliM** [comment]
Same problem with my x96 max+ with same SOC, also no bluetooth
