### ISSUE TITLE
Brightness set to 100% after RetroArch

### ISSUE THREAD

**Issue by gingerbeardman** [EmuELEC/EmuELEC#1136]
**Describe the bug**
Brightness set to 100% after RetroArch

**To Reproduce**
1. In ES: Start > System Settings > Brightness > 10%
1. Run a game using RA
1. Brightness is still at 10%
1. Quit
1. Brightness is now 100%

**Expected behavior**
Brightness should remain as set and not change unexpectedly 

**Screenshots**
N/A

**EmuELEC version:**
 - Version: 4.6

**Device (please complete the following information):**
 - SOC: RK3326
 - Brand: GameForce
 - Model: Chi
 - Version: n/a

**Additional context**
- I'm playing N64 games using Mupen64plus 32bit
- I don't see any way of changing Brightness within RA?

**Comment by gingerbeardman** [comment]
Resetting RetroArch config did nothing

**Comment by Langerz82** [comment]
Try in RA Settings >> Configuration >> Save on Exit.

Where are you changing brightness? I couldn't find the option in the main menu.

In /storage/.config/retroarch/retroarch.cfg you can manually change the number under:
```
screen_brightness = "100"
```

**Comment by Langerz82** [comment]
It seems it might reset in the code, as AmberELEC has a patch to disable the reset here:
https://github.com/AmberELEC/AmberELEC/blob/dev/packages/games/tools/retroarch/patches/retroarch-disable_brightness_setting.patch

**Comment by gingerbeardman** [comment]
> Where are you changing brightness? I couldn't find the option in the main menu.

In ES: Start > System Settings > Brightness

Sadly none of your suggestions offer the solution.

**Comment by Langerz82** [comment]
@shantigilbert 
Will probably have to look into this one, because we usually have a patch that should disable the resetting of screen brightness located here:
packages/sx05re/libretro/retroarch/patches/OdroidGoAdvance/9999-emuelec-unify-brightness.patch

Gameforce should also use these patches. Maybe they are not applying properly.

**Comment by Langerz82** [comment]
I used an similar Odroid-Go Advance device and the brightness settings were being applied. Shanti might have to take a look at why Gameforce is not working the same.

**Comment by miwasp** [comment]
The patch still works fine for oga/ogs and gf, it just isn‘t applied to the 32bit version of retroarch. This needs to be fixed.

**Comment by gingerbeardman** [comment]
Aha! That would do it.

Only reason I am using it is that it's the only version that I could get to run Beetle Adventure Racing
