### ISSUE TITLE
scummvm  have no 18add58f142f0b0fe1614f79a9a9cb48aa3eb033

### ISSUE THREAD

**Issue by shiniankanchaige** [EmuELEC/EmuELEC#1149]
packages/sx05re/libretro/scummvm/package.mk 
![image](https://user-images.githubusercontent.com/49228914/224285569-5ea1eb68-44b2-407c-ac1d-86fc8f147cb0.png)

**Comment by zhuhellozhu** [comment]
+1 got this issue too
