### ISSUE TITLE
Where should the key settings be set in mupen64plus?

### ISSUE THREAD

**Issue by candychn** [EmuELEC/EmuELEC#1154]
N64 games have incorrect default buttons. How can I change them

**Comment by Langerz82** [comment]
In Retroarch you should be able to change the buttons in the quick menu. Do NOT change them in the main settings of retroarch as you will be changing buttons for all cores.

For more info see:
https://retropie.org.uk/docs/RetroArch-Configuration/

And this is not really an issue with the code so I'm closing it. If you need more help try the discourse or discord.
