### ISSUE TITLE
pocketcdg plays only distorted noise

### ISSUE THREAD

**Issue by worstcase-scenario** [EmuELEC/EmuELEC#1155]
EMUELEC 4.6 (Amlogic-ng.aarch64)
Machine model: Amlogic

When I’m trying to run a .cdg-file, pocketcdg is being launched via retroarch, but instead of playing the mp3-music, it only produces kind of a distorted, oldschool-modem-white noise… (while showing the karaoke text and all). 

This happens both when starting the .cdg-file from a gamelist in Emulationstation and directly loading the file in retroarch. 

When I remember correctly, this issue didn't happen on EmuElec 4.5... has there been an update / change to the pocketcdg-core? 

I'd be glad for any ideas, suggestions and solutions! Thanks.

**Comment by shantigilbert** [comment]
If the Retroarch volume is too high (above 100%) please try it with the volume around 70%

**Comment by worstcase-scenario** [comment]
The only audio-option I can find in retroarch is under Audio -- Volume Gain (dB)
And that is set on 0.0 - so normal, right?

Should I change this number?

**Comment by shantigilbert** [comment]
Maybe try copying the Pocketcdg core from 4.,5 to 4.6 (to /tmp/cores) to see if it's a core update issue.

**Comment by shantigilbert** [comment]
Is this still an issue?

**Comment by worstcase-scenario** [comment]
I would have to try it out again, after discovering EmuELEC has mplayer, I deleted the pocketcd-roms...

**Comment by shantigilbert** [comment]
confirmed working
