### ISSUE TITLE
Try to compile Amlogic-ne

### ISSUE THREAD

**Issue by kero990** [EmuELEC/EmuELEC#1156]
Hi, I saw that the upstream coreelec has officially supported the Amlogic-ne device, and I saw the relevant documents in the dev branch. I am now trying to compile a release of Amlogic-ne, but I get a lot of differences when I try to compile with different devices. mistake. I wonder if you guys tried compiling for Amlogic-ne? Can it be done correctly?
The bug with the most progress is now here
> [250/588] [DONE] install libretro-bash-launcher:target
> <<< SDL_GameControllerDB:target seq 260 <<<
> CLEAN      SDL_GameControllerDB
>     *      Removing /home/kero/EmuELEC/build.EmuELEC-Amlogic-ne.aarch64-4/build/SDL_GameControllerDB-cead9cccf79c0865cf8c2b7b652867372d63cd6e ...
>     *      Removing /home/kero/EmuELEC/build.EmuELEC-Amlogic-ne.aarch64-4/qa_checks/SDL_GameControllerDB-* ...
> UNPACK      SDL_GameControllerDB
>     APPLY PATCH (common)      packages/sx05re/tools/sysutils/SDL_GameControllerDB/patches/add-emuelec-gamepads.patch
> patching file gamecontrollerdb.txt
> Hunk #1 FAILED at 1.
> 1 out of 1 hunk FAILED -- saving rejects to file gamecontrollerdb.txt.rej
> *********** FAILED COMMAND ***********
> patch -d "${PKG_BUILD}" -p1 < ${i} 1>&${VERBOSE_OUT}
> **************************************
> *********** FAILED COMMAND ***********
> ${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
> **************************************
> *********** FAILED COMMAND ***********
> ${SCRIPTS}/build "${1}" "${PARENT_PKG}"
> **************************************
> FAILURE: scripts/install SDL_GameControllerDB:target has failed!
> 
> The following log for this failure is available:
>   /home/kero/EmuELEC/build.EmuELEC-Amlogic-ne.aarch64-4/.threads/logs/260.log
> 
> >>> SDL_GameControllerDB:target seq 260 >>>
> [251/588] [FAIL] install SDL_GameControllerDB:target
> 
> The following log for this failure is available:
>   /home/kero/EmuELEC/build.EmuELEC-Amlogic-ne.aarch64-4/.threads/logs/260.log
> 
> Parallel build failure - see log for details. Time of failure: Mon Mar 27 07:33:57 AKDT 2023
> make: *** [Makefile:10: image] Error 1

**Comment by shantigilbert** [comment]
Amlogic-ne is not supported on EmuELEC , needs a lot of changes for it to compile.
