### ISSUE TITLE
Supports Sega Saturn

### ISSUE THREAD

**Issue by Relobum** [EmuELEC/EmuELEC#1158]
Good afternoon.

Please tell me if EmuELEC supports Sega Saturn emulation?

And a question, how well it works, provided that a high-end device is used? Do crashes, freezes, etc. happen?

I heard that Sega Saturn emulation works a little worse than emulation of most other platforms. Is this true?

**Comment by Relobum** [comment]
I apologize insanely if I created this thread in the wrong section. I just couldn't find the right one. Sorry in advance.

**Comment by shantigilbert** [comment]
Use forum or discord for these kind of questions.
