### ISSUE TITLE
Major Issues with Overscan on CRT

### ISSUE THREAD

**Issue by drambit** [EmuELEC/EmuELEC#1166]
I'm trying to play PSX games from EmuElec on A95X F3 Air (it's just a generic s905x3 android tv box,) through composite output to a Sony Trinitron CRT. There is major issues with overscan that I can't manage to fix yet.

Photo of what it looks like:
[https://canada1.discourse-cdn.com/free1/uploads/emuelec/optimized/1X/393b556bde6950449deca875dd071841d97c3bc5_2_666x500.jpeg](url)

Photo of what it looks like after using "echo "ee_videowindow=10 5" >> /emuelec/configs/emuelec.conf " command, with setres.sh, and set to 480cvbs.

[https://canada1.discourse-cdn.com/free1/uploads/emuelec/optimized/1X/474ba29b43328e2ed2b923792bc83ad7dbe98b4e_2_666x500.jpeg](url)

I have an open forum post here where we have been trying to solve the problem, much to no avail so far: [https://emuelec.discourse.group/t/overscan-on-crt/1849](url)

Is there a way to correct the size and position of the picture so that it fits nicely?

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/604
