### ISSUE TITLE
mpv not using hardware decoding

### ISSUE THREAD

**Issue by 25minutes** [EmuELEC/EmuELEC#1169]
**Describe the bug**
I try to use mpv to play media files from /storage/roms/mplayer folder. It works but it doesn't seem to use hardware decoding, even if I manually edit playvideo.sh and add --hwdec=auto --hwdec-codecs=all.

I fully understand there can be limitations for media play on EmuELEC. Just want to verify if this is something expected, or if I didn't do it right . Thanks.

**To Reproduce**
Put any standard mp4 or mkv media files in /storage/roms/mplayer, then play it via ES.

**Expected behavior**
Ideally, mpv should be able to play media files with hardware decoding.

**Screenshots**
n/a

**EmuELEC version:**
 - v4.6

**Device (please complete the following information):**
 - SOC: S905x2

**Comment by shantigilbert** [comment]
> Ideally, mpv should be able to play media files with hardware decoding.

But it does not. MPV does not work with HW decoding on fbdev, or at least I could not get it to work, and no further attempts will be made, sorry.
