### ISSUE TITLE
advance mame with xbox360 wireless controller

### ISSUE THREAD

**Issue by dewenhsu** [EmuELEC/EmuELEC#118]
Odroid N2 + emuelec 3.5 test + xbox360 wireless controller + usb keyboard
I can use keyboard 6 and 2 to insert coin and start game
the controller can use direction pad, but fire bomb ( A and B button ) is not working.
the keyboard direction and A B ( ctrl and alt ) works.
I wish to call advmame config menu by press keybard "tab",
but it is not work.
Is there a way to call the advmame config menu so I can map the controller ?
thank you !

**Comment by shantigilbert** [comment]
What happends if you press the guide button? on the controller, or the L3 or R3 ?

**Comment by dewenhsu** [comment]
guide button no response. LT RT and all possible button no response.
but if I use keyboard 6 and 2 to enter game, the direction pad is working.
there is no L3 or R3 for xbox360 wireless controller.
thank you.
there is a config file for advmame ( advmame.rc )
it seems can add config for the controller mapping, but I still can not get success.

**Comment by shantigilbert** [comment]
I can confirm that there was an issue with advmame, it will be resolved on the upcoming version.

**Comment by dewenhsu** [comment]
thank you very much !

**Comment by shantigilbert** [comment]
Can you replace this script `/emuelec/scripts/set_advmame_joy.sh` with this one

https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emuelec/config/emuelec/scripts/set_advmame_joy.sh

and also add this `device_joystick raw` to `/storage/.advance/advmame.rc`

And test to see if your gamepad is now working?

**Comment by dewenhsu** [comment]
Thank you !
It works. Now I can press keyboard "Tab" to call advmame menu, and config the controller.

**Comment by shantigilbert** [comment]
Fixed on v3.6

**Comment by dewenhsu** [comment]
Thank you !

shantigilbert <notifications@github.com> 於 2020年6月15日 週一 下午2:26寫道：
