### ISSUE TITLE
Descent 1&2 ports

### ISSUE THREAD

**Issue by apatuka** [EmuELEC/EmuELEC#1200]
**Is your feature request related to a problem? Please describe.**
It's not about a problem.

**Describe the solution you'd like**
Descent 1&2 port for Emuelec

**Describe alternatives you've considered**
Using MsDos emulation but will be nice to have a native port for the operating system for better performance.

**Additional context**
The source code is here
https://github.com/dxx-rebirth/dxx-rebirth

I know how to compile but i don't know nothing about integrating into Emuelec
It Uses SDL 2

**Comment by worstcase-scenario** [comment]
I think Descent 1 & 2 are both available with PortMaster...

**Comment by shantigilbert** [comment]
These are in fact available in Port Master, closing
