### ISSUE TITLE
gamepad hd-060 works fine when playing a game , after leaving it the controller crash and when reconnecting the controller , it is paired but not connected ( i should restart the computer every time i leave a game )

### ISSUE THREAD

**Issue by Anonymey0** [EmuELEC/EmuELEC#1202]
gamepad hd-060 works fine when playing a game like AC Creed ( ubisoft connect) fall guys (epic games) dbx2 (steam), after leaving it the controller crash and when reconnecting the controller , it is paired but not connected ( i should restart the computer every time i leave a game ) OS: WIN 11

1. connecting the gamepad to Bluetooth ( works fine)
2. Click on a game and play it 
3. leave the game
4. controller CRASH 
5. after reconnecting the pc263 paired but not connected

![before](https://github.com/EmuELEC/EmuELEC/assets/137336540/04f655ee-713f-49e3-8ef8-7aa93ad90b8a)
![after](https://github.com/EmuELEC/EmuELEC/assets/137336540/95183dca-30aa-45ef-86d7-6a8d4ae874dd)

hd-060 gamepad :https://www.alibaba.com/product-detail/Wireless-Elite-game-controller-for-PS4_60854500059.html
 Brand: unknown 
it considered as ds4 v2

**Comment by 7Ji** [comment]
How is this related to EmuELEC?
