### ISSUE TITLE
Problems with the game MarioGolf64. I've tried changing all emulators. He starts the game, and on the first shot, the RED screen appears

### ISSUE THREAD

**Issue by Mario64Golf64** [EmuELEC/EmuELEC#1213]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**EmuELEC version:**

**Device (please complete the following information):**
 - SOC: [e.g. S095x3]
 - Brand: [e.g. Beelink]
 - Model [e.g. mini g1]

**Additional context**

**Comment by Mario64Golf64** [comment]
Problems with the game MarioGolf64. I've tried changing all emulators. He starts the game, and on the first shot, the RED screen appears

**Comment by Kelvfimer** [comment]
Pls follow the template with those values not filled in. We can't help. So we need the emuelec version, board you are using etc

If not we have ti close the request.

**Comment by Mario64Golf64** [comment]
![1](https://github.com/EmuELEC/EmuELEC/assets/142372723/73c29bdd-9d58-4988-8228-a126abcf43e1)
![2](https://github.com/EmuELEC/EmuELEC/assets/142372723/1edeccda-6ff2-451f-8b26-57ff6fb6156d)
![3](https://github.com/EmuELEC/EmuELEC/assets/142372723/86dae8a8-c107-4353-bf01-1de55d7690d2)
![4](https://github.com/EmuELEC/EmuELEC/assets/142372723/0d61f747-6609-4549-85ef-e491b05672cb)
![5](https://github.com/EmuELEC/EmuELEC/assets/142372723/cebe99e4-22e2-414e-b519-11c9c8214b42)
![6](https://github.com/EmuELEC/EmuELEC/assets/142372723/f555087c-45f8-4550-a6a8-e4abbf069339)
![7](https://github.com/EmuELEC/EmuELEC/assets/142372723/5a261377-bf77-4f82-a928-23bc8c857a51)
![8](https://github.com/EmuELEC/EmuELEC/assets/142372723/65683cf0-88d1-483b-b2d4-87bb7b593524)
![9](https://github.com/EmuELEC/EmuELEC/assets/142372723/aa261399-eb07-4b58-a77d-fcb65c811ab6)
![10](https://github.com/EmuELEC/EmuELEC/assets/142372723/69a9acba-d497-4172-a3cb-4fbf94806702)
![11](https://github.com/EmuELEC/EmuELEC/assets/142372723/8638b644-6a58-432f-96da-073757d3d284)
![12](https://github.com/EmuELEC/EmuELEC/assets/142372723/7db66152-8446-4b7d-a227-f61063ce78be)
![13](https://github.com/EmuELEC/EmuELEC/assets/142372723/fa6d176f-da7e-47ed-a369-6701f10e8632)
![14](https://github.com/EmuELEC/EmuELEC/assets/142372723/1b7d3150-e7d3-48a7-850e-67bc50c444eb)

**Comment by Mario64Golf64** [comment]
Do you need any more information?

**Comment by Kelvfimer** [comment]
Tested in the latest version 4.6. It is working in all emulators except mupen64 32bit. It is an emulator issue not Emuelec issue.

Btw mupen64plus is not recommended to be used as the development was stopped in 2019.

Pls, for more info read

https://github.com/libretro/mupen64plus-libretro

You must use mupen64plus next or parallel. I tested on both of them and it works. 

Finally, remember we do NOT support custom systems with non official Emuelec embeded as the one you are using from Vayava. So be careful if you follow any official upgrade guide, you can brick your device and it will no longer work.

With an official Emuelec image, the recomendation is to be in the latest version but this Vayava device it is not official and unknown for us.

Thx
