### ISSUE TITLE
Can't load theme list in batocera-es-theme

### ISSUE THREAD

**Issue by yingw** [EmuELEC/EmuELEC#1222]
Dev branch, newest code, compile and build successfully.

Can't load theme list, defined in `batocera-es-theme`, it show "no item", and nothing useful in the backend log "es-log.txt"

![9d5379b5c90d46bd8ebafb9bec7b6dc](https://github.com/EmuELEC/EmuELEC/assets/1177503/4ebaada0-5c52-40f1-9122-f6932e4a5990)

![image](https://github.com/EmuELEC/EmuELEC/assets/1177503/943f0f6d-a690-4cda-907e-808ae1a592bc)

![image](https://github.com/EmuELEC/EmuELEC/assets/1177503/508ba07f-2d86-4749-91c2-315a07534cf1)

![image](https://github.com/EmuELEC/EmuELEC/assets/1177503/b138725c-edc4-4979-8657-5ea2f22e8c69)

**Comment by Kelvfimer** [comment]
@yingw known issue the way the themes are downloaded changed. We need to fix it. thx

**Comment by shantigilbert** [comment]
This should be fixed now.
