### ISSUE TITLE
Just one scraper "ARCADEDB", no "ScreenScraper"

### ISSUE THREAD

**Issue by yingw** [EmuELEC/EmuELEC#1223]
Dev branch, newest code, compile and build successfully.

Just find one scraper in menu: "ARCADEDB", no  "ScreenScraper" and "TheGamesDB",  guess need a API key? Is there any guide to setup?

**Comment by 7Ji** [comment]
https://github.com/EmuELEC/EmuELEC/blob/57b6f21dc6be45140ad98a6a96982048e7fe8328/packages/sx05re/emuelec-emulationstation/package.mk#L25
