### ISSUE TITLE
Arcade controls won't connect + EMUELEC folder not available in explorer - S905x3 ver4.6

### ISSUE THREAD

**Issue by legendofvolnutt** [EmuELEC/EmuELEC#1233]
Hey guys I'm new here, so I'm pretty much done my custom arcade cabinet but I'm now at a stand still...

So first off I had connected my wifi and my computer had detected the box through network sharing so I customized a theme and added a few roms to test it out... it worked great but then when I went to try again I was never able to detect it again. So far I have not been able to find anyone else with this issue. I've tried reformatting my sd, using version 4.3, another sd card, and another box that's identical, although with the same card that is now updated back to 4.6. 

My other issue is that I bought a sanwa/bosega encoder from amazon with an il eurostick and knockoff happ buttons from arcade world uk, and the system recognizes the board when its plugged in without the ground cables, but crashes with them in, and the buttons are not recognized when I try to map them, both in emulation station or retroarch.

Are there fixes for either of these? Thanks guys.

**Comment by shantigilbert** [comment]
> and the system recognizes the board when its plugged in without the ground cables

this should be your hint that it is either your cabling or your board, not EmuELEC related. 

> it worked great but then when I went to try again I was never able to detect it again. So far I have not been able to find anyone else with this issue. I

From this description this again seems to be something external to EmuELEC.
