### ISSUE TITLE
Simple POWER OFF UX

### ISSUE THREAD

**Issue by nevmind** [EmuELEC/EmuELEC#1242]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In order to power off , it's necessary to navigate power off menu after pressing start button in emulstation.
but menu depth is too deep so it's not easy to use.

So, it would be very good to provide shortcut of power off
ex) 
1. move original select button function to somewhare in main menu.
2. provide various option to select power off method 
   a) press select button : popup to ask power off or not, default value is power off
   b) press select button long : power off immediately
   c) press select button : power off immediately

**Describe alternatives you've considered**
provide system power off menu on top of menu when you press start button in emulstation

**Additional context**

**Comment by shantigilbert** [comment]
Sorry I don't think this will be added just to save 2 button presses.
