### ISSUE TITLE
Using sortname as display name is not readable

### ISSUE THREAD

**Issue by yingw** [EmuELEC/EmuELEC#1264]
in EmuELEC-EmulationStation, when using Detail view and "sort by sortname", the display name in the list will be sortname. I think the real name is better, and sometime the sortname is nonsense to used as display name.

In some non-English area, to sort the game list using their language, they have to use sortname to sort them. But the sortname is some letter (Such as Chinese Pinyin) convert to English letters, it can be sort , but not readable.

Eg:

Using name as sort property, It looks great , but the order is a mess:

![Screenshot 2023-11-27 10-39-12](https://github.com/EmuELEC/EmuELEC/assets/1177503/07ecbc0a-4c34-4620-b0eb-5e32ea5d6e6b)

Using sortname as sort prop. Order is good, the looks like this:

![Screenshot 2023-11-27 10-39-31](https://github.com/EmuELEC/EmuELEC/assets/1177503/7930adec-71db-45cb-b344-ad84074b6b41)

It make the game name unreadable.

So please, can it be reasonable to change this to use name as display always?

BTW, the sortname function is great, works correctly, it helped nonengalish area to sort names.
And, in the Detailed Carousel view, the name is always the name, not sortname, it's great. I think that's the correct solution.

![Screenshot 2023-11-27 10-56-27](https://github.com/EmuELEC/EmuELEC/assets/1177503/74bef44b-bff0-443e-9de0-3818e38e7a99)

And the code might be here: [code](https://github.com/EmuELEC/emuelec-emulationstation/blob/232e540e5f56132dbf28e1b0ac31a5682d02bdce/es-app/src/views/gamelist/GameNameFormatter.cpp#L120-L123)

**Comment by Langerz82** [comment]
sorting is based on the english alphabet, this is the same with standard emustation.

**Comment by yingw** [comment]
I tried to delete that 4 lines code and rebuild image, and then everything runs fine to me .

**Comment by Langerz82** [comment]
@yingw I'll add the option to hide sortnames when displaying the gamelists when I get some time soon.

**Comment by Langerz82** [comment]
@yingw to test check here:
https://github.com/EmuELEC/emuelec-emulationstation/pull/85

**Comment by Langerz82** [comment]
Closing issue as feature to disable show sortname is included in latest revision.
