### ISSUE TITLE
Which DTB  do I use?

### ISSUE THREAD

**Issue by AlaaDidan** [EmuELEC/EmuELEC#1294]
I have a device labeled "3d Game linux" and I need to reinstall the "Emuelec" system, but I do not know which DTB is suitable for my device? Note that I am currently in the process of installing version 4.6, and the device is small and white. I think these devices are called “Game Stick.” It is connected directly to the TV with an HDMI input and a USB power cable.

**Comment by worstcase-scenario** [comment]
This is not the forum for your device, we do not support those companies, please ask whoever sold you the device and post your concerns there.

You have purchased a box that illegally uses Emuelec without authorization. These kind of companies make money with these devices, which is strictly not allowed. See here:

https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices#special-not
