### ISSUE TITLE
Disable filters

### ISSUE THREAD

**Issue by chenteparao** [EmuELEC/EmuELEC#130]
Hi, I put a filter in retroarch and in PSX games look really bad, how disable filters from retroarch again?

Thanks guys

**Comment by shantigilbert** [comment]
The same way you enabled them?

**Comment by chenteparao** [comment]
No, there in sot the same way because when I active just press the button over the fiter, but there is not a button to disable

I was seeing in retroarch ans pressing start butto the option over you are change to custom.
