### ISSUE TITLE
[EE 4.7] Savestates problems

### ISSUE THREAD

**Issue by Quantum1997** [EmuELEC/EmuELEC#1319]
**Describe the bug**
Savestates from EE 4.6 fail to load, and newly created savestates don't appear in EmulationStation savestates menu.

**To Reproduce**
1. Opening EmulationStation savestates menu and seeing EmuElec 4.6 savestate (created in slot 0) being there normally
2. Trying boot the ROM by clicking the savestate, EmuElec loading screen appears, then exits ROM and comes back to the menu
3. Normally booting the ROM
4. Pressing the Load savestate hotkey, message appears that says something like "failed to load savestate"
5. Pressing the Save savestate hotkey to see if newer savestates can be loaded, savestate successfully created (on the same slot the older one was)
6. Pressing Load savestate hotkey again, this time newer created savestate loads succsessfully
7. Exiting ROM, going back to the menu, still seeing the old EmuElec 4.6 savestate (created in slot 0) there, but not seeing the newly created saveslot
8. Deleting old EmuElec 4.6 saveslot, succesfully dissapear from EmulationStation savestates menu, but EmuElec 4.7 new savestate still not appearing
9. Trying to create a savestate to a ROM that never had a previous savestate before, same problem happens
10. Opening EmulationStation savestates menu, still seeing the old EmuElec

**Expected behavior**
Savestates backed up from Emuelec 4.6 should be able to boot up, newly created savestates from Emuelec 4.7 should be displayed in Emulation Station savestates menu.

**Screenshots**
No need, problem can be understood from text.

**EmuELEC version:**
 - Version [EmuElec 4.7]

**Device (please complete the following information):**
 - SOC: [S095x3]
 - Brand: [HK1 Box]
 - Model [ Amlogic S905X3]
 - Version [Android 9]

**Additional context**
Nothing to be added.

**Comment by Quantum1997** [comment]
> is it the same as #1313 ?

It is similar (may even be the same problem), but I decided to create this issue because not only my device is newer (so it may not be expected to only happen on much older devices), but I also noticed these extra details I haven't seen in that post (such as failing to load these older savestates at all, and the problem of displaying newly created ones on EmuStation). That post talked mainly about auto savestates. 

I am aware that we should not post issues about the same bug, but I felt that these details might be important to be known as well, since I am not entirely sure if they are even linked (who knows if solving auto savestates problem in that thread might fix the EE 4.7 not displaying savestates at all problem)

**Comment by shantigilbert** [comment]
Can you test the solution provided in: https://github.com/EmuELEC/EmuELEC/issues/1313#issuecomment-1961856926

**Comment by shantigilbert** [comment]
Fixed in a157e8796979b790e38cc0f04fdb22a69aeab3ae

**Comment by Quantum1997** [comment]
> Fixed in [a157e87](https://github.com/EmuELEC/EmuELEC/commit/a157e8796979b790e38cc0f04fdb22a69aeab3ae)

Sorry for the very late answer, been really busy lately! I finally got to try out this sollution, and I can say it works perfectly! Now savestate feature finally works just as intended. Thank you for providing this!
