### ISSUE TITLE
I encountered a strange problem

### ISSUE THREAD

**Issue by 2494654220** [EmuELEC/EmuELEC#1327]
![20240229192455](https://github.com/EmuELEC/EmuELEC/assets/129390910/9d35d672-eca9-47b1-af55-acba3a7750c4)
When this interface appears, all keys are prohibited from using
Unable to exit
Can only disconnect the power supply

**Comment by 2494654220** [comment]
> 这不是一个系统错误，只是缺少一个模拟器的ROM集（我猜是Final Burn？）的消息。您应该能够通过按 HOTKEY + SELECT 返回 EmuELEC。通过该组合，您始终可以离开任何模拟器并返回 EmuELEC。

no,When this interface appears, all keys are prohibited from using

**Comment by 2494654220** [comment]
HOTKEY + SELECT ， no effect

**Comment by worstcase-scenario** [comment]
Hmmm. It is working for me. With which button-combination do you usually quit running emulators?
