### ISSUE TITLE
Support for T96 Quad 1 GB Ram possible?

### ISSUE THREAD

**Issue by jocire** [EmuELEC/EmuELEC#133]
This is my Android Box, which I sadly can not get running. It does not recognize any of my USB Game Controllers. Not even the Logitech Dual Action. I was hoping with EmuELEC it will work out.

**Comment by jocire** [comment]
Here the box:
https://neodigitalperu.com/android-tv-box-t96-4k-ram-1gb-rom-8gb

**Comment by DKAngel2000** [comment]
its a rockchip based box not an amlogic so emuelec wont run with it as it is aimed at amlogic devices

here is some help https://mxqproject.com/rockchip-rk3229-libreelec-kodi-18-5-firmware/

**Comment by jocire** [comment]
Thank you for clarifying this!
