### ISSUE TITLE
EmuELEC does not load quick saves.

### ISSUE THREAD

**Issue by pr4ce** [EmuELEC/EmuELEC#1339]
**Describe the bug**
I have a GT King console running on the EMUELEC 4.6 system. 
Yesterday, I updated EMUELEC to 4.7. 
After that, all my quick saves stopped loading. 
EMUELEC can see them and shows screenshots of these quick saves, but when I try to load from them, it starts loading and then goes back to the game list after a few seconds.

I checked all the paths in RetroArch for quick saves. They are correct. If I make a quick save while in a game, I can load it while still in the game. When I exit the game, I see a new quick save in EmuELEC for that game. But when I select it, a screen with the EmuELEC logo appears, and after a moment, it goes back to the game list.

**To Reproduce**
1. Go to PlayStation games (or any other)
2. Click on any game (run any game)
3. Do quick save (super button + R2)
4. Exit the game
5. Press the triangle on the game to open the quick menu and check if you see the quick save for this game.
6. Select the quick save (click on it)
7. It does not work (does not load quick save)

**Expected behavior**
It should work like it did in version 4.6. Load the "quick save" and start the game from the saved state.

**Screenshots**
I can provide a video if you need it.

**EmuELEC version:**
 - Version 4.7

**Device:**
 - SOC: S922X
 - Brand: Beelink
 - Model GT King

**Comment by shantigilbert** [comment]
#1313
