### ISSUE TITLE
how build a simple program

### ISSUE THREAD

**Issue by denisdemaisbr** [EmuELEC/EmuELEC#1348]
I want build a C (lua interpreter) program to run on emuelec (cross compile using linux, ubuntu).
To download at box using wget/curl and run it.

Any tips to install 'build essentials' to emuelec?

Any can help me?

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/wiki/DEV:-How-to-compile-toolchain-only
