### ISSUE TITLE
Updating Ports metadata/scraping using PortMaster does not work

### ISSUE THREAD

**Issue by djibux** [EmuELEC/EmuELEC#1359]
**Describe the bug**
Ports metadata installed using PortMaster are not visible in EmulationStation.  PortMaster should update Metadata.

**To Reproduce**
1. Start PortMaster
2. Install a game
3. Optional: force download of metadata using Options > Metadata Refresh
4. Exit PortMaster
5. Update Gamelist (Go to Main Menu > Game Settings > Update Gamelist)

**Expected behavior**
The gamelist.xml should be updated and include description and media for newly added games.

When forcing Metadata Refresh, PortMaster does mention that it’s updating the gamelist.xml, but changes are not visible.  ~~In fact I’m not sure where it is storing its gamelist: changes are not reflected in either `rom/ports` or `rom/ports_scripts`.~~

**EmuELEC version**
 - Version: 4.7

**Device**
 - GameForce Chi

**Comment by worstcase-scenario** [comment]
Did you check if the option "Parse game list only" is disabled?

**Comment by djibux** [comment]
Yes, it is disabled in the "Frontend Developer Options" menu.

**Comment by djibux** [comment]
I have done some further digging and what I have written above is not entirely true: the gamelist.xml in the `ports` folder does seem to be updated by PortMaster and include metadata.  But for some reason, it is just ignored by Emulationstation that uses gamelist.xml in the `ports_scripts` folder.

**Comment by worstcase-scenario** [comment]
I don't know if the EmuELEC team can solve this, I guess you should perhaps also contact the portmaster-crew and ask them if it's possible that they change the code so that the gamelist.xml-file is also stored under the ports_script-folder? 
An other solution would be to create a script that runs on boot, which copies the gamelist.xml-file in ports to ports_scripts... but that would be a workaround...

**Comment by worstcase-scenario** [comment]
I found the script that generates the gamelist.xml for portmaster. Here is the github, I guess you could add that issue there and see if they will update it....

https://github.com/tobio-tenma/ports_to_gamelist

**Comment by worstcase-scenario** [comment]
They also have a discord server with a lot of activity, so perhaps the faster way would be to ask there about that issue...

https://discord.gg/vVtK8F93

**Comment by worstcase-scenario** [comment]
When I have the time, I'm going to test another script that merges the content of the /ports/gamelist.xml into the /ports_scripts/gamelist.xml file. If it works, I'll publish it here.

**Comment by djibux** [comment]
Thanks for all that.
Media for the ports/gamelist.xml is in the ports folder, so copying the list to ports_scripts/gamelist.xml won’t work without updating file paths.  I’ll test my luck on the discord server.

**Comment by worstcase-scenario** [comment]
I now have a python script that lets me choose which downloaded game from PortMaster (re. which entry from the gamelist.xml in /ports) I want to merge into the /ports_scripts-gamelist.xml (including the image and desc-tags). It works!

**Comment by shantigilbert** [comment]
> Is the ports_scripts folder specific to Emuelec? I don’t see it mentioned by PortMaster, and in which case I believe the issue is more on Emuelec side.

yes it is.

Can you do me a favor and move the generated gamelist.xml to the `ports_scripts` (or `ports` if its already in `ports_scripts`)

**Comment by djibux** [comment]
Hello,
@shantigilbert.  The generated gamelist is in the ports folder but seems to be ignored by EmulationStation.  Moving the gamelist from ports to ports_scripts does not fully work because media files are in the ports folder.
I mentioned the issue on Discord and kloptops said he would look into it.
@worstcase-scenario, maybe you should liaise with him and share your script.
Thanks.

**Comment by miwasp** [comment]
There was an update of Portmaster a few hours ago which fixes this.

**Comment by djibux** [comment]
Awesome!  I’ll test this evening and close the issue.

**Comment by djibux** [comment]
I have tried both the stable and beta channels but I don’t get any metadata for ports installed with portmaster.  Did you face the same issue @miwasp?

**Comment by djibux** [comment]
I reached out on Discord.  Indeed the new version included a fix, but there was an issue with script paths in the gamelist.xml.  It should be fixed tomorrow.

**Comment by djibux** [comment]
Fixed.  Nice job!
