### ISSUE TITLE
SSH connection issue on Phicomm N1

### ISSUE THREAD

**Issue by April-BOY** [EmuELEC/EmuELEC#136]
I just start Emuelec on Phicomm N1 with USB drive.But my gamepad is not detected with USB mode.Jsut like that.
![emuelec卡机画面](https://user-images.githubusercontent.com/19245482/76694713-52a4d480-66b1-11ea-9a92-ee743c1e4714.jpg)
So I want to pair my controller through bluetooth.When I connect to Phicomm N1 with SSH,the putty and the MobaXterm just show the same prompt："Network error:connection refused".
![N1ssh登录失败](https://user-images.githubusercontent.com/19245482/76694763-0908b980-66b2-11ea-84d7-9f5b515d05e9.png)

**Comment by shantigilbert** [comment]
AFAIK That box needs some sort of hack to boot it, so I have no idea what changes they make that might affect this.
