### ISSUE TITLE
Compilation error with dev branch

### ISSUE THREAD

**Issue by meeuuh92** [EmuELEC/EmuELEC#1360]
Hi,

I try to compile the dev branch for using most recent version of retroarch. I've got trouble with my bluetooth gamepad with last release. So i've got error with some packages : dtc, connman and advancemame.. For, dtc and connman i had need to change the url of zip file... But for advancemame, it's seems to be an error in build script... 

Regards and thank you for emuelec's job ..

**Comment by shantigilbert** [comment]
Post logs
