### ISSUE TITLE
PS1 button problem

### ISSUE THREAD

**Issue by Kez66** [EmuELEC/EmuELEC#1361]
Hi all. I'm having a problem with the PS1 controllers. Indeed, since my switch to EmuELEC 4.7 the L2 and R2 keys are no longer recognized in my PS1 games. Example: Tomb Raider, Last Revelation...
I came back to 4.6, the L2 and R2 keys work perfectly. I redid an installation to 4.7 but nothing works, the "bug" persists. So I stayed on version 4.6.

Am I the only one experiencing this problem?

Yours sincerely,

EmuELEC 4.7

Device : Android 11 Smart TV Box
 - SOC: s905x4
 - Brand: HEYNOW

**Comment by worstcase-scenario** [comment]
Do a update to 4.8.TEST-version, for example via the UPDATE menu (update-type BETA).

https://github.com/EmuELEC/EmuELEC-tests/releases/tag/v4.8-TEST-04212024
