### ISSUE TITLE
about the new update an my box 

### ISSUE THREAD

**Issue by victor64x4** [EmuELEC/EmuELEC#1365]
Hello friends, I was checking out the new update for EmuELEC and I'm not 100% sure if it will install properly on my arcade box. That's why I thought it would be best to ask first. The TV box has the following specs:

Amlogic S905M chip
Quad-core ARM Cortex-A53 CPU
Mali-450 GPU
8 Ram

**Comment by Langerz82** [comment]
If it's a S905M chip I doubt it has 8GB RAM.

Try using the dtb file:
gxl_p281_1g.dtb (1 GB RAM)

But ArcadeBox is not a supported device so dont expect anymore help see:
https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices

Closing as not an issue with the repo.
