### ISSUE TITLE
Black Screen on boot on Banana Pi BPI-M5

### ISSUE THREAD

**Issue by Droppix** [EmuELEC/EmuELEC#1366]
**Describe the bug**
I tried to install emuELEC (4.7, 4.5, or 4.3) on a Banana Pi BPI-M5, without success (I tried different DTB: sm1_s905x3_4g_1gbit, sm1_s905x3_bananapi_m5, ...), I systematically get a black screen!
I tried with a CORELEC image (CoreELEC Amlogic-ng 9.2 for Bananapi M5.img) or Armbian 24.5.1 Bananapim5 minimal.img.xz, and the boot works fine!

**To Reproduce**
1. Flash 'EmuELEC-Amlogic-ng.aarch64-4.7-Generic.img.gz' on SD Card 32GB, 256GB (differents brand)
2. Copy the sm1_s905x3_4g_1gbit.dtb or sm1_s905x3_bananapi_m5.dtb (various DTBs tested), rename on dtb.img
3. Then try booting

**Expected behavior**
On boot, black screen, no messages...

**EmuELEC version:**
 - Version 4.7, or 4.5, 4.3

**Device (please complete the following information):**
 - SOC:S095x3
 - Brand: Banana Pi 
 - Model BPI-M5

**Comment by 7Ji** [comment]
> CoreELEC Amlogic-ng 9.2 for Bananapi M5.img

is not an official CE image, CE had no official 9.2 M5 image. CE, and inherently EE, uses the generic image for BPi-M5, there's none dedicated image. You'll need to install Android first before running either CE or EE, as per [CE wiki](https://wiki.coreelec.org/coreelec:bpi):
> Prior to installing CoreELEC, the Android firmware has to be flashed to the SBC.
