### ISSUE TITLE
X96 Mini

### ISSUE THREAD

**Issue by actraiser30** [EmuELEC/EmuELEC#1372]
Hello 

I have a X96 Mini Android tv box

With cpu Amlogic S905W

Will Emuelec work with my hardware??

If yes I use the generic image?

Thanks

**Comment by actraiser30** [comment]
At least you can say something very helpful thx for nothing

**Comment by shantigilbert** [comment]
Maybe take 10 seconds to read the rules posted instead of being entitled.

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!
