### ISSUE TITLE
I want to make some change in the splash screen. How can I do that?

### ISSUE THREAD

**Issue by sc0rp10n-py** [EmuELEC/EmuELEC#1378]
Hi, I wanted to make changes to splash screen like text and image, I found image, but I can't located where the text is.

**Comment by sc0rp10n-py** [comment]
"EmuELEC is FREE! NOT FOR SALE!" this text

**Comment by shantigilbert** [comment]
The text is there for a reason, please don't remove it

**Comment by sc0rp10n-py** [comment]
@shantigilbert ok I will not change
But at this stage where I have searched through entire codebase rigorously.
I am curious as to how was this text added?
