### ISSUE TITLE
How to set up to start from EMMC first, when EMUELEC4.7 system is on TF card

### ISSUE THREAD

**Issue by crazywjj** [EmuELEC/EmuELEC#1385]
How to set up to start from EMMC first, when EMUELEC4.7 system is on TF card

**Comment by crazywjj** [comment]
My Android TV is installed on EMMC, and when I boot up, it will first start EMUELEC in my TF card instead of entering Android TV first. I hope to start Android TV in EMMC first when booting up. thank you

**Comment by worstcase-scenario** [comment]
Just remove your card before booting up.

**Comment by crazywjj** [comment]
Removing the TF card can start Android TV from EMMC, but in fact, I want to insert the TF card and enter Android TV. I haven't found a way to modify the startup menu yet

**Comment by shantigilbert** [comment]
This is not an EmuELEC issue, this is handled by your device.
