### ISSUE TITLE
How to Install Drastic DS emulator on Emuelec without internet connection?

### ISSUE THREAD

**Issue by Exia-Ti885** [EmuELEC/EmuELEC#139]
Hello, since emuelec did not detect my tv box Wifi chip (x10 Max+), I cant use internet on it, but I realize on script menu, I have to install Drastic in order to do it, I have to connect to internet, is there any way to install Drastic on emuelect without internet? Thank you in advance.

**Comment by petesimon** [comment]
why completed? where is an answer to [Exia-Ti885](https://github.com/Exia-Ti885)'s question?

**Comment by Kelvfimer** [comment]
@petesimon because the only way is via internet. No connection no drastic in a supported way. There is a way downloading it and then via USB copying it but it is for advanced users.
