### ISSUE TITLE
T95 Max+ Not Booting into EMUELEC

### ISSUE THREAD

**Issue by Caninusouza** [EmuELEC/EmuELEC#141]
Bought the exact same box recommended by ETA Prime on his video and followed his tutorial step by step multiple times. It keeps booting into Android TV. Tried other different files from the tree than the one he recommended and nothing. Any chance you may know what is happening?

Thank you

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/129

**Comment by snakect77** [comment]
I found the same problem with the same box t95max + amlogic s905x3, using apk aida64 mi from model tvbox franklin device franklin platform
can anyone start emuelec on this device?

**Comment by DKAngel2000** [comment]
> I found the same problem with the same box t95max + amlogic s905x3, using apk aida64 mi from model tvbox franklin device franklin platform
> can anyone start emuelec on this device?

download terminal emulator, load it up and type reboot update with your sd card in and presuming you set the card up properly it will boot, as per the instructions above
