### ISSUE TITLE
Feedback on two issues in master_32bit

### ISSUE THREAD

**Issue by 2494654220** [EmuELEC/EmuELEC#1424]
1. Unibios switching to AES is invalid
2. The IPS patch is invalid, but romdata can be used
https://github.com/libretro/FBNeo
![IMG_20241013_024957](https://github.com/user-attachments/assets/3462dbf4-5c10-4d07-958d-25cbac78808a)

**Comment by Langerz82** [comment]
You are better off reporting those issues with libretro FBNeo. because we don't usually try and fix core issues themselves.
