### ISSUE TITLE
EmuELEC fails at boot with "can't mount sysroot"

### ISSUE THREAD

**Issue by dimk1** [EmuELEC/EmuELEC#143]
As the title says, EmuELEC fails to boot with the message can't mount sysroot. I then enter exit and the fail messages conitnue with can't access KERNEL,etc. Any idea what might be wrong?

**Comment by shantigilbert** [comment]
Bad flash or SD, wrong DTB maybe. 
please follow the how to install, this is not an issue but a user error.
