### ISSUE TITLE
upgrade RetroArch

### ISSUE THREAD

**Issue by 2494654220** [EmuELEC/EmuELEC#1437]
hello,I am using emuelec version 3.3. How can I upgrade RetroArch without upgrading emuelec

**Comment by Langerz82** [comment]
update the hash value, and recompile the build.

https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/libretro/retroarch/package.mk

Also this is not a issue, just a general question please use the discord.

**Comment by 2494654220** [comment]
> update the hash value, and recompile the build.
> 
> https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/libretro/retroarch/package.mk
> 
> Also this is not a issue, just a general question please use the discord.

After the compilation and build process, I receive a directory named "retroarch-1e1b24c35996436e6cf0fe50ec046e2e03a0dbfa". I'm uncertain if this is correct. Should I replace the entire directory on the SD card with this one?

**Comment by Langerz82** [comment]
First you need to be in the 3.9 emuelec tag branch.
you need to build the whole project and you should get the output files in the target directory. Then you copy that onto an sd card.

**Comment by Langerz82** [comment]
Hmm it seems the patches are failing. Try removing the files from the retroarch directory in master_32bit, and copying the retroarch directory from the latest dev version. Make sure your master 32bit version is v3.9.

**Comment by 2494654220** [comment]
> Hmm it seems the patches are failing. Try removing the files from the retroarch directory in master_32bit, and copying the retroarch directory from the latest dev version. Make sure your master 32bit version is v3.9.

I updated the directory with files from the dev branch (Figure 1)
![004](https://github.com/user-attachments/assets/db1a4825-8f2c-4503-89b2-fdf377fa0964)

 after recompiling, some patches were prompted to be skipped, followed by an error message (Figure 2).
![003](https://github.com/user-attachments/assets/fbcc1492-d1c1-4d75-b043-cc23a9eb1317)

**Comment by Langerz82** [comment]
did you also update the hash value to the dev version?

**Comment by 2494654220** [comment]
> did you also update the hash value to the dev version?

Yes, the package.mk file is also from the DEV branch.

**Comment by Langerz82** [comment]
hmm not sure maybe you have to update some of its dependencies as well.

**Comment by 2494654220** [comment]
> hmm not sure maybe you have to update some of its dependencies as well.

Oh, I may not be able to solve it. Thank you very much for your guidance.
