### ISSUE TITLE
T95 Max Plus Won't Boot into EmuElec

### ISSUE THREAD

**Issue by gcdoug** [EmuELEC/EmuELEC#144]
I bought the same TV box that ETA Prime did a video about on YouTube. It is supposed to have the S905X3 chip in it. I followed his video to install onto a microSD card.  renamed the appropriate file from the device_trees folder. However, with everything I have tried, I cannot get the device to boot into EmuElec. Any suggestions? Thanks.

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/129

**Comment by gcdoug** [comment]
I didn't see this post and it seemed to help because I didn't know where the reset button inside the headphone jack but that seemed to help. Thanks

**Comment by NewAgeRipper** [comment]
Solved mine by installing Terminal Emulator in Android and typing "reboot update" without quotes.
