### ISSUE TITLE
Unable to find savestate for emuelec v4.7 running drastic DS emulator on r36s

### ISSUE THREAD

**Issue by DaviDiB1** [EmuELEC/EmuELEC#1444]
I am unable to find my savestate for pokemon under the drastic emulator on r36s running emuelec v4.7. I put the sd card in my mac and the savestate folder is empty, it's not in storage/roms/savestates/[system] or EEROMS/savestates/[system]).

**Comment by Kelvfimer** [comment]
That's not the savestates folder. It is /storage/.config/emulationstation/scripts/drastic/savestates and for the game internal saves /storage/.config/emulationstation/scripts/drastic/backup For these kind of questions use Discord.
