### ISSUE TITLE
How to upgrade lib7z?

### ISSUE THREAD

**Issue by 2494654220** [EmuELEC/EmuELEC#1447]
Excuse me for interrupting, but the new FBN source code requires an upgrade to the lib7z library. Could you please tell me how to perform the upgrade?
![d1a0f7e2-8627-44c0-a2a9-27d893b1e398](https://github.com/user-attachments/assets/d98e313a-8fb8-4935-a5b7-63b7cfe33814)

**Comment by Kelvfimer** [comment]
why do you want to use EMUELEC 3.3??

**Comment by 2494654220** [comment]
> why do you want to use EMUELEC 3.3??

Version 3.3 runs smoothly on my device.
