### ISSUE TITLE
build EmuELEC Missing light file

### ISSUE THREAD

**Issue by johy-525** [EmuELEC/EmuELEC#1449]
[401/578] [DONE] install libxkbcommon:target
<<< light:target seq 429 <<<
GET      light (git)
    DELETE      (/home/work/emuelec/EmuELEC/sources/light/light-*/)
    GIT CLONE      light
Cloning into '/home/work/emuelec/EmuELEC/sources/light/light-33f2316e5512762a5a33a62c78db7a435d9fec9b'...
fatal: could not read Username for 'https://github.com': No such device or address
*********** FAILED COMMAND ***********
. "${get_handler}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/get "${PKG_NAME}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install light:target has failed!

The following log for this failure is available:
  /home/work/emuelec/EmuELEC/build.EmuELEC-OdroidGoAdvance.aarch64-4/.threads/logs/429.log

>>> light:target seq 429 >>>
[402/578] [FAIL] install light:target

The following log for this failure is available:
  /home/work/emuelec/EmuELEC/build.EmuELEC-OdroidGoAdvance.aarch64-4/.threads/logs/429.log

Parallel build failure - see log for details. Time of failure: Thu Nov 28 11:45:40 CST 2024
make: *** [Makefile:10：image] 错误 1

not found light file？

Thanks!

**Comment by shantigilbert** [comment]
use this:

https://github.com/godalming123/light
