### ISSUE TITLE
FAILURE: scripts/install multiemu:target has failed!

### ISSUE THREAD

**Issue by 986046679** [EmuELEC/EmuELEC#1457]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

**Describe the bug**
When I tried to compile, I got a 404 error on the webpage. I checked the link and found that the source of the link had expired.
![1733887342649](https://github.com/user-attachments/assets/3e8d77c1-5232-459c-9d3d-7a1b102b45c4)

**To Reproduce**
Direct compilation

**Expected behavior**

**Screenshots**
![1733887342649](https://github.com/user-attachments/assets/6ecdf3fe-1e9a-478d-a4d8-ae9621c15e69)

**EmuELEC version:**
 - Version 4.7
 - The latest version

**Device (please complete the following information):**
ubuntu20.4

**Additional context**

**Comment by worstcase-scenario** [comment]
Read the rules first before posting:
PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

This is not a problem with Emuelec, please close this issue and use the discord for help.

**Comment by 986046679** [comment]
ok

**Comment by 986046679** [comment]
> try deleting that package file in your sources folder and in your build directory and re-trying.

I've tried, but the same error keeps appearing. I tried accessing the source website directly, but I got a 404 error.

**Comment by Langerz82** [comment]
Try downloading the file directly and do a sha256sum on it and see if you get the same hash. If you do and you are sure it's incorrect then update the package file with the hash you are getting.

**Comment by 986046679** [comment]
> Try downloading the file directly and do a sha256sum on it and see if you get the same hash. If you do and you are sure it's incorrect then update the package file with the hash you are getting.

I tried it and it worked, but I still have a question in version 4.3 if you have a fix for it
![1b3af8ae1d03c413b293b90460cdf4a](https://github.com/user-attachments/assets/9bf9c18b-7e83-4ee3-8d82-48eee942a51d)

**Comment by Langerz82** [comment]
Not sure about that error. Check with package owner for bug and fix for version maybe?
@shantigilbert any idea what he can do?

Just a question, why are you compiling an older version 4.3?

**Comment by 986046679** [comment]
> Not sure about that error. Check with package owner for bug and fix for version maybe? @shantigilbert any idea what he can do?
> 
> Just a question, why are you compiling an older version 4.3?
> 
> checked error online: you might need to update golang package to version 1.17 or higher.
> 
> try copy these files into your 4.3 version, and see if it works. you might need an earlier version. https://github.com/EmuELEC/EmuELEC/tree/dev/packages/addons/addon-depends/go https://github.com/EmuELEC/EmuELEC/commits/dev/packages/addons/addon-depends/go/package.mk

Since I want to run this version on the s905L, I will try the method you mentioned

**Comment by 986046679** [comment]
> Not sure about that error. Check with package owner for bug and fix for version maybe? @shantigilbert any idea what he can do?
> 
> Just a question, why are you compiling an older version 4.3?
> 
> checked error online: you might need to update golang package to version 1.17 or higher.
> 
> try copy these files into your 4.3 version, and see if it works. you might need an earlier version. https://github.com/EmuELEC/EmuELEC/tree/dev/packages/addons/addon-depends/go https://github.com/EmuELEC/EmuELEC/commits/dev/packages/addons/addon-depends/go/package.mk

Unfortunately, when I tried to follow your method, I got another error.
![02eb1627db955481749941cb3e66597](https://github.com/user-attachments/assets/1f9a4e5e-eaa0-4879-bd9c-4bb0569ef399)
