### ISSUE TITLE
Does this support Raspberry Pi

### ISSUE THREAD

**Issue by gaoljhy** [EmuELEC/EmuELEC#146]
I have one Raspberry Pi4 , So i want to use it on Raspberry Pi4.

**Comment by howels** [comment]
Emuelec specialises in supporting the amlogic chipset, which is different to the hardware in the pi and is commonly used in Android-based TV boxes.  Other distributions may support the Pi, but in general the 3D graphics drivers for Pi4 are not as mature as Pi3. You may wish to try Retropie?

**Comment by gaoljhy** [comment]
ok ,i will try it
