### ISSUE TITLE
Where to put ppsspp cheat file?

### ISSUE THREAD

**Issue by silentred** [EmuELEC/EmuELEC#147]
I notice there are 2 dir maybe related to cheats.
- Cheat dir in samba, pointing to /tmp/database/cht
- ~/.config/ppsspp/PSP/Cheats dir

I try to put a cheat.db or .ini file in both directories, but neither of them works. The cheat page in PPSSPP is still empty.

**Comment by SumavisionQ5** [comment]
/tmp/database/cht is for RetroArch core, you may need to load the cheat by your self with Libretro cores.
~/.config/ppsspp/PSP/Cheats is for PPSSPP, if your cheats is not displayed, maybe your cheats are not in correct format.

**Comment by silentred** [comment]
@SumavisionQ5 Thank you for your reply. I am closing this issue.
