### ISSUE TITLE
ROMs in the Arcade folder are not recognized

### ISSUE THREAD

**Issue by fireflychef** [EmuELEC/EmuELEC#148]
I placed some arcade ROMs into the designated Arcade folder, but EmuELEC does not recognize any of the games.  The ROM files are in ZIP format.

Should I unZIP the files, or did I place them in the wrong folder?

**Comment by DKAngel2000** [comment]
they have to be a matching set to which core you are using

**Comment by howels** [comment]
Should be "arcade" instead of "Arcade"

**Comment by fireflychef** [comment]
> they have to be a matching set to which core you are using

Which cores should I be using?  I haven't added any cores since placing EmuElec into my media box?  I have dropped ROMs into other folders and they are all being recognized except the ROMs inside the 'arcade' folder.
