### ISSUE TITLE
T95 Max S905x3

### ISSUE THREAD

**Issue by NewAgeRipper** [EmuELEC/EmuELEC#149]
Flashed a 128 gig SD card with correct image but box isn't booting from SD card. Instead it boots straight into Android. I followed ETA Primes video to the letter. Is there a work around for this?

**Comment by NewAgeRipper** [comment]
Flashed a 128 gig SD card with correct image but box isn't booting from SD card. Instead it boots straight into Android. I followed ETA Primes video to the letter. Is there a work around for this?

**Comment by DKAngel2000** [comment]
download terminal, the type reboot update, that shouldboot of the sdcard if you have it all setup properly

**Comment by howels** [comment]
Please read the wiki (https://github.com/EmuELEC/EmuELEC/wiki/How-to-Install) and look at existing issues https://github.com/EmuELEC/EmuELEC/issues/144 https://github.com/EmuELEC/EmuELEC/issues/141 as these are exactly what you are experiencing.

**Comment by gcdoug** [comment]
There is a hidden reset switch in the AV jack. press and hold while applying power and with the SD card inserted. It should boot into EmuELEC at that point. It worked for me.
