### ISSUE TITLE
Amiga game screens are off-centre 

### ISSUE THREAD

**Issue by MarkTheMorose** [EmuELEC/EmuELEC#150]
I've tried about a dozen Amiga games from WHDLoad files, and all have their screens too far left and down, so I can't see what's at the far left and bottom of their screens.

I don't know how all this retro loveliness works, so I've no idea what the problem is, nor where to look (I'm new to software such as EmuELEC and Retropie).  I did try changing 'game ratio', which appears to be related to the size of the display, but no changes there made any difference.

Thanks in advance.

**Comment by ramsel1508** [comment]
Observed this as well but this is not related to emuelec but rather to amiberry I guess. You can get rid of this problem if you add
 
gfx_center_horizontal=smart
gfx_center_vertical=smart

to your *.uae files

**Comment by shantigilbert** [comment]
I added those lines to the configuration files, so hopefully v3.6 will fix that issue

**Comment by shantigilbert** [comment]
Can you try with v3.6 ?
