### ISSUE TITLE
How to remaping wheel controller for atomiswave or naomi racing game?

### ISSUE THREAD

**Issue by Exia-Ti885** [EmuELEC/EmuELEC#151]
Hello, I have an issue about controller for racing game on atomiswave/naomi games, the game is mostly work very well on amlogic s905x3 soc, but too bad I cant play racing game on it, I try to remap the controller inside Retroarch menu but still not work..anyone can help? also how to I go to PPSSPP Stand alone setting menu? Thank you in advance

**Comment by murphy654** [comment]
Dont know about mapping the wheel buttons but the psp settings is accessed by pressing escape on a keyboard you can then map a button for the settings menu

**Comment by Exia-Ti885** [comment]
> Dont know about mapping the wheel buttons but the psp settings is accessed by pressing escape on a keyboard you can then map a button for the settings menu

Thank you!

**Comment by BaltasarParreira** [comment]
I solved this on Faster Than Speed rom going to system menu using the service button and change the country to Europe, also I change the game options from mph to kph and them save, after that I mange to go and run the game always normal without stopping at the beginning on the screen asking for controller settings.
To play I didn't remap anything just use my PS3 left analog stick down to accelerate and left/right to turn. For navigating on the menus the normal select and start buttons , etc.

**Comment by snakect77** [comment]
I can't, you can be more precise please

**Comment by snakect77** [comment]
> Ho risolto questo problema con la rom Più veloce della velocità e della velocità massima andando al menu di sistema usando il pulsante di servizio e cambiando il paese in Europa, inoltre cambio le opzioni di gioco da mph a km / h e li salvo, dopodiché mi occupo di andare a correre il gioco sempre normale senza fermarsi all'inizio sullo schermo chiedendo le impostazioni del controller.
> Per giocare non ho rimappato nulla, basta usare la mia levetta analogica sinistra PS3 verso il basso per accelerare e sinistra / destra per girare. Per navigare nei menu i normali pulsanti di selezione e avvio, ecc.



> I solved this on Faster Than Speed and Maximum Speed rom going to system menu using the service button and change the country to Europe, also I change the game options from mph to kph and them save, after that I mange to go and run the game always normal without stopping at the beginning on the screen asking for controller settings.
> To play I didn't remap anything just use my PS3 left analog stick down to accelerate and left/right to turn. For navigating on the menus the normal select and start buttons , etc.
I can't, you can be more precise please

**Comment by snakect77** [comment]
It can indicate all the settings
