### ISSUE TITLE
Update 3.4 Version 

### ISSUE THREAD

**Issue by samuelstatus** [EmuELEC/EmuELEC#152]
Hello, 
Actually I have a good game image but it's 3.0 version, so I want to update to 3.4
I read about update in the first page, but not understand where I put the file .tar
I have a s912 box
Please be patient 😇

**Comment by ValeFormi** [comment]
Same here from 3.4 to 3.5 the Emuelec partition doesn't have enough space, and 
copying on Update from scp does not work after restart.
