### ISSUE TITLE
s912 psp wont boot

### ISSUE THREAD

**Issue by nikos17m** [EmuELEC/EmuELEC#153]
hello 
i am new to this
i managed to boot successfully emuelec v3.5 into a s912 box tx9s to be exact
wifi works etc so the device tree is correct.

i am trying to boot psp games with no luck
i updated everything within the retroatch but still i am getting a black screen.

my box is the problem or I am doing something wrong?

Thank you
Regards
Nick

**Comment by shantigilbert** [comment]
Read the wiki, PPSSPP does not run on s912
