### ISSUE TITLE
T95 Max+: Scrapped images at first, not anymore

### ISSUE THREAD

**Issue by Caninusouza** [EmuELEC/EmuELEC#155]
Hi, at first I was able to get it to scrape. Now, even after starting it all over from scratch it just search for the images, but does not download them, not even for the systems it did before.  Can you please help? Not sure what I'm doing wrong. Thank you

**Comment by shantigilbert** [comment]
Register on the ss website

**Comment by Caninusouza** [comment]
SS website? What SS stands for? Thank you

**Comment by chenteparao** [comment]
> Hi, at first I was able to get it to scrape. Now, even after starting it all over from scratch it just search for the images, but does not download them, not even for the systems it did before. Can you please help? Not sure what I'm doing wrong. Thank you

i can you give me the dtb for this divece please? o which one is? Thanks
