### ISSUE TITLE
Change Screen Resolution Via File (Problem)

### ISSUE THREAD

**Issue by PinkoMoore** [EmuELEC/EmuELEC#164]
I want to set my box to 720p to get it working on my monitor. I've followed the EE_VIDEO_MODE instructions but now all it does is boot to the 'EmuElec' start screen, afterwards the screen turns black.

Background info: 
I've been using my emuelec box on a 1080p screen for a while before this.

**Comment by shantigilbert** [comment]
What steps are you following to do this?

**Comment by PinkoMoore** [comment]
I put a file named EE_VIDEO_MODE on the root of EmuElec partition with "720p60hz" in it.

**Comment by shantigilbert** [comment]
try doing this on a terminal with SSH

`echo $(cat /flash/EE_VIDEO_MODE) > /sys/class/display/mode`

**Comment by shantigilbert** [comment]
Closing as no response, open up if necessary
