### ISSUE TITLE
Multilanguage addon version

### ISSUE THREAD

**Issue by Sheredeka** [EmuELEC/EmuELEC#165]
Please, make it possible to switch the interface language in addon version

**Comment by dimetrius-zx** [comment]
Yes! I also want this opportunity!

**Comment by rasto4nik** [comment]
Yas! I want russian language!

**Comment by shantigilbert** [comment]
Not possible, ES does not support it.

**Comment by Asrock2008** [comment]
Yes! I also want this opportunity!
I want russian language, thanks you for your work

**Comment by Anzic23** [comment]
Yes! I also want this opportunity!

**Comment by vansai** [comment]
Yes! I also want this opportunity!
