### ISSUE TITLE
How to force 720p

### ISSUE THREAD

**Issue by ArturNadolski** [EmuELEC/EmuELEC#168]
I've NEC 1980 FXi 19" 5:4 LCD monitor. I would like to set it to 720p mode as native for EmuELEC.
This monitor doesn't support 1080p so after fresh EmuELEC start I'm getting image like at attached pictures.
![IMG_20200504_175347](https://user-images.githubusercontent.com/20038314/80986541-fd737c80-8e30-11ea-84d4-49a328b01950.jpg)
![IMG_20200504_175412](https://user-images.githubusercontent.com/20038314/80986560-02383080-8e31-11ea-9d03-eba784345231.jpg)

**Comment by ArturNadolski** [comment]
How to add splash and intro for 720p? Where to put files and how to name it to system recognize and use it instead of original ones in 1080p?

**Comment by shantigilbert** [comment]
Read the wiki on how to change the resolution. 

There is no support for changing intro video or splash.
