### ISSUE TITLE
Plymouth-lite also available as CE boot splash?

### ISSUE THREAD

**Issue by siliconhippy** [EmuELEC/EmuELEC#170]
Hi Shanti !

Great job! Hope I am following instructions to make myself 😬 clear.

1. Is the emuELEC add-on available in CoreElec repo for v 9.2.1 (Nov '19, Kodi 18.5) or later?

2. I noticed plymouth-lite files.
Can I use these to substitute my own boot splash .png image to replace the default CoreElec boot splash?

(Didn't see Plymouth for Entware $opkg in CoreElec.)

If yes, can you kindly point some command line instructions, i.e., filepath change needed, etc?

**Comment by shantigilbert** [comment]
Addon is manual install, and no, it will not help you change the splash, and I will not help you change it either, ask in CoreELEC forum.
