### ISSUE TITLE
Disappearing roms

### ISSUE THREAD

**Issue by bbmllr4** [EmuELEC/EmuELEC#176]
Hello I think that's a bug. I have the SD card via USB in my Windows 10 PC and have spent hours buting Roms on the SD card. As the card is still in the PC, the Roms are still there as soon as I do  take out and in the Android TV-Box t95 max there are no Roms anymore ?? Ob the SD Card Samsung UE 32Gb. Just the normal 200 mb of and the Rom are simply gone ?  IT did't a Thing in the SD card. I Just USB direct in the Box wird emuelec File transfer and reboot nothing ??? I don't understand why the Roms do not  are written on the SD card.

**Comment by shantigilbert** [comment]
This has nothing to do with emuelec, its on your PC.
