### ISSUE TITLE
Change DOSBox to DOSBox-x

### ISSUE THREAD

**Issue by andrewg78** [EmuELEC/EmuELEC#177]
**Is your feature request related to a problem? Please describe.**
Yes. In the original DosBox there is no feature to save and load a game state 

**Describe the solution you'd like**
Instead of the original dosbox version, compile a fork called dosbox-x 
https://github.com/joncampbell123/dosbox-x

**Comment by shantigilbert** [comment]
I tried Dosbos-x, unfortunately I had problems with how the games are displayed (window way to small) until I figure it out, I have no choice but to keep using dosbox :(

**Comment by andrewg78** [comment]
I would like to play a bit with this project.  How do u execute a cross compilation for Amlogic generic ?
Could you provide some commands here?

**Comment by shantigilbert** [comment]
Everything you need to compile is on the readme including dependencies and commands.

**Comment by shantigilbert** [comment]
Dosbox-x has been added
