### ISSUE TITLE
emuelec 3.5 bug report

### ISSUE THREAD

**Issue by soominpapa** [EmuELEC/EmuELEC#181]
**EmuELEC version:**
 - Version 3.5

**Device (please complete the following information):**
 - SOC: s922x
 - Brand: odroid
 - Model: odroid N2
 - Version

** AI Game Translation bug
- Target language : not working in game
- Pause on Translated Screen : not working in game
- If I setup in retroarch, Those are worked. But, That's not automatic setup function.

** RA BEZELS switch bug
- Enable RA Bezels : If I set enabled it, but it was on disabled position.

** I did a clean install of emuelec 3.5.
However, I tried reset in danger zone to fix the above error, but it didn't work.

**Comment by shantigilbert** [comment]
> * Target language : not working in game
> 
> * Pause on Translated Screen : not working in game
> 
> * If I setup in retroarch, Those are worked. But, That's not automatic setup function.

How did you set it up on Retroarch? can you send me a retroarch.cfg that works for you?
