### ISSUE TITLE
Emuelec en RK3328

### ISSUE THREAD

**Issue by george291214** [EmuELEC/EmuELEC#183]
Hay manera de tener emuelec en un tv box rk3328? Ya intente con kodi pero no puedo instalar el addon al parece hay una mamera con librelec alguien me podria ayudar

**Comment by SumavisionQ5** [comment]
RK3328 won't be supported by shantigilbert. Please ask somebody else to do it. Supporting Amlogic devices takes all shanti's time and he has no interest on other RK machines expcept OGA.

**Comment by shantigilbert** [comment]
No hay manera
