### ISSUE TITLE
Hello everyone, how to install the core?

### ISSUE THREAD

**Issue by kyo750904** [EmuELEC/EmuELEC#184]
Hello everyone

In the original version 3.5, the core of PSX was only PCSX_REARMED_LIBRETRO
I think using mednafen_psx_libretro can make the picture quality better
But even if I type Cores myself and paste mednafen_psx_libretro.so
The core does not appear in the core options,
So I think copy and paste is not that simple, I want to ask you how to call or install the kernel

Thank you

**Comment by shantigilbert** [comment]
Not compatible
