### ISSUE TITLE
FAILURE: scripts/install u-boot has failed!

### ISSUE THREAD

**Issue by fabiohpa** [EmuELEC/EmuELEC#192]
Hi guys, when trying to build the project in my vm I got the error below.

![image](https://user-images.githubusercontent.com/22963092/84085600-51d3c400-a9bc-11ea-9514-ae2b8118722f.png)

I redid the steps described in the readme and the bug persists.

I agree that I did not understand the reason for the error and then correct it. Could someone help me? I am a beginner and would like to learn how to compile the project and then start to cooperate with ideas.

Tks

Edit:
Ubuntu 18
HD 200 GB
EmuELEC 3.5

**Comment by shantigilbert** [comment]
You need to provide the log for that failure, or scroll back a few lines until you see the real error, from that image is impossible to know

**Comment by british-choi** [comment]
@fabiohpa 
you can get failed log
$ cat ./build.EmuELEC-Amlogic.arm-3.5/.threads/logs/107/stdout

**Comment by fabiohpa** [comment]
Try to run or command to export or not work. I chose to copy and paste. Sorry for the number of lines.

Everything was going well, I didn't understand what could have happened.

Thank you for your help.

`fabio@fabio-VirtualBox:~/EmuELEC$ PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC make image
./scripts/image mkimage

 =================================================================================
 Configuration for EmuELEC (community)
 =================================================================================

 Buildoptions:
 ======================================================
 - CPU (ARCH):				 cortex-a53 (arm)
 - FLOAT:				 hard
 - FPU:					 neon-fp-armv8
 - CPU features:			 32bit neon
 - LTO (Link Time Optimization) support: yes
 - GOLD (Google Linker) Support:	 yes
 - LLVM support:			 no
 - DEBUG:				 no

 Graphic configuration:
 ======================================================
 - OpenGL (GLX) support (provider):	 no (no)
 - OpenGLES support (provider):		 yes (opengl-meson-t82x)
 - uvesafb support:			 no

 Hardware decoder configuration:
 ======================================================
 - Kodi Player driver:			 libamcodec
 - VAAPI Support:			 no
 - VDPAU Support:			 no

 Input device configuration:
 ======================================================
 - Remote support:			 no
 - CEC Adapter support:			 no
 - CEC Framework support:		 no
 - Kodi Joystick support:		 yes

 Misc. hardware configuration:
 ======================================================
 - ALSA support:			 yes
 - Pulseaudio support:			 yes
 - Bluetooth support:			 yes
 - Include driver:			 gpu-aml
 - Include driver:			 kvimfan-aml
 - Include driver:			 openvfd-driver
 - Include driver:			 wifi_dummy-aml
 - Include driver:			 ap6xxx-aml
 - Include driver:			 mt7601u-aml
 - Include driver:			 mt7603u-aml
 - Include driver:			 mt7610u-aml
 - Include driver:			 qca9377-aml
 - Include driver:			 ssv6xxx-aml
 - Include driver:			 RTL8188EU-aml
 - Include driver:			 RTL8189ES-aml
 - Include driver:			 RTL8189FS-aml
 - Include driver:			 RTL8192CU
 - Include driver:			 RTL8192DU
 - Include driver:			 RTL8192EU
 - Include driver:			 RTL8723BS-aml
 - Include driver:			 RTL8723DS-aml
 - Include driver:			 RTL8812AU
 - Include driver:			 RTL8814AU
 - Include driver:			 RTL8821CU
 - Include driver:			 RTL8822BU-aml
 - Include driver:			 RTL8822BS-aml
 - Include firmware:			 misc-firmware
 - Include firmware:			 wlan-firmware
 - Include firmware:			 dvb-firmware
 - Include firmware:			 brcmfmac_sdio-firmware-aml
 - Include firmware:			 qca9377-firmware-aml
 - Include firmware:			 rtkbt-firmware-aml
 - Initramfs modules:			 font
 - Initramfs modules:			 softcursor
 - Initramfs modules:			 bitblit
 - Initramfs modules:			 fbcon
 - Initramfs modules:			 dwc_otg

 Network service configuration:
 ======================================================
 - Avahi (Zeroconf) support:		 yes
 - NFS mounting support:		 yes
 - SAMBA mounting support:		 yes
 - SAMBA server support:		 yes
 - SFTP server support:			 yes
 - OpenVPN support:			 yes
 - WireGuard support:			 

 OS configuration:
 ======================================================
 - OEM Support:				 yes
 - Default ROOT Password:		 emuelec
 - Bootloader:				 u-boot
 - UDevil support:			 yes
 - Installer support:			 no
 - Include package:			 u-boot-script
 - Include package:			 dtc
 - Include package:			 u-boot-tools-aml
 - Include package:			 CoreELEC-Debug-Scripts

 Misc. Filesystems:
 ======================================================
 - Swap Support:			 yes
   - Swapfile default size:		 128
 - exFAT Support (via Fuse):		 yes
 - NTFS Support (via Fuse):		 yes
 - Install HFS Tools:			 yes

 =================================================================================
 End Configuration for EmuELEC
 =================================================================================



Packages loaded : 1116
Build trigger(s): 1 [image]
Package steps   : 416

[001/416] [DONE] build   configtools:host
[002/416] [DONE] build   make:host
[003/416] [DONE] build   ccache:host
[004/416] [DONE] build   xz:host
[005/416] [DONE] build   sed:host
[006/416] [DONE] build   gettext:host
[007/416] [DONE] build   pkg-config:host
[008/416] [DONE] build   m4:host
[009/416] [DONE] build   autoconf:host
[010/416] [DONE] build   automake:host
[011/416] [DONE] build   intltool:host
[012/416] [DONE] build   libtool:host
[013/416] [DONE] build   autoconf-archive:host
[014/416] [DONE] build   bison:host
[015/416] [DONE] build   autotools:host
[016/416] [DONE] build   flex:host
[017/416] [DONE] build   openssl:host
[018/416] [DONE] build   gcc-arm-aarch64-linux-gnu:host
[019/416] [DONE] build   linux:host
[020/416] [DONE] build   binutils:host
[021/416] [DONE] build   gmp:host
[022/416] [DONE] build   mpfr:host
[023/416] [DONE] build   mpc:host
INSTALL      gcc (bootstrap)
[024/416] [DONE] install gcc:bootstrap
[025/416] [DONE] build   cmake:host
[026/416] [DONE] build   zlib:host
[027/416] [DONE] build   pigz:host
INSTALL      ccache (host)
INSTALL      autotools (host)
INSTALL      linux (host)
INSTALL      pigz (host)
INSTALL      glibc (target)
[028/416] [DONE] install glibc
[029/416] [DONE] build   gcc:host
[030/416] [DONE] build   libxml2:host
[031/416] [DONE] build   libxslt:host
[032/416] [DONE] build   xmlstarlet:host
[033/416] [DONE] build   p7zip:host
[034/416] [DONE] build   bzip2:host
[035/416] [DONE] build   sqlite:host
[036/416] [DONE] build   Python2:host
[037/416] [DONE] build   ninja:host
[038/416] [DONE] build   libffi:host
[039/416] [DONE] build   util-linux:host
[040/416] [DONE] build   Python3:host
[041/416] [DONE] build   setuptools:host
[042/416] [DONE] build   pathlib:host
[043/416] [DONE] build   meson:host
INSTALL      configtools (host)
INSTALL      make (host)
INSTALL      xz (host)
INSTALL      sed (host)
INSTALL      pkg-config (host)
INSTALL      autoconf (host)
INSTALL      automake (host)
INSTALL      intltool (host)
INSTALL      libtool (host)
INSTALL      autoconf-archive (host)
INSTALL      gcc (host)
INSTALL      bison (host)
INSTALL      flex (host)
INSTALL      cmake (host)
INSTALL      xmlstarlet (host)
INSTALL      p7zip (host)
INSTALL      ninja (host)
INSTALL      meson (host)
INSTALL      toolchain (target)
[044/416] [DONE] install toolchain
[045/416] [DONE] build   lzo:host
[046/416] [DONE] build   zstd:host
[047/416] [DONE] build   squashfs:host
[048/416] [DONE] build   dosfstools:host
[049/416] [DONE] build   libcap:host
[050/416] [DONE] build   fakeroot:host
[051/416] [DONE] build   kmod:host
[052/416] [DONE] build   mtools:host
[053/416] [DONE] build   e2fsprogs:host
[054/416] [DONE] build   populatefs:host
INSTALL      tz (target)
[055/416] [DONE] install tz
INSTALL      libidn2 (target)
[056/416] [DONE] install libidn2
INSTALL      arm-mem (target)
[057/416] [DONE] install arm-mem
INSTALL      libc (target)
[058/416] [DONE] install libc
INSTALL      gcc (target)
[059/416] [DONE] install gcc
[060/416] [DONE] build   cpio:host
INSTALL      wireless-regdb (target)
[061/416] [DONE] install wireless-regdb
INSTALL      keyutils (target)
[062/416] [DONE] install keyutils
INSTALL      device-trees-amlogic (target)
[063/416] [DONE] install device-trees-amlogic
[064/416] [DONE] build   aml-dtbtools:host
[065/416] [DONE] build   mkbootimg:host
INSTALL      cpio (host)
INSTALL      kmod (host)
INSTALL      aml-dtbtools (host)
INSTALL      gcc-arm-aarch64-linux-gnu (host)
INSTALL      mkbootimg (host)
INSTALL      linux (target)
[066/416] [DONE] install linux
INSTALL      gpu-aml (target)
[067/416] [DONE] install gpu-aml
INSTALL      kvimfan-aml (target)
[068/416] [DONE] install kvimfan-aml
INSTALL      openvfd-driver (target)
[069/416] [DONE] install openvfd-driver
INSTALL      wifi_dummy-aml (target)
[070/416] [DONE] install wifi_dummy-aml
INSTALL      ap6xxx-aml (target)
[071/416] [DONE] install ap6xxx-aml
INSTALL      mt7601u-aml (target)
[072/416] [DONE] install mt7601u-aml
INSTALL      mt7603u-aml (target)
[073/416] [DONE] install mt7603u-aml
INSTALL      mt7610u-aml (target)
[074/416] [DONE] install mt7610u-aml
INSTALL      qca9377-aml (target)
[075/416] [DONE] install qca9377-aml
INSTALL      ssv6xxx-aml (target)
[076/416] [DONE] install ssv6xxx-aml
INSTALL      RTL8188EU-aml (target)
[077/416] [DONE] install RTL8188EU-aml
INSTALL      RTL8189ES-aml (target)
[078/416] [DONE] install RTL8189ES-aml
INSTALL      RTL8189FS-aml (target)
[079/416] [DONE] install RTL8189FS-aml
INSTALL      RTL8192CU (target)
[080/416] [DONE] install RTL8192CU
INSTALL      RTL8192DU (target)
[081/416] [DONE] install RTL8192DU
INSTALL      RTL8192EU (target)
[082/416] [DONE] install RTL8192EU
INSTALL      RTL8723BS-aml (target)
[083/416] [DONE] install RTL8723BS-aml
INSTALL      RTL8723DS-aml (target)
[084/416] [DONE] install RTL8723DS-aml
INSTALL      RTL8812AU (target)
[085/416] [DONE] install RTL8812AU
INSTALL      RTL8814AU (target)
[086/416] [DONE] install RTL8814AU
INSTALL      RTL8821CU (target)
[087/416] [DONE] install RTL8821CU
INSTALL      RTL8822BU-aml (target)
[088/416] [DONE] install RTL8822BU-aml
INSTALL      RTL8822BS-aml (target)
[089/416] [DONE] install RTL8822BS-aml
INSTALL      driverselect (target)
[090/416] [DONE] install driverselect
INSTALL      linux-drivers (target)
[091/416] [DONE] install linux-drivers
INSTALL      kernel-firmware (target)
[092/416] [DONE] install kernel-firmware
INSTALL      misc-firmware (target)
[093/416] [DONE] install misc-firmware
INSTALL      rfkill (target)
[094/416] [DONE] install rfkill
INSTALL      wlan-firmware (target)
[095/416] [DONE] install wlan-firmware
INSTALL      dvb-firmware (target)
[096/416] [DONE] install dvb-firmware
INSTALL      brcmfmac_sdio-firmware-aml (target)
[097/416] [DONE] install brcmfmac_sdio-firmware-aml
INSTALL      qca9377-firmware-aml (target)
[098/416] [DONE] install qca9377-firmware-aml
INSTALL      rtk_hciattach (target)
[099/416] [DONE] install rtk_hciattach
INSTALL      rtkbt-firmware-aml (target)
[100/416] [DONE] install rtkbt-firmware-aml
INSTALL      linux-firmware (target)
[101/416] [DONE] install linux-firmware
[102/416] [DONE] build   gcc-linaro-aarch64-elf:host
[103/416] [DONE] build   gcc-linaro-arm-eabi:host
INSTALL      gcc-linaro-aarch64-elf (host)
INSTALL      gcc-linaro-arm-eabi (host)
INSTALL      u-boot-LePotato (target)
[104/416] [DONE] install u-boot-LePotato
INSTALL      u-boot_firmware (target)
[105/416] [DONE] install u-boot_firmware
INSTALL      u-boot-Odroid_C2 (target)
[106/416] [DONE] install u-boot-Odroid_C2
BUILD      u-boot (target)
    TOOLCHAIN      manual
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/update.sh' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/update.sh'
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/canupdate.sh' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/canupdate.sh'
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/LePotato_boot.ini' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/LePotato_boot.ini'
'/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-LePotato-b497a82d864d07e4d4e8ffe7f05870536b2b38d0/fip/u-boot.bin.sd.bin' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/LePotato_u-boot'
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/Odroid_C2_boot.ini' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/Odroid_C2_boot.ini'
'/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-Odroid_C2-ad3e8b1cfb74d22777cb002f01ac992abe457aad/u-boot.bin' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/Odroid_C2_u-boot'
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/config.ini' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/config.ini'
[107/416] [FAIL] install u-boot
FAILURE: scripts/install u-boot has failed!
parallel: This job failed:
package_worker 1 107 416 'install u-boot'
Parallel build failure - see log for details. Time of failure: Mon Jun  8 22:46:34 -03 2020
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 1
`

**Comment by british-choi** [comment]
1. $ cat ./build.EmuELEC-Amlogic.arm-3.5/.threads/logs/107/stdout
2. $ df -h

**Comment by fabiohpa** [comment]
@british-choi , I try to execute the command but it returns the message that the path does not exist. 

I enabled the viewing of hidden files and accessed the threads folder. There are several files, I noticed that there is a file called "u-boot: target.build.failed" and inside it is written "187". 

It helps?

![image](https://user-images.githubusercontent.com/22963092/84099212-78efbd00-a9df-11ea-8663-b1717780f8fb.png)

Tks

**Comment by shantigilbert** [comment]
This is a very weird issue as there is really no error message, it seems everything has been copied as it should, are you sure yoiu have enough space? 

run `df -h` 

also make sure your directories are NOT symlinks.

**Comment by british-choi** [comment]
your capture image is "107" not "187"
$ cat ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/107/stdout
$ df -h

**Comment by fabiohpa** [comment]
@british-choi, sorry, i just typed wrong. Had copied and pasted the commands you gave me.
$ cat ./build.EmuELEC-Amlogic.arm-3.5/.threads/logs/107/stdout

@british-choi I ran the command cat ~ / EmuELEC / build.EmuELEC-Amlogic.arm-3.5 / .threads / logs / 107 / stdout and got the same return.
![image](https://user-images.githubusercontent.com/22963092/84101710-ece09400-a9e4-11ea-9452-c8a1fc00b521.png)

@shantigilbert, I ran the command and got the following return...
![image](https://user-images.githubusercontent.com/22963092/84101768-21ece680-a9e5-11ea-908a-5b17f6e4c372.png)

**Comment by shantigilbert** [comment]
can you try this 

`PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC ./scripts/build u-boot`

**Comment by fabiohpa** [comment]
@shantigilbert I ran the command

![image](https://user-images.githubusercontent.com/22963092/84103544-bd805600-a9e9-11ea-8aae-51fd3deebe08.png)

**Comment by shantigilbert** [comment]
ok, now try the regular  command
 `PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC make image`

**Comment by fabiohpa** [comment]
@shantigilbert  same mistake

![image](https://user-images.githubusercontent.com/22963092/84103753-5dd67a80-a9ea-11ea-86f7-2b603c109cc3.png)

**Comment by shantigilbert** [comment]
hmm this is extremely weird... 

Try this now 
`PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC ./scripts/install u-boot`

**Comment by fabiohpa** [comment]
@shantigilbert,  it's insane .. hahaha

I ran the command

![image](https://user-images.githubusercontent.com/22963092/84104153-506dc000-a9eb-11ea-9733-e580deb385f8.png)

**Comment by fabiohpa** [comment]
@shantigilbert 

tried again regular command
PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC make image

![image](https://user-images.githubusercontent.com/22963092/84104386-ec97c700-a9eb-11ea-8749-9e2522b3ef04.png)

**Comment by british-choi** [comment]
what directory (or file) is missing?
1. ~/EmuELEC
2. ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5
3. ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads
4. ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs
5. ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/107
6. ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/107/stdout  <= this is not directory, It's log file

**Comment by shantigilbert** [comment]
@fabiohpa You need to provide the file that @british-choi is asking for, as the error is on package 107, whichever that might be, it is not u-boot

also you can provide `~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/107/stderr`

**Comment by fabiohpa** [comment]
@shantigilbert  @british-choi  there is no "logs" folder on that path you said.

![image](https://user-images.githubusercontent.com/22963092/84105584-228a7a80-a9ef-11ea-89fd-54a547ffbe7a.png)

**Comment by british-choi** [comment]
sorry, i don't know this issue.
I'm not use virtual box system
The only difference from me is that you are using a virtual box.

**Comment by shantigilbert** [comment]
I am not sure what the issue is either, I also do not use VM. but try this 

`find . -type d -name "107"` 

maybe the logs are set to be saved elsewhere with the VM.

**Comment by fabiohpa** [comment]
Hi guys, i'm back. hahaha

I installed Ubuntu 18.04 on a new computer. I'm not using vm anymore. I tried to compile the project again and got the same error but I was able to access the logs. Accessing the stderr file from the logs folder 107. I got the content to follow.

[108/416] [FAIL] install u-boot
The following logs for this failure are available:
  stdout: /home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/107/stdout
  stderr: /home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/107/stderr

Running the command:
"$ cat ./build.EmuELEC-Amlogic.arm-3.5/.threads/logs/108/stdout" . I got the content to follow.

(...) 
libbb/xfuncs_printf.c: In function 'generate_uuid':
libbb/xfuncs_printf.c:649:3: warning: ignoring return value of 'read', declared with attribute warn_unused_result [-Wunused-result]
   read(i, buf, 16);
   ^~~~~~~~~~~~~~~~
make[2]: *** wait: No child processes.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [Makefile:743: libbb] Error 2

**Comment by shantigilbert** [comment]
can you post the complete error log, not just the end. maybe use a site like pastebin

**Comment by fabiohpa** [comment]
hi @shantigilbert, I couldn't embed the pastebin link. I will make the link available:

https://pastebin.com/VUy0dBVs

**Comment by shantigilbert** [comment]
> hi @shantigilbert, I couldn't embed the pastebin link. I will make the link available:
> 
> https://pastebin.com/VUy0dBVs

I really don't know what is going on, these are my suggestions

try this first

```
PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC ./scripts/build busybox
PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC ./scripts/install busybox
PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC make image
```
you might get a clearer error, although I doubt it 

if that does not work, try this:
```
git checkout dev
PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC ./scripts/build busybox
PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC make image
```

**Comment by fabiohpa** [comment]
cool, I'll try again and post the result.

tks @shantigilbert

**Comment by fabiohpa** [comment]
cool, I'll try again and post the result.

tks @shantigilbert

**Comment by fabiohpa** [comment]
@shantigilbert.. i perform the previous steps and I was unsuccessful. What a shame!
I ran the commands to validate the logs and the return is below.

What version of linux do you use?

fabio@fabio-HP-G42-Notebook-PC:~/EmuELEC$ cat ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/108/stderr
[137/419] [FAIL] install u-boot

The following logs for this failure are available:
  stdout: /home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/108/stdout
  stderr: /home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/108/stderr

fabio@fabio-HP-G42-Notebook-PC:~/EmuELEC$ cat ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/108/stdout
BUILD      u-boot (target)
    TOOLCHAIN      manual
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/update.sh' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/update.sh'
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/canupdate.sh' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/canupdate.sh'
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/LePotato_boot.ini' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/LePotato_boot.ini'
'/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-LePotato-923e6512c88d595df9514a719833c72933d6d2bd/fip/u-boot.bin.sd.bin' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/LePotato_u-boot'
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/Odroid_C2_boot.ini' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/Odroid_C2_boot.ini'
'/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-Odroid_C2-a2eb29f823e8cfc6fee325f69116334c6f1ba6c0/u-boot.bin' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/Odroid_C2_u-boot'
'/home/fabio/EmuELEC/projects/Amlogic/bootloader/config.ini' -> '/home/fabio/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/u-boot-1.0/.install_pkg/usr/share/bootloader/config.ini'
FAILURE: scripts/install u-boot has failed!

fabio@fabio-HP-G42-Notebook-PC:~/EmuELEC$ cat ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/137/stdout
INSTALL      busybox (host)
INSTALL      busybox (target)

fabio@fabio-HP-G42-Notebook-PC:~/EmuELEC$ cat ~/EmuELEC/build.EmuELEC-Amlogic.arm-3.5/.threads/logs/137/stderr
[134/419] [DONE] install busybox

tks

**Comment by shantigilbert** [comment]
Ubuntu Ubuntu 18.04.4 LTS 64bits

I really do now know what the error is, sorry.

**Comment by fabiohpa** [comment]
@shantigilbert 

Thank you for the support. 👍
