### ISSUE TITLE
PSP input not working at all

### ISSUE THREAD

**Issue by sobavsworld** [EmuELEC/EmuELEC#195]
Just installed Emuelec following ETA Prime's steps, but the PSP input is not working at all, I can't even exit the emulator without turning off my tv box completely. My controller is working on every other emulator. Did/does anyone have this problem? 

I'm running EmuELEC version 3.4
 - S905x3 
 - T95Max android tv box, 4GB model

**Comment by shantigilbert** [comment]
Please use Github for actual bugs, this is a particular issue. Use discord for that.
