### ISSUE TITLE
[OGA] Missing speaker icon in song title notification

### ISSUE THREAD

**Issue by atylmo** [EmuELEC/EmuELEC#198]
When a song starts on the EmulationStation menu, the title ithat pops up in the notification is supposed to have a speaker icon to the left of it. It works in Batocera but in EmuELEC it's turned into a white rectangle.

Thank you for the hard work on this project! :)

**Comment by shantigilbert** [comment]
Thanks, this has been fixed but not yet public.

**Comment by atylmo** [comment]
Ah, okay. Thanks for fixing it!

**Comment by shantigilbert** [comment]
fixed on 845165d
