### ISSUE TITLE
[OGA]The RetroArch 's setting menu  don't have "Driver" option.

### ISSUE THREAD

**Issue by CynricXu** [EmuELEC/EmuELEC#200]
[OGA]The retroarch 's setting menu doesn't have "Driver" option in version 3.6，So I can't change the retroarch theme.

**Comment by shantigilbert** [comment]
Main Menu > System Settings > Developer > Use RGUI

That is the only option to change driver.

**Comment by shantigilbert** [comment]
You can also change /emuelec/configs/emuelec.conf

```
## Retroarch menu driver, ozone (default), rgui or xmb 
#global.retroarch.menu_driver=
```

**Comment by CynricXu** [comment]
Ok! Thank you！
