### ISSUE TITLE
Pixels look "weird" in all games

### ISSUE THREAD

**Issue by Prosnorkulus1** [EmuELEC/EmuELEC#203]
In all games im having this problem where the pixels are half size and only some are full size, heres an imgur link to show what im talking about, it is the most noticeable in the ground blocks, the "I" in mario, and the four dots on the corners of question blocks. https://imgur.com/a/HlKhQDW. Ive been messing around with the retroarch settings and nothing is fixing it

**Comment by shantigilbert** [comment]
Switch to RGA scaling, or 4:3

This is not a bug, you need to change settings to reach a point to your liking, and BTW the first image is not how Mario should look. (It was not a widescreen game by any means)
