### ISSUE TITLE
Enable prefilled names for DevilutionX

### ISSUE THREAD

**Issue by AJenbo** [EmuELEC/EmuELEC#207]
You might want to enable prefilled names so users do not have to type one 

`-DPREFILL_PLAYER_NAME=ON`

https://github.com/EmuELEC/EmuELEC/blob/master/packages/sx05re/emulators/devilutionX/package.mk#L17

**Comment by shantigilbert** [comment]
Thank you! That is a very good idea I will implement it on next release!

**Comment by AJenbo** [comment]
Just discovered this by coincidence since someone requested that this feature upstream, but we already had :) Feel free to message us if there are any specific issues with it running on relevant platforms.

**Comment by NeonLightning** [comment]
those flags should be documented somewhere probably lol

**Comment by AJenbo** [comment]
Feel free to make a PR for the readme :)
