### ISSUE TITLE
videopac rom dir

### ISSUE THREAD

**Issue by bsturk** [EmuELEC/EmuELEC#208]
The directory created by emuelec-addon.sh for the videopac (odyssey 2) rom directory does not match what is in es_system.cfg

videopac \

<path>/storage/roms/videopac2</path>

**Comment by shantigilbert** [comment]
Thank you, which one should be used? videopac or videopac2?

**Comment by bsturk** [comment]
You're welcome.  If it were me I would either call it just videopac or odyssey_2.  Being from the US, it was called the Odyssey 2 here.

**Comment by shantigilbert** [comment]
fixed on 845165d
