### ISSUE TITLE
X96 mini p281 and p282

### ISSUE THREAD

**Issue by chenteparao** [EmuELEC/EmuELEC#210]
Hi, I bought a x96mini some days ago and performance is amazing with emuelec, today bought the "same" device for my brother but not boot. I install AIDA64 in both devices and old X96mini has a difference, 

it say p281 in board, while new device say p282 in board. Do you know how to run in this new device? Thanks.

![WhatsApp Image 2020-06-27 at 15 24 17](https://user-images.githubusercontent.com/59416373/85931483-53412f80-b88a-11ea-827e-0bf658687df7.jpeg)
![WhatsApp Image 2020-06-27 at 15 24 17 (1)](https://user-images.githubusercontent.com/59416373/85931485-53d9c600-b88a-11ea-9d60-d2155086c5fc.jpeg)

**Comment by chenteparao** [comment]
![IMG_20200630_123549](https://user-images.githubusercontent.com/59416373/86161027-49117200-bad2-11ea-9576-41e378eeaf02.jpg)
With terminal shoe that

**Comment by George2912** [comment]
![16048607972426314731983640195872](https://user-images.githubusercontent.com/71301318/98481388-28ab9f80-21b7-11eb-99ff-64274c3c8f51.jpg)
help, is this x96mini clone? 

sorry for my english i use a translator
