### ISSUE TITLE
Error installing Drastic

### ISSUE THREAD

**Issue by xuan-ming** [EmuELEC/EmuELEC#212]
Hello, when I use the emuelec native command to install Drastic, it shows that there is no network connection.
It has been successfully installed with this command in the past, but it has been found to be unusable recently.

**Comment by xuan-ming** [comment]
The version is emuelec3.6

**Comment by shantigilbert** [comment]
> Hello, when I use the emuelec native command to install Drastic, it shows that there is no network connection.
> It has been successfully installed with this command in the past, but it has been found to be unusable recently.

You need to be connected to the internet or else it will not work.

**Comment by xuan-ming** [comment]
OK
