### ISSUE TITLE
FBA:  "game ratio" and "integer scale" options ignored

### ISSUE THREAD

**Issue by caseyjmorris** [EmuELEC/EmuELEC#221]
**Describe the bug**
FBA:  "game ratio" and "integer scale" options ignored

**To Reproduce**

1. Start EmulationStation
2. Go to FBA game list
3. Press select while highlighting a game
4. Go to "advanced game options" or "advanced system options" and change the "integer scale" and "game ratio" options.
5. The setting has no effect.  You change change the options in-game by pressing hotkey + X to bring up the RetroArch menu and changing the options there, but this setting will be lost if you exit the game.

**Expected behavior**
Expected the setting to affect the scaling and aspect ratio game is rendered in.

**Screenshots**
(None)

**EmuELEC version:**
 - Version 3.6

**Device (please complete the following information):**
 - SOC: Amlogic S905X3
 - Brand: EVER EXPRESS
 - Model T95 MAX+
 - Version (not aware of multiple versions of this device)

**Additional context**
(None)

**Comment by shantigilbert** [comment]
I cannot reproduce this, but first of all, EmuELEC does not have a FBA core not sure if you mean FBneo, but the scale and ratio work fine in FBneo, I just tested it with a handful of games.

**Comment by caseyjmorris** [comment]
Yes, sorry, didn't realize there was a difference. 

Settings:

![IMG_20200713_215042](https://user-images.githubusercontent.com/3388158/87371383-3af03680-c553-11ea-8d56-a44cd4625e15.jpg)

In game:
![IMG_20200713_215107](https://user-images.githubusercontent.com/3388158/87371396-43487180-c553-11ea-9f2b-c73af90296c4.jpg)

In game menu:

![IMG_20200713_215126](https://user-images.githubusercontent.com/3388158/87371434-5a875f00-c553-11ea-8b82-3a476a9531b3.jpg)

As you can see, if I change the setting from the in game menu I see the expected result in the background:

![MVIMG_20200713_215133](https://user-images.githubusercontent.com/3388158/87371464-712db600-c553-11ea-93ea-d9c0491cf58c.jpg)


Am I doing something wrong here?

**Comment by shantigilbert** [comment]
You never mentioned you use Bezels, disable them to use those options

**Comment by caseyjmorris** [comment]
Didn't realize that was an issue, since I just left that setting with its default value.  That seems to fix it.

**Comment by shantigilbert** [comment]
Bezels need predefined aspect or else they will display incorrectly :)
