### ISSUE TITLE
Wifi dongle doesn´t work

### ISSUE THREAD

**Issue by retriok** [EmuELEC/EmuELEC#226]
I use a raspberry pi wifi dongle WLU6331 chipset Broadcom BCM43143 thatr works fine with emuelec 3.5 but it dosen't work with emuelec 3.6. I'm using oga version of emuelec.

**Comment by ozkantuzemen** [comment]
Realtek rtl8188ee (for ex. WIFI USB 2.0 150 MB/s NANO) doesn't work either. It works with Emuelec 3.5.

**Comment by andot** [comment]
Comfast CF-811AC can't work.

**Comment by shantigilbert** [comment]
Is this still an issue?
