### ISSUE TITLE
Support for Armbian vs Steam Link on emuELEC

### ISSUE THREAD

**Issue by siliconhippy** [EmuELEC/EmuELEC#234]
Hi !

Read the Wiki, great to know all features and -ng progress.

Question: Any plans to bring emuELEC on Armbian ( as with CoreElec)? This would nicely complement Steam Link on Linux.

Alternatively, can Stream Link be created on the standalone emuELEC?

**Comment by shantigilbert** [comment]
The awnser to both questions is no, sorry
