### ISSUE TITLE
NDS without internet

### ISSUE THREAD

**Issue by chenteparao** [EmuELEC/EmuELEC#239]
Hi everyone;

I buyed a RK2020 and installed Emuelec 3.6, I havent a dongle with Wifi and I wanna install Drastic, is possible install this core manually? Thanks

**Comment by shantigilbert** [comment]
Rk2020 is not supported

**Comment by chenteparao** [comment]
> Rk2020 is not supported

Not supported NDS or not Suppported for that machine or Team behind Emuelec not suported this device?

**Comment by shantigilbert** [comment]
The device, Rk2020 is not supported.
