### ISSUE TITLE
Change to other Font for ozone failed on EE3.6

### ISSUE THREAD

**Issue by yingw** [EmuELEC/EmuELEC#241]
Before 3.6 I used to change some Chinese font for RetroArch ozone theme, the steps:
1. in ftp, transfer **regular.ttf**, and **bold.ttf** to `/tmp/assets/ozone`
2. Exit to RetroArch, select Chinese in `User` > `Language` menu, save config file.
3. Done. Everytime restarted, the fonts remains.

But in 3.6, I did the exactly steps as before, but It just show normal once when I change in menu. After restart RA, all menu words turns into ????, looks like an default EN fonts. If I switch to English in menu, it shows en normally, but is some Pixel Font (Strange!) not the default one.

And check the `/tmp/assets` and `/storage/assets/ozone`, the Chinese fonts remains there.

I tested several times. And tested in EE 3.4, 3.5, everything works fine. Looks like a bug in 3.6.

BTW, I noticed, In 3.4, 3.5, the menu just the language name, such as "English", the 3.6 shows "English (need restart...)", Is there any extra step to "restart"?

**Comment by yingw** [comment]
The normal default fonts:

![image](https://user-images.githubusercontent.com/1177503/88927599-38f3da80-d2aa-11ea-9824-490d162e3e64.png)

After Updated CN fonts:
![image](https://user-images.githubusercontent.com/1177503/88926682-e960df00-d2a8-11ea-9899-65e0cbc5ede3.png)

![image](https://user-images.githubusercontent.com/1177503/88926795-101f1580-d2a9-11ea-8108-c36977942894.png)
and 
![image](https://user-images.githubusercontent.com/1177503/88926736-fd0c4580-d2a8-11ea-803c-666b730d0b64.png)

After restart:
![image](https://user-images.githubusercontent.com/1177503/88926827-1b724100-d2a9-11ea-89ea-16848d8b4be7.png)
and (What's this Font?)
![image](https://user-images.githubusercontent.com/1177503/88926842-2036f500-d2a9-11ea-8c40-9f99ab6b5436.png)

**Comment by shantigilbert** [comment]
Can you test v3.7-TEST ? https://github.com/EmuELEC/EmuELEC-tests/releases

**Comment by yingw** [comment]
> Can you test v3.7-TEST ? https://github.com/EmuELEC/EmuELEC-tests/releases

Hi, Tested. But unfortunately it failed the same as 3.6.

After reenter RetroArch, it shows ???? again.

Change to EN, the strange Font:

![image](https://user-images.githubusercontent.com/1177503/89185816-6ce23f00-d5cd-11ea-9935-ba749c2ded59.png)

Save config file, reenter RetroAerch, it return to normal Font.

![image](https://user-images.githubusercontent.com/1177503/89185863-82efff80-d5cd-11ea-88bc-6691e2551b68.png)

**Comment by shantigilbert** [comment]
Sorry then, I have no idea why that happens as I have never used changed fonts. :(

**Comment by shantigilbert** [comment]
This should be fixed now, please reopen the issue if its not.

**Comment by yingw** [comment]
> This should be fixed now, please reopen the issue if its not.

Thanks, but I had fixed it by copying the 'pkg' folder from <https://github.com/libretro/retroarch-assets> to the '/tmp/assets' folder. And this is also mentioned and solved in simular solution by other guys using Chinese.

I will test the new version sometime.

**Comment by shantigilbert** [comment]
That is the same "fix" I applied.

**Comment by yingw** [comment]
@shantigilbert hi, found it breaks ag. in 4.1 and 4.2, and lot report from some Chinese forum：https://tieba.baidu.com/p/7319507359

![image](https://user-images.githubusercontent.com/1177503/127451908-a85ded37-2679-4dce-8f86-b0260a6521e4.png)

just change to Chinese (whether change fort in /tmp/assets/ozone or not) , save config, restart, it comes 口口口( not the ??? last time), if using English as default lang and change to Chinese after entering RA, it works normally.

found you have updated the pkg folder in the last fix, and I tried to update this time, not working.

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/534
