### ISSUE TITLE
Drastic problems

### ISSUE THREAD

**Issue by ouroboros420** [EmuELEC/EmuELEC#246]
I really enjoy emuelec, apart from drastic. It starts up games fine, but I am not able to get any menu up (no Fx button is working). I still couldn't find any wiki page or forum post describing the hotkeys for drastic as well how to actually play the games. 
As example, when trying to play GTA China town wars, you can't get past the screen where it asks you to chose a save slot, because the stylus isn't giving any input anymore. 
I am on latest test build for the OGA BE, if that changes anything for you. Help would be much appreciated 

Edit: you might want to implement a time out feature for the drastic installer script, once its finished (like you have with bios missing dialog). Cause the way it is now, you can't quit the installation via the options, but have to press F1+F6.

**Comment by shantigilbert** [comment]
Use discord for this kind of questions please
