### ISSUE TITLE
Some messages can't translated

### ISSUE THREAD

**Issue by ws02589111** [EmuELEC/EmuELEC#247]
The following msgid can't  be translated at input configure window:
```
LEFT ANALOG RIGHT
LEFT ANALOG DOWN
RIGHT ANALOG DOWN
RIGHT ANALOG RIGHT
D-PAD UP
D-PAD DOWN
D-PAD LEFT
D-PAD RIGHT
BUTTON A / EAST
BUTTON B / SOUTH
BUTTON X / NORTH
BUTTON Y / WEST
LEFT SHOULDER
RIGHT SHOULDER
LEFT TRIGGER
RIGHT TRIGGER
LEFT THUMB
RIGHT THUMB
HOTKEY ENABLE
```
Branch: dev, master

I had tried add the msgid and msgstr  to ko, ja_JP and zh_CN and rebuild it, but no effected. 
(The msgid get from the file emuelec-emulationstation\es-core\src\guis\GuiInputConfig.cpp)

**Comment by joao-pedro-barbosa** [comment]
I've located another literals in other sections. Like start menu (reboot, reboot from nand...).
Probably is not just focused in controllers.
