### ISSUE TITLE
Performous

### ISSUE THREAD

**Issue by deuteragenie** [EmuELEC/EmuELEC#26]
It would be great to add performous (karaoke game) to the distro: https://performous.org/

**Comment by kassak** [comment]
They do not have arm version for now
https://github.com/performous/performous/issues/17

**Comment by shantigilbert** [comment]
> 
> 
> They do not have arm version for now
> [performous/performous#17](https://github.com/performous/performous/issues/17)

Thanks I will close this issue for now
