### ISSUE TITLE
Mupen64plux_nx core having missing and glitch texture on OGA.

### ISSUE THREAD

**Issue by zombiekutez** [EmuELEC/EmuELEC#260]
Im using v3.7 stable
Model: OGA v1.
Core using: mupen64plus-next (2.1 GLES2 be9b85a)
Driver im using is gl
I having same problem like this:
https://github.com/libretro/mupen64plus-libretro-nx/issues/239
I meet this problen in Golden Eye, Perfect Dark, Dongkey kong 64.
Do OGA having GLES3 driver ??? I seen Mali G31 having support GLES3.2

Happy today for N64 run full spees in OGA with that core with Threaded Renderer ON , thank for longtime trying guy.

**Comment by shantigilbert** [comment]
Thank you, I have fixed it and it will be available in the next test release :)
