### ISSUE TITLE
Wifi not work on x96 mini 2/16 (Amlogic S905W) Emuelec 3.7

### ISSUE THREAD

**Issue by bennington111** [EmuELEC/EmuELEC#261]
Try to wifi connect from Emuelec mine menu.
Try to wifi connect from menu Setup - Wifi.
Try to wifi connect from Retroarch.
Not work. 
Error /net/connman/service/wifi_....._managed_psk: Input/output ... connection failed.
Error /net/connman/service/wifi_......_managed_psk:Not connected ... disconnection failed.

![PHOTO_20200809_122144](https://user-images.githubusercontent.com/36040586/89729784-a8ec2880-da41-11ea-8dcd-b61f6dda1e61.jpg)
Emuelec 3.7
Try SD card and USB flash drive, the same error.

**Comment by cponzoni** [comment]
i confirm wifi is not working on x96 mini ( s905w )

**Comment by shantigilbert** [comment]
You need to SSH to your device and type 

```
udevadm info /sys/bus/sdio/devices/sdio* | pastebinit
``
then paste the resuting url here

**Comment by bennington111** [comment]
> You need to SSH to your device and type
> 
> ```
> udevadm info /sys/bus/sdio/devices/sdio* | pastebinit
> ```
> 
> then paste the resuting url here

http://ix.io/27P3

**Comment by Alfa83** [comment]
Hola, solo quiero acotar algo yo tenia el mismo problema en X96 mini (amlogic s905w), porque el equipo funciona con banda de 2,4 GHz. "Mi banda local es de 5GHz así que la tuve que bajar". La tarjeta de red inalámbrica del dispositivo es solo compatible con esa frecuencia. Espero sea eso amigo suerte.

**Comment by bennington111** [comment]
> Hola, solo quiero acotar algo yo tenia el mismo problema en X96 mini (amlogic s905w), porque el equipo funciona con banda de 2,4 GHz. "Mi banda local es de 5GHz así que la tuve que bajar". La tarjeta de red inalámbrica del dispositivo es solo compatible con esa frecuencia. Espero sea eso amigo suerte.

I use 2,4 GHz, not 5GHz. But wifi not working.

**Comment by cponzoni** [comment]
wifi works again in 3.8 test release

**Comment by shantigilbert** [comment]
closing this issue, as it seems to be fixed and no more info has been given, feel free to reopen if that is not the case

**Comment by alealeks** [comment]
**EmuELEC V4.7:** WiFi doesn't work on X96 mini. Wi-Fi checkbox is enabled and Wifi hotspot name and password are entered correctly. Everything works correctly on Android.

**Comment by worstcase-scenario** [comment]
Did you check if it's perhaps an issue with your password?
Read this: https://github.com/EmuELEC/EmuELEC/wiki/WiFI#important-all-versions

**Comment by worstcase-scenario** [comment]
Perhaps you should try and update to 4.8-test (beta) version and see if you have the same issues with that version.

**Comment by alealeks** [comment]
> Perhaps you should try and update to 4.8-test (beta) version and see if you have the same issues with that version.

Installed the latest beta version (EmuELEC-Amlogic-ng.aarch64-4.8-TEST-04212024-Generic.img) and the result is the same. Available networks are listed, but it does not connect.
