### ISSUE TITLE
Emuelec Theme Issue

### ISSUE THREAD

**Issue by Frakatchoo** [EmuELEC/EmuELEC#262]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

**Describe the bug**
It seems that there is a problem with some themes, and after investigation, it is impossible to display some text on the system pages, and also impossible to display SVG images.

**Expected behavior**
Emuelec therefore seems to be using an old, fairly basic version of Emulation Station. And it would be good to have an update to have better compatibility with themes.

**Screenshots**
Here's 2 screenshots with 2 different themes :
- Epicnoir Theme by Chicuelo
- Artflix by Alekfull

![IMG_20200810_115137](https://user-images.githubusercontent.com/35847883/89772419-40b14b80-db02-11ea-9071-670e2948d3f3.jpg)
![IMG_20200810_115417](https://user-images.githubusercontent.com/35847883/89772421-4149e200-db02-11ea-8531-049fa655db7e.jpg)

**EmuELEC version:**
 - Version 3.6

**Device (please complete the following information):**
- Odroid Go Advance 1.1

**Additional context**
For information these two themes work under Batocera on my Odroid Go Advance.

**Comment by shantigilbert** [comment]
Update to 3.7
