### ISSUE TITLE
Menu item in gamelist is missing after quit game

### ISSUE THREAD

**Issue by ws02589111** [EmuELEC/EmuELEC#263]
**To Reproduce**
1. enter the game
2. press select + start，enter  the quick menu then quit game

Not 100%, but the probability is very high

**Screenshots**
![Cache_5b909a8a833ae03d](https://user-images.githubusercontent.com/10301545/89851684-ab748c80-dbbf-11ea-88d5-52467bc71ac8.jpg)

**EmuELEC version:**
Emuelec v3.7

**Device (please complete the following information):**
S905M2， S905L

**Comment by shantigilbert** [comment]
Do yo use CN characters ?

**Comment by ws02589111** [comment]
Yes，i replace the font to Microsoft yahei

**Comment by shantigilbert** [comment]
Unfortunately that seems to be an issue with ES and CN characters, I do not have a solution.

**Comment by funwun** [comment]
same issue~~~

**Comment by shantigilbert** [comment]
This has been fixed (or should be), it was a problem with ES vram. But feel free to reopen if its not fixed for you.
