### ISSUE TITLE
gamepad not work when play a mame game on S905M Emuelec 3.7

### ISSUE THREAD

**Issue by Z0287yyy** [EmuELEC/EmuELEC#264]
Hi,

Today, I update to 3.7, and I found gamepad is not work when pay a mame game such as "captain commando", but other emulator is OK.

All buttons are not work, include home button, and I re-config the pad key-mapping, also not work in mame game.

Thanks.

**Comment by shantigilbert** [comment]
Were they working before?

**Comment by Z0287yyy** [comment]
Yes, it work at 3.5 version, and it's a xbox360 pad.
