### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Frisk-0** [EmuELEC/EmuELEC#268]
I have false positive error message regarding awbios.zip for atomiswave. My games runs perfectly. 

![20200816_012318.jpg](https://user-images.githubusercontent.com/59013471/90323252-14148e00-df5f-11ea-9ef0-133a341fa75c.jpg)

I also have the error two times for diablo, one at launching and one at exiting but game works 

![20200816_012559.jpg](https://user-images.githubusercontent.com/59013471/90323307-e0863380-df5f-11ea-82f3-92f5078984f1.jpg)

I'm using gt king s922x and when the error message is displayed, emulationstation runs slow. Have to restart it.

**Comment by shantigilbert** [comment]
This are not false positives, please get the proper files as described in the error

**Comment by TheLastProject** [comment]
See https://github.com/EmuELEC/EmuELEC/wiki/Common-Questions#why-doesnt-game-x-work

**Comment by Frisk-0** [comment]
Thx for pointing me the wiki but this is not relevant here because all my games work.

Why show an error message if game is not crashing and works properly ?

For example, saturn require only one bios and is not region dependant so why show an error for missing bios if every games work with only one ?

Another example, MSX, dozens of useless files are mentionned missing but all my romset works as expected.

This is only frustration to gather useless files only to avoid an "error" message which is not one error because game work.

**Comment by TheLastProject** [comment]
It is relevant, the page I linked states exactly what your error means.

**Comment by TheLastProject** [comment]
It's also not an error message, it is a warning: "the game **may** not work".

Maybe we can only show this after a crash but using an untested BIOS file can cause other random "weird" issues so I'm not 100% sure if that's the right solution either.

**Comment by shantigilbert** [comment]
As for the slowdown, it has been fixed and will be available on the next test release :)
