### ISSUE TITLE
Corrupted share drive with release 3.7 Odroid Go Advance

### ISSUE THREAD

**Issue by stuart1975** [EmuELEC/EmuELEC#269]
I flashed the file with 
EmuELEC-OdroidGoAdvance.arm-3.7-odroidgo2_v11.img.gz

After that I inserted in odroid go advance black edition. Seems ok emuelec started with no visible errors. After that I pressed button "off" and
inserted in PC open it with Paragon Linux Filesystem and it shows me always 
Filesystem: ext4
partition style: MBR
State: corrupted.
Drive does not show up and cannot copy any file.

I used a 128GB Canvas React micro SD Card from Kingston. 

Doing the same with the previous version everthings is fine.
EmuELEC-OdroidGoAdvance.arm-3.6-odroidgo2_v11.img.gz
Partion is ok and allows me to copy files to drive.

Also formating sd card with NTFS and checking for errors resulted in no errors found.

**Comment by shantigilbert** [comment]
That is a paragon issue not an EmuELEC issue
