### ISSUE TITLE
Within game loudness +- control like in Batocera OS

### ISSUE THREAD

**Issue by stuart1975** [EmuELEC/EmuELEC#271]
I have a odroid go advance and has many keys under screen display with no use within gameplay.

It would be great if it could be implemented loudness +- control within gameplay like in batocera os https://batocera.org/.

**Comment by TheLastProject** [comment]
This already exists, holding I or VI and pressing Up/Down controls the volume (they both control different sliders but not sure how to properly explain)

**Comment by shantigilbert** [comment]
These are already implemented
