### ISSUE TITLE
EmuELEC not booting s905x3

### ISSUE THREAD

**Issue by elioma91** [EmuELEC/EmuELEC#275]
I'm trying to install EmuELEC on an Android TV box, H9X3 Amlogic S905x3 4gb/16gb. I insert the micro SD Card and its not booting. It freezes on the H9x3 Logo.

I downloaded EmuELEC-Amlogic-ng.arm-3.7-Generic.img.gz

and i've tried all the dtbs and nothing happens.

**Comment by shantigilbert** [comment]
Closing this, no reply after 10 days,, open it up again if you still need help
