### ISSUE TITLE
PSP God of war Issue performance

### ISSUE THREAD

**Issue by hehk1234** [EmuELEC/EmuELEC#278]
My RGB 10 comes with this software, GOW have performance issue on snake battle and on begin scene. I know RGB 10 can handle this game because of GPU (Mali G31) and lower resolution.... Retroid Pocket 2 runs this game with more performance and have Mali 400MP2. I hope on future we can see this game fly on all Mali G31. Thanks for the work

**Comment by shantigilbert** [comment]
No support for that device here, sorry

**Comment by hehk1234** [comment]
Yes I know, but It have the same hardware than RK2020 or OGA.

Em ter, 25 de ago de 2020 21:46, shantigilbert <notifications@github.com>
escreveu:

**Comment by shantigilbert** [comment]
Go ask powkiddy to improve it.
