### ISSUE TITLE
[REQUEST] Official support for EmuELEC on the RK2020 handheld game console?

### ISSUE THREAD

**Issue by Hedda** [EmuELEC/EmuELEC#281]
**Is your feature request related to a problem? Please describe.**

Not related to a problem. Just wondering if you have plans to officially support EmuELEC on the RK2020 handheld game consoles?

RK2020 is an inexpensive Linux-based portable gaming console from China using same standard components as ARM TV boxes.

https://rkconsole.com

Currently, in its first version, it is basically a clone/replicate of ODROID-GO Advance hardware based on a RockChip RK3326 SoC with a Quad-Core ARM Cortex-A35 1.3GHz CPU, Mali-G31 Dvalin GPU, and 1GB DDR3 RAMN

https://www.hardkernel.com/shop/odroid-go-advance/

However, being a modern Chinese company I'm sure they will quickly innovate and release newer and enhanced revisions of the device. Hopefully, they will also listen to feedback from the community in regards to hardware and firmware improvements.

**Describe the solution you'd like**

 Official support for EmuELEC on RK2020 handheld game console.

**Describe alternatives you've considered**

No alternatives. 

**Additional context**

RK2020 initially shipped with a pirated copy the firmware for ODROID-GO Advance but since Hardkernel threaten to sue them they have gone from shipping them empty/unflashed to more recently shipping them with a version of EmuELEC (fork?).

**Comment by shantigilbert** [comment]
I have no plans on supporting devices that break licences and copyright laws, so no.
