### ISSUE TITLE
MXS 2 system not found when scraping.

### ISSUE THREAD

**Issue by Broos-E** [EmuELEC/EmuELEC#284]
i am trying to scrape the MSX 2 but get a message saying "some of your systems do not have a platform set" even if if i choose MSX 2 from the systems list.

Emuelec 3.7
Odroid N2

**Comment by shantigilbert** [comment]
Can you edit the file `/storage/.emulationstation/es_systems.cfg` (or inside ConfigFiles in samba) 

and change this `<platform>msx2</platform>` for this `<platform>msx</platform>`

restart Emulationstation and try to scrape them again.

**Comment by Broos-E** [comment]
that seems to have worked thanks
