### ISSUE TITLE
emuelec not booting on s905w

### ISSUE THREAD

**Issue by elioma91** [EmuELEC/EmuELEC#294]
Emuelec not booting on a Tx3 mini 2/16gb with s905w. The emuelec screen appears, creates partition, restarts automatically. And it stays on that screen forever. Im using the gxl_p281_2g dtb. I tried different dtbs and its the same.

![15997898661763766404636257730151](https://user-images.githubusercontent.com/69883247/92842543-4cb25680-f3a9-11ea-8229-b643fac40b45.jpg)

**Comment by SamuEDL** [comment]
Have you tried re-creating the SD with the image?

**Comment by elioma91** [comment]
> Have you tried re-creating the SD with the image?

You mean creating an image and write it on the same sd card?

**Comment by AlienatedDiego** [comment]
It doesn't seem like a problem with .dtb but with your storage. Format the sd and recreate the image, if it does not work try with a different sd or usb.

**Comment by elioma91** [comment]
GOT IT TO WORK FINALLY! Tried different sd cards with different storage capacity and nothing. I tried other dtb that has nothing to do with s905w and it worked *facepalm*

Thanks for the help!!

**Comment by elioma91** [comment]
Solved it. I used another dtb for another processor. Weird how it worked.

**Comment by shantigilbert** [comment]
> Solved it. I used another dtb for another processor. Weird how it worked.

Could be that the procesor is really not s905w many Chinese devices do that

**Comment by kaderr09** [comment]
> GOT IT TO WORK FINALLY! Tried different sd cards with different storage capacity and nothing. I tried other dtb that has nothing to do with s905w and it worked _facepalm_
> 
> Thanks for the help!!

i have the same problem sir ,could you send me the reference of the dtb that you have tried plz

**Comment by AlienatedDiego** [comment]
Check the Amlogic soc on your device to make sure. Without that information it's hard to tell. You can check it from Android using Aida64 app, cpuz or similar. That said, in most cases none of the .dtb for s905w works because it really is a different soc, usually s912.https://github.com/EmuELEC/EmuELEC/wiki/Comprobaci%C3%B3n-Procesador
