### ISSUE TITLE
Analog not working.

### ISSUE THREAD

**Issue by zombiekutez** [EmuELEC/EmuELEC#295]
Device: OGA V1
Emuelec ver. : 3.8-TEST-09112020arm
The analog it my OGA is normal, it working in emulationstation, but it so wear in retroarch, when i set input button Axis Threshold is 1.000 it not working (this conifg is need for console when it need both analog and d-pad working like n64, dreamcast, when axis threshold set is 0.500, the analog stick so work like d-pad) when i turn it to 0.500 in game use bolt d-pad and analog, when i move analog stick only d-pad moving. Sorry im too busy to report log.

**Comment by shantigilbert** [comment]
Sorry we are to busy to investigate
