### ISSUE TITLE
How check my compilation (emulator)

### ISSUE THREAD

**Issue by zerotrzy** [EmuELEC/EmuELEC#296]
Please help me runing my emulator in qemu or other emulator.
How checking my configuration etc.

**Comment by shantigilbert** [comment]
I cannot understand what this has to do with emuelec?

**Comment by zerotrzy** [comment]
I have trouble with my config file. I would chceck my image disk before I put my setup to SD card.

Simple, I would run emuelec on desktop linux machine before.

**Comment by shantigilbert** [comment]
I honestly have no idea what you are talking about... Sorry, please either explain exactly what yo u are trying to do, if possible with steps. Emuelec does not run on desktop pc

**Comment by zerotrzy** [comment]
emuelec can run on desktop if using emulator. for example qemu https://wiki.qemu.org/Documentation/Platforms/ARM

Question is how download kernel, bios etc.

**Comment by shantigilbert** [comment]
I have no idea, qemu is not supported
