### ISSUE TITLE
Mupen64plus-Next black screen on latest Emuelec test build - Android Q Box

### ISSUE THREAD

**Issue by Cee123** [EmuELEC/EmuELEC#300]
**Describe the bug**
Just letting you guys know, Mupen64plus-next loads to a black screen on the Android Q Box. I'm not sure why that is, but I think this brand of Android Box is only compatible with OpenGles2 whereas the core version is built for OpenGles3.

I'm using the latest Arch64 test build. The "generic" version.

**To Reproduce**
-

**Expected behavior**
Should load, but doesn't.

**Screenshots**
-

**EmuELEC version:**
 3.8-TEST-09112020

**Device (please complete the following information):**
Android 5.1
Amlogic s905 quad-core cortex-A53 2.0 Ghz
Mali-450 5-Core GPU
2GB DDR3 16GB EMMC
2.4G +5G WIFI,802.11 B/G/N
100/1000M LAN
Bluetooth4.0
Hardward 3D graphics acceleration
2K*4K Support
Dolby/ 3G/ SPDIF/ IEC958/ Coaxial

**Additional context**
Anyway I can compile the OpenGles2 version of Mupen Next? Or someone can provide it? I think the previous version of Emuelec that I tried had the OpenGles2 version and it worked fine.

**Comment by Cee123** [comment]
Well I just compiled a few Mupen64plus-next cores on Ubuntu using my Odroid N2 so I could get them arch64. And I've tried both cores for opengles2 and opengles3 and using LLE and without. And each time I try to get these cores to work, it appears to work for a second or so but then it crash dumps resulting in a Segmentation Fault.

![20200922_113717-20200922-120720352](https://user-images.githubusercontent.com/43462099/93843495-9580de00-fccc-11ea-8858-7a7438d749b0.jpg)

[mupen64plus_next_libretro_gles2(LLE).zip](https://github.com/EmuELEC/EmuELEC/files/5259127/mupen64plus_next_libretro_gles2.LLE.zip)
[mupen64plus_next_libretro_gles2.zip](https://github.com/EmuELEC/EmuELEC/files/5259130/mupen64plus_next_libretro_gles2.zip)
[mupen64plus_next_libretro_gles3(LLE).zip](https://github.com/EmuELEC/EmuELEC/files/5259131/mupen64plus_next_libretro_gles3.LLE.zip)
[mupen64plus_next_libretro_gles3.zip](https://github.com/EmuELEC/EmuELEC/files/5259133/mupen64plus_next_libretro_gles3.zip)

Not sure what I could do to get this core to work.

**Comment by asakous** [comment]
use old version of  mupen64plus-next . probably before this commit tag (9f3169).

**Comment by Cee123** [comment]
> 
> 
> use old version of mupen64plus-next . probably before this commit tag (9f3169).

Awesome, thank you! Alright I'll try one of the older versions before that commit tag then, I'll compile one or two of those and I'll see if they work.

**Comment by Cee123** [comment]
> 
> 
> use old version of mupen64plus-next . probably before this commit tag (9f3169).

I couldn't get an older version to build for some strange reason. I'll keep trying.

**Comment by asakous** [comment]
> > use old version of mupen64plus-next . probably before this commit tag (9f3169).
> 
> I couldn't get an older version to build for some strange reason. I'll keep trying.

try remove PKG_SHA256 in package.mk. maybe works

**Comment by Cee123** [comment]
> 
> 
> > > use old version of mupen64plus-next . probably before this commit tag (9f3169).
> > 
> > 
> > I couldn't get an older version to build for some strange reason. I'll keep trying.
> 
> try remove PKG_SHA256 in package.mk. maybe works

Ok, thank you. I'll try that and see if it works.

**Comment by Cee123** [comment]
I tried an older version, the one just before 9f3169 and I tried changing the flags in the Makefile to set them to Gles2 and Gles3. I tried a few different versions. But I keep getting an error now that says error missing libGL.so.1

**Comment by asakous** [comment]
please reference my package settings [https://github.com/asakous/Neo-EmuELEC-H3/tree/master/packages/sx05re/emulators/mupen64plus-nx](url)

**Comment by Cee123** [comment]
> 
> 
> please reference my package settings [https://github.com/asakous/Neo-EmuELEC-H3/tree/master/packages/sx05re/emulators/mupen64plus-nx](url)

I'm not sure I understand. Do I post the issue there and reference it from here? I click on the link but nothing comes up.

**Comment by asakous** [comment]
my bad . typo.  
you can copy the url and paste to chrome.
and use my package.mk and patches  to build mupen64plus-nx.

**Comment by Cee123** [comment]
> 
> 
> my bad . typo.
> you can copy the url and paste to chrome.
> and use my package.mk and patches to build mupen64plus-nx.

That works now. Sorry about that. Thanks so much!! I'll try that and see if I can get it to work. Much appreciated!

**Comment by Cee123** [comment]
I'm really sorry for being a noob when it comes to github and probably Linux as well. But I'm not sure exactly what I'm supposed to do. So basically I've downloaded these files and placed them in a folder mupen64plus-next, so do I just build it from the package.mk file? And if so, what command do I use? I've tried make but it's not working. Or do I fetch EmuELEC from the github, fetch mupen64plus-next and add it to that folder and build it from there? Or do I fetch mupen64plus-next from the libretro github and add it to that folder and build it from there? Sorry I'm still trying to figure this out.

**Comment by asakous** [comment]
you need to fetch EmuELEC from the github and replace mupen64plus-next with my files. and build the whole system.
or simply go to [https://github.com/asakous/Neo-EmuELEC-H3/releases/tag/V1.1](https://github.com/asakous/Neo-EmuELEC-H3/releases/tag/V1.1)  and download mupen64plus_next_libretro.zip . hopefully it works on Amlogic  system.
otherwise you just wait to shantigilbert to fix it.
 .

**Comment by Cee123** [comment]
> 
> 
> you need to fetch EmuELEC from the github and replace mupen64plus-next with my files. and build the whole system.
> or simply go to https://github.com/asakous/Neo-EmuELEC-H3/releases/tag/V1.1 and download mupen64plus_next_libretro.zip . hopefully it works on Amlogic system.
> otherwise you just wait to shantigilbert to fix it.
> .

Oh my God thank you so much! You're awesome. I just downloaded the zip file it was a lot easier for me. Thank you.

**Comment by Cee123** [comment]
Interesting, seems now there's a different issue. An error message saying "wrong ELF class".

![20200924_201709-20200924-201744834](https://user-images.githubusercontent.com/43462099/94144064-4345e580-fea3-11ea-937d-f427d9292b5f.jpg)

**Comment by asakous** [comment]
that means the binary file is not compatible with your system. so I am out of ideas . you better wait for shantigilbert to fix it.

**Comment by Cee123** [comment]
> 
> 
> that means the binary file is not compatible with your system. so I am out of ideas . you better wait for shantigilbert to fix it.

Thanks for all your help. Yeah I think I'll just wait for a fix hopefully in the next version or whatever.

**Comment by Cee123** [comment]
I think that core could be 32-bit. Because it says wrong ELF class: ELFCLASS32.

**Comment by Cee123** [comment]
So no one knows what's causing the segmentation fault on the mupen64plus-next cores i compiled? Possibly a driver issue?

**Comment by shantigilbert** [comment]
> 
> 
> So no one knows what's causing the segmentation fault on the mupen64plus-next cores i compiled? Possibly a driver issue?

if you are compiling them I think its better to ask in the mupen64 repo.

**Comment by shantigilbert** [comment]
Try this one please

[mupen64plus_next_libretro.zip](https://github.com/EmuELEC/EmuELEC/files/5309014/mupen64plus_next_libretro.zip)

**Comment by Cee123** [comment]
> 
> 
> Try this one please
> 
> [mupen64plus_next_libretro.zip](https://github.com/EmuELEC/EmuELEC/files/5309014/mupen64plus_next_libretro.zip)

Awesome. I will try that version and see if it works. Thanks!

**Comment by Cee123** [comment]
> 
> 
> Try this one please
> 
> [mupen64plus_next_libretro.zip](https://github.com/EmuELEC/EmuELEC/files/5309014/mupen64plus_next_libretro.zip)

Thank you! You're a legend. Can confirm that version 100% works. Thanks for that!

**Comment by shantigilbert** [comment]
This has been fixed on v3.9
