### ISSUE TITLE
OGA Background image scaling looks pixelated in 3.7 and 3.8, was fine in 3.6

### ISSUE THREAD

**Issue by mbroers** [EmuELEC/EmuELEC#306]
On Odroid Go Advance, the background images are not scaling properly in the latest two releases 3.7 and 3.8.  In 3.6 the scaling looks fine for the same image file.

3.8 with background pixellation:
![3 8](https://user-images.githubusercontent.com/2566312/94701434-45280280-0302-11eb-8e9a-bc05e638fe21.jpeg)

3.6 looking fine:
![3 6](https://user-images.githubusercontent.com/2566312/94701504-55d87880-0302-11eb-8d02-408dfa41d381.jpg)

I've tried disabling the theme option 'OPTIMIZE FOR SMALL SCREENS' and it doesnt resolve the issue.

**Comment by shantigilbert** [comment]
Is this still an issue on v4.0?

**Comment by mbroers** [comment]
sadly yeah.. i havent verified on n2+ yet

**Comment by mbroers** [comment]
when i switch scaling to 2x1 or 3x1 the images look fine, but 1x1 they scale like this

**Comment by shantigilbert** [comment]
Ok, then sorry I really do not know why this is happening or how to fix it.

**Comment by mbroers** [comment]
It doesnt happen in crystal but I am unable to find a UI style in crystal that duplicates that old oga default style that worked for me in 3.6. 1x1 in crystal has a bunch of text and doesnt pull the marquee.  Maybe I will petition dim and describe what Im seeking or help collab on that project if possible.

**Comment by mbroers** [comment]
I think I'm losing my mind.  es-theme-emuelec-carbon is fine now. no more pixellation on scaling.  i swear i had this on different themes after recently setting up 4.0 in 1x1 configs but this one is fine now.  close it!

**Comment by dm2912** [comment]
> It doesnt happen in crystal but I am unable to find a UI style in crystal that duplicates that old oga default style that worked for me in 3.6. 1x1 in crystal has a bunch of text and doesnt pull the marquee. Maybe I will petition dim and describe what Im seeking or help collab on that project if possible.

is small panel 3:2 no good for the oga?

![image](https://user-images.githubusercontent.com/25871666/108273918-2240a280-716c-11eb-8e60-d1ba1cf4c554.png)

that was specifically done to mimic a single carousel, but using a single image rather than loading multiple elements

And for gamelist similar.. 

![image](https://user-images.githubusercontent.com/25871666/108274172-6fbd0f80-716c-11eb-8182-d4577eb1da0f.png)

just hit me up on discord in the #theming bit if there's a particular layout you want

**Comment by shantigilbert** [comment]
Also Crystal should be default on v4.0 and it also scales accordingly to the device used, so small panel 3:2 for OGA, small panel 16:9 for OGS

**Comment by mbroers** [comment]
I will check your suggestions, thanks! My personal preference was es-theme-emuelec-carbon specifically for the default 1x1 browsing with the marquee text over box art that fades to video with the marquee moving up and smaller.. I really thought it was perfect but I dig the theme work for crystal very very much. Would be awesome to have such a style in crystal too!  I'll play around but the reason I opened this issue is gone as far as I can tell.

**Comment by dm2912** [comment]
> I will check your suggestions, thanks! My personal preference was es-theme-emuelec-carbon specifically for the default 1x1 browsing with the marquee text over box art that fades to video with the marquee moving up and smaller.. I really thought it was perfect but I dig the theme work for crystal very very much. Would be awesome to have such a style in crystal too! I'll play around but the reason I opened this issue is gone as far as I can tell.

thats basically what small panel does, except it uses screenshot with marquee on top as opposed to box art. 

honestly, the reason i went screenshot route is the new icons for favourites and cheevo's are really hard to line up with boxart which can be all sorts of random shapes. 

without getting too sidetracked, if you go to line 908 of gamelist.xml in crystal you can swap out >image< for >thumb< and get a similar effect..

but no need now carbon is working :D
