### ISSUE TITLE
Porting game doom1 execution path error

### ISSUE THREAD

**Issue by t812206236** [EmuELEC/EmuELEC#307]
**Describe the bug**

doom1 cannot be executed

**To Reproduce**

Download doom1 via wiki

**EmuELEC version:**

EmuELEC 3.8

**Device (please complete the following information):**

oga 1.1

**Additional context**

/storage/.config/emuelec/ports/Doom.sh

the command '/storage/roms/ports/doom2/doom1.wad' should be  '/storage/roms/ports/doom/doom1.wad'

**Comment by TheLastProject** [comment]
Oops, nice find. I'll fix this today.
