### ISSUE TITLE
Flycast bug with analog on Emuelec

### ISSUE THREAD

**Issue by hehk1234** [EmuELEC/EmuELEC#310]
Hello .. Good night. I tested the flycast on some roms and for example: Shadow man and legacy kain.
Analog is simply not recognized as analog. My device is an RGB10 (clone odroid advance). Besides, all the other emulators work well with the buttons, only the flycast that apparently is not synchronizing with the emuelec configuration.
Emuelec 3.8

**Comment by shantigilbert** [comment]
Disable analog to digital on Retroarch. Please only open BUG issues here, this is a user error.

**Comment by hehk1234** [comment]
Sir, the problem is for odroid go advance, retroarch don't give me option
to change "analog - digital" I already try. Another problem, reicast don't
run any rom here, only flycast.

Em qui., 1 de out. de 2020 às 22:31, shantigilbert <notifications@github.com>
escreveu:

**Comment by shantigilbert** [comment]
Rgb10 is not supported, only odroid go advance.

**Comment by hehk1234** [comment]
but they have same hardware, RGB10 is clone from odroid.... all emulators
works fine, I just get the problem with gamepad on dreamcast (and plugin
too). Sorry I don't want disturb you, I try everything to get gamepad set
config, but fails.... it recognize analog like D-pad.

Em qui., 1 de out. de 2020 às 23:13, shantigilbert <notifications@github.com>
escreveu:

**Comment by shantigilbert** [comment]
Go ask the manufacturer then, only odroid go advance is supported.

**Comment by hehk1234** [comment]
Ok bro, I test o batocera and works (with same IMG for odroid advance) . I
like more emuelec because it have more compatibility on rgb10 and shaders
filters.

Em qui., 1 de out. de 2020 às 23:19, shantigilbert <notifications@github.com>
escreveu:
