### ISSUE TITLE
Nintendo DS not showing 3.8-odroidgo2

### ISSUE THREAD

**Issue by s34nvideos** [EmuELEC/EmuELEC#314]
**Describe the bug**
Nintendo DS not showing in the menu
EmuELEC-OdroidGoAdvance.arm-3.8-odroidgo2.img.gz

**To Reproduce**
1. install EmuELEC-OdroidGoAdvance.arm-3.8-odroidgo2.img.gz
2. add nds roms
3. GO to main menu. go nds channel

**Expected behavior**
nintendods to appear

**Screenshots**

**EmuELEC version:**
3.8

**Device (please complete the following information):**
RK2020

**Additional context**

**Comment by AlienatedDiego** [comment]
Emuelec does not support rk2020 devices, you can use it at your own risk, but we cannot offer help.

**Comment by s34nvideos** [comment]
Having same issue on other hardware too
