### ISSUE TITLE
Kodi media player to EmuElec

### ISSUE THREAD

**Issue by Sidordroid** [EmuELEC/EmuELEC#316]
Dear developers, please add the Kodi media player to EmuElec

**Comment by Sidordroid** [comment]
If there is no such opportunity to put Kodi in EmuElec, then implement some kind of alternative media player so that you can relax in addition to games, watching movies and listening to music

**Comment by dm2912** [comment]
just put coreelec on internal, emuelec on sd and switch between the two

**Comment by TheLastProject** [comment]
Also, there is already a media player in the -test version. You can add files in `/storage/roms/mplayer`. Seems to only work for the non-addon version though from what I can see.
