### ISSUE TITLE
How to add RK3399 - nanopc-t4 and work ? 

### ISSUE THREAD

**Issue by keeno1982** [EmuELEC/EmuELEC#321]
I run "PROJECT=Rockchip DEVICE=RK3399 ARCH=arm UBOOT_SYSTEM=nano-pc-t4 make image" and fail, I guess UBOOT_SYSTEM not support. I want to know how it work? Help please.
![111](https://user-images.githubusercontent.com/13664097/95564816-e9701e80-0a51-11eb-928c-c38fc998fc4f.jpg)

**Comment by shantigilbert** [comment]
Emuelec is only for Amlogic and one rockchip device, the odroid go advance, no rk3399 support.
