### ISSUE TITLE
Is it possible to make it possible to turn down the volume of the preview video for games

### ISSUE THREAD

**Issue by Sidordroid** [EmuELEC/EmuELEC#325]
Dear developers, thanks for the cool OS. But there are a few questions 1) Maybe I will repeat myself, but you can add Kodi, if it can't be added, then it didn't hurt to add another multimedia station. 2) Is it possible to make it possible to turn down the volume of the preview video for games - they are too loud and cannot be turned down video volume

**Comment by shantigilbert** [comment]
No, this is not a full fledge os, it is meant ONLY for emulation, but a small media player is already present not for 4k videos or anything above 1080p.

**Comment by shantigilbert** [comment]
Also please read the issue templates they are there for a reason

**Comment by Sidordroid** [comment]
> No, this is not a full fledge os, it is meant ONLY for emulation, but a small media player is already present not for 4k videos or anything above 1080p.

And how to watch video files and listen to music on EmuElec. Please click on the link to the instruction. Thank you

**Comment by Sidordroid** [comment]
> > No, this is not a full fledge os, it is meant ONLY for emulation, but a small media player is already present not for 4k videos or anything above 1080p.
> 
> And how to watch video files and listen to music on EmuElec. Please click on the link to the instruction. Thank you

**Comment by Sidordroid** [comment]
I still don't know how to use the media player in Emuelec. Stick my nose in the instructions please

**Comment by shantigilbert** [comment]
place your videos in /storage/roms/mplayer and it should appear in ES after a restart

**Comment by Sidordroid** [comment]
Thank you. Can you listen to music tracks, for example mp3? Where to put them?

**Comment by shantigilbert** [comment]
not while playing, only as background music for ES `/storage/roms/BGM`
