### ISSUE TITLE
Video screen saver mute does not work

### ISSUE THREAD

**Issue by chucksmith** [EmuELEC/EmuELEC#328]
**Describe the bug**
I'd like to use the video screensaver without sound, but even when I go into Screensaver Settings and turn on Mute Video Audio, the screensaver still plays videos with sound.

**To Reproduce**
1. Go to Screensaver Behavior and choose Random Video.
2. Turn on Mute Video Audio.
3. Launch Screensaver.
4. Hear audio playing with random videos.

**Expected behavior**
I expect to see random game videos without sound.

**EmuELEC version:**
 - Version 3.8

**Device**
 - SOC: S905x3
 - Model: HK1 Box

**Comment by shantigilbert** [comment]
I just tested this and all of my videos play muted... on the video screen and on the video screen saver, can you post the format of one of your videos?

**Comment by chucksmith** [comment]
This was an issue for me in 3.7 and 3.8, but appears to be fixed in 3.9, so I'm closing this ticket.
