### ISSUE TITLE
Does not download kernels and not all kernels are available for download?

### ISSUE THREAD

**Issue by Sidordroid** [EmuELEC/EmuELEC#329]
I am using EmuElec on an amlogic s905x3 tv box and I have identified some shortcomings in the work of Retroarch. Does not download kernels and not all kernels are available for download? When trying to forcibly copy my files from another Retroarch, it does not see them. Is it write-protected? Why is it cut? to put in EmuElec, copy your full-fledged and not trimmed Retroarch?

**Comment by shantigilbert** [comment]
Not sure what you mean by Kernels, if you mean cores then, please do not download them it will break your system, the cores included are the ONLY ones supported.

**Comment by Sidordroid** [comment]
In EmuElec in the Dreamcast emulator, the speed is good, but with fast loading and saving, it gives this thing. And the 3DO emulator in EmuElec lags a lot
![Uploading 17102020532.jpg…]()

**Comment by Sidordroid** [comment]
In EmuElec in the Dreamcast emulator, the speed is good, but with fast loading and saving, it gives this thing. And the 3DO emulator in EmuElec lags a lot
![17102020532](https://user-images.githubusercontent.com/71819151/96320826-2c1a9380-101c-11eb-965f-57425ab27061.jpg)

**Comment by Sidordroid** [comment]
> In EmuElec in the Dreamcast emulator, the speed is good, but with fast loading and saving, it gives this thing. And the 3DO emulator in EmuElec lags a lot
> ![17102020532](https://user-images.githubusercontent.com/71819151/96320826-2c1a9380-101c-11eb-965f-57425ab27061.jpg)

**Comment by Sidordroid** [comment]
In EmuElec on the Dreamcast emulator, the speed is good, but it gives this with fast saving and fast loading. And the Panasonic 3DO emulator lags a lot
![17102020532](https://user-images.githubusercontent.com/71819151/96321321-adbef100-101d-11eb-89fe-736b674bcdb0.jpg)
