### ISSUE TITLE
Script to download bezels does not work with megadrive

### ISSUE THREAD

**Issue by xgrind** [EmuELEC/EmuELEC#331]
**Describe the bug**
Script to download bezels does not work with megadrive

**To Reproduce**
1. Go to Updates and Downloads
2. Click on Bezel Project
3. Click on Install Bezel
4. Click on Megadrive
5. See error

**Expected behavior**
Download bezels from the megadrive according to the roms.

**Screenshots**
![IMG_20201016_192540](https://user-images.githubusercontent.com/3290706/96352314-af79ca80-1098-11eb-8581-9d78ec4341ae.jpg)
![IMG_20201016_192736](https://user-images.githubusercontent.com/3290706/96352328-c02a4080-1098-11eb-9f88-63a8addbd575.jpg)
![IMG_20201016_192926](https://user-images.githubusercontent.com/3290706/96352333-c5878b00-1098-11eb-8f21-212b27b1bddf.jpg)
![IMG_20201016_193027](https://user-images.githubusercontent.com/3290706/96352341-ce785c80-1098-11eb-89cb-9510af4a567d.jpg)

**EmuELEC version:**
 - Version 3.5

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: S905W
 - Brand: Amlogic
 - Model: TX9
 - Version: p281_2

**Additional context**
The bezels of other systems are downloaded normally, but only megadrive that gives this problem. The developers said on Facebook that the bug was fixed and may not have been updated on Emuelec.

**Comment by shantigilbert** [comment]
No support for pre-made pirated images.
