### ISSUE TITLE
Error downloading bezels from Megadrive

### ISSUE THREAD

**Issue by xgrind** [EmuELEC/EmuELEC#332]
**Describe the bug**
The system downloads only the default bezel from the megadrive, while being able to download bezel from each game on other systems.

**To Reproduce**
1. Go to 'Main Menu'
2. Click on 'Updates & Downloads'
3. Click on 'The Bezel Project'
4. Scroll down to 'Megadrive'
5. Click on 'Megadrive'
6. Click on 'Install'

**Expected behavior**
Download all bezels according to the name of the game

**Screenshots**

**EmuELEC version:**
 - Version [3.8]

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: [S905W]
 - Brand: [Amlogic]
 - Model [TX9]
 - Version [2GB ram]

**Additional context**
[ix.io/2BjX](url)

**Comment by shantigilbert** [comment]
Can you please stop posting this? I told you I do not support pre-made images filled with roms.
