### ISSUE TITLE
EmuELEC 3.8/Flycast 1.9.0/Fist of the north star (Atomiswave) HP bar, layer bug

### ISSUE THREAD

**Issue by pyjmj05** [EmuELEC/EmuELEC#333]
EmuELEC 3.8 / Odroid N2+

![1](https://user-images.githubusercontent.com/73285776/96874000-99ad4080-14b0-11eb-8547-19bc4fefb9c1.PNG)
↑ The layers of the HP bar were reversed. (EmuELEC)

![2](https://user-images.githubusercontent.com/73285776/96874027-a2057b80-14b0-11eb-87cd-d9a075ab2ac3.PNG)
↑ It should be like this originally. (Retro Arena)

**Comment by shantigilbert** [comment]
This should probably be discussed on the other issue you opened. https://github.com/libretro/flycast/issues/973
