### ISSUE TITLE
Where to find dtb file for MXQ Pro 4K

### ISSUE THREAD

**Issue by tperry82** [EmuELEC/EmuELEC#339]
Can't seem to find the right dtb image file for MXQ Pro 4K in the latest versions of emuelec. Can I download it somewhere, or do I need to download an earlier version, to work with this android box?

**Comment by SamuEDL** [comment]
The dtbs are located in the "device_tree" directory on the SD. If not, check that you are using the version corresponding to your tvbox:
s905/s905x/s905w/s905d/s912: EmuELEC-Amlogic.arm-*.*-Generic.img.gz
S905x2/s905x3/s922: EmuELEC-Amlogic-ng.arm-*.*-Generic.img.gz

**Comment by tperry82** [comment]
Yeah I searched there, but no luck. Turns out I had the wrong version. thanks, mate!
