### ISSUE TITLE
psp games do not work

### ISSUE THREAD

**Issue by kaderr09** [EmuELEC/EmuELEC#341]
hello 
i have the tx3 mini s905 with muelec 3.9 . everything work great but when i add psp roms and try to play them they crash i think it has relation with the bios
wich bios file fits emuelec if you have a solution
thank you for all what you do to improve the project

**Comment by shantigilbert** [comment]
Please fill the template issues

**Comment by kaderr09** [comment]
> Please fill the template issues



> Please fill the template issues

i have not understood so sorry!
i am not so familiar with the project

**Comment by shantigilbert** [comment]
When you open an issue it ask what kind of issue, fill out the information asked in there.
