### ISSUE TITLE
how to make psp roms work 

### ISSUE THREAD

**Issue by kaderr09** [EmuELEC/EmuELEC#343]
hello i have a tx3 mini tv box wit s905 ,everything is ok excepting psp roms 
thy do not work . and this is a link of a video witch describes the situation  
https://www.youtube.com/watch?v=ang6-QG-jJQ
 any suggestion please

**Comment by shantigilbert** [comment]
You do not have a S905, that is a s912, PPSSPP stand alone does not work on S912, use the libretro one. and Please stop posting this!

**Comment by kaderr09** [comment]
> You do not have a S905, that is a s912, PPSSPP stand alone does not work on S912, use the libretro one. and Please stop posting this!

sorry i have posted it again because the previous posts do not have enough information 
i thought tx3 mini is s905 from browsing it at the official site 
. CPU: Amlogic S905W Quad-Core 64bit Cortex-A53 1.5GHz
thank you for your patience and so sorry for re-posting again

**Comment by shantigilbert** [comment]
They sell a gazillion different "TX3" devices, none of them have the same components, yours is a S912.
