### ISSUE TITLE
Black screen when connected via av-out to CRT TV

### ISSUE THREAD

**Issue by Sidordroid** [EmuELEC/EmuELEC#347]
Black screen when connected via av-out to CRT TV

I still did not figure out what to change where. I read the wiki and did not understand anything. I just know the resolution of my electronic beam TV 480cvbs and 576cvbs. Please give detailed instructions on how to submit an image, otherwise I do not understand anything.Advanced IP Scanner can be used?
My device tv box amlogic s905x3

Maybe add all the permissions to the settings or implement the function of automatically setting the screen resolution?

**Comment by bennington111** [comment]
https://github.com/EmuELEC/EmuELEC/wiki/Salida-RCA
