### ISSUE TITLE
Screen position. Emuelec 3.9. X96 mini 2/16 via RCA.

### ISSUE THREAD

**Issue by bennington111** [EmuELEC/EmuELEC#349]
Hi. I use Emuelec 3.9 on x96 mini via RCA using this guide: https://github.com/EmuELEC/EmuELEC/wiki/Salida-RCA. 
Screen shifted left. 
How to change screen position? 
Which file contains the screen position settings?
![InkedDSC_5650_LI](https://user-images.githubusercontent.com/36040586/99057203-21fc9e00-25a4-11eb-8712-91871e1d07cb.jpg)
![InkedDSC_5651_LI](https://user-images.githubusercontent.com/36040586/99057208-232dcb00-25a4-11eb-909f-6c2ff4fca8ff.jpg)

**Comment by shantigilbert** [comment]
not easy to do, but follow this issue. 

https://github.com/EmuELEC/EmuELEC/issues/61

**Comment by shantigilbert** [comment]
No reply for 10 days, will assume fixed, otherwise please feel free to reopen this issue.
