### ISSUE TITLE
[Test 4.0 AARCH64 for N2] missing libxkbcommon all cores

### ISSUE THREAD

**Issue by fabioL78** [EmuELEC/EmuELEC#352]
Can't open any libretro core, error can't find libxkbcommon file. Directory usr/bin/retroarch seems to be missing altogether. 

![IMG_20201116_194849](https://user-images.githubusercontent.com/74564355/99296976-e08c1d00-2847-11eb-8c48-5091a2b74712.jpg)

**Comment by shantigilbert** [comment]
Thanks, I am uploading a fixed version.

**Comment by shantigilbert** [comment]
Re-uploaded and fixed

**Comment by fabioL78** [comment]
Working great, thanks!
