### ISSUE TITLE
No sound in game emuelec 4.0-TEST-11162020 on x96 mini 2/16 (s905w).

### ISSUE THREAD

**Issue by bennington111** [EmuELEC/EmuELEC#353]
No sound in game emuelec 4.0-TEST-11162020 on x96 mini 2/16 (s905w) hdmi .

**Comment by AlienatedDiego** [comment]
Thanks, we suspect some problems with test 4.0 test for s905 family
Please check if any of the unconfirmed issues are reproduced:

Crashes in E.S when navigating between systems

sound problems in some cores like mame, flycast genesis + or snes9x; in others like pcsx_rearmed or ppsspp it seems to work

sound problems in E.S (videos)

unstable or running cores too fast (Mupen 64, flycast)

Remember that it is only a first test to identify problems.

**Comment by shantigilbert** [comment]
Thanks I can confirm it does not work in Retroarch, I will investigate.

**Comment by shantigilbert** [comment]
Uploaded a fixed image: https://github.com/EmuELEC/EmuELEC-tests/releases/tag/v4.0-test
