### ISSUE TITLE
How do you get Duke Nukem 3D to work?

### ISSUE THREAD

**Issue by Cee123** [EmuELEC/EmuELEC#358]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

**Describe the bug**
Duke Nukem 3D (the PC port) doesn't appear to be working on EmuElec. I'm not sure if it's unsupported yet or it's not working due to my own user error. 

**To Reproduce**
In the roms folder, I've tried creating two folders (because I'm not sure which is correct)
-duke3d
-eduke32 
and then placed all the Duke Nukem 3D files into both of these folders

**Expected behavior**
Duke Nukem 3D should work (?).

**Screenshots**
Don't have any atm.

**EmuELEC version:**
 - Version 4.0 (unofficial test release)

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
All the devices I've tried so far
- Odroid Go Advance
- Odroid N2
- Amlogic QBox s905

**Additional context**
I've checked the wiki page, nothing mentioned there on how to get it to run (yet?).

**Comment by shantigilbert** [comment]
First. Please fill out the Issue Template
Second,  Eduke is not included in 32bit builds. so if you are using v3.9 or below is not there.

**Comment by Cee123** [comment]
> 
> 
> First. Please fill out the Issue Template
> Second, Eduke is not included in 32bit builds. so if you are using v3.9 or below is not there.

Oh ok, no worries. I'll do that then. Thanks. Yeah you're right, I'm using the unofficial test release. My bad, I should've notice it wasn't in the official release just yet.

**Comment by shantigilbert** [comment]
use the missing bios screen and it will give you the correct path, it should be in /storage/roms/ports/....

**Comment by Cee123** [comment]
> 
> 
> use the missing bios screen and it will give you the correct path, it should be in /storage/roms/ports/....

Alright cool, thanks for that. I'll try that and see where it says to place those files.

**Comment by shantigilbert** [comment]
I just checked and its `/storage/roms/ports/eduke/duke3d.grp`

**Comment by Cee123** [comment]
> I just checked and its `/storage/roms/ports/eduke/duke3d.grp`

Aha! Thank you! So that's what i did wrong. I was thinking the folder name was eduke32 like on retroarena. I'll try that should work.

**Comment by Cee123** [comment]
Doesn't work just comes up with a general error message.

![20201202_102705-20201202-105253664](https://user-images.githubusercontent.com/43462099/100822141-b7e16580-348c-11eb-83a6-2a631c31444e.jpg)

**Comment by Cee123** [comment]
@shantigilbert Doesn't seem to work.

**Comment by shantigilbert** [comment]
Open `/emuelec/ports/Duke Nukem.sh` and edit/add these lines

```
PORT="eduke32"
# init_port binary audio(alsa. pulseaudio, default)
init_port ${PORT} alsa
cd /storage/roms/ports/eduke
${PORT}
```

**Comment by Cee123** [comment]
@shantigilbert Thanks for that! That worked! Those lines weren't in the script file. Thanks for taking the time out to help, really appreciate it. Cheers.
