### ISSUE TITLE
Display bug with Duke Nukem 3D on Odroid Go Advance

### ISSUE THREAD

**Issue by Cee123** [EmuELEC/EmuELEC#359]
**Describe the bug**
Incorrect resolution or display of Duke Nukem 3D on the Odroid Go Advance. Multiple overlapping displays of the game across the top third of the screen.

**To Reproduce**
- Using the 4.0 test version of EmuElec.

**Expected behavior**
Should display fullscreen.

**Screenshots**
![20201204_222506-20201204-222535274](https://user-images.githubusercontent.com/43462099/101175741-7e714b80-3680-11eb-8eef-48cd756db765.jpg)

**EmuELEC version:**
 - Version 4.0 Test

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
Odroid Go Advance.

**Additional context**
Tried changing the resolution under the config files as well as the screen size, but it doesn't make any difference. I'm not sure if anyone is aware of this bug, so I just thought I'd report it to you guys here. This only seems to happen on the OGA, on everything else it runs perfectly.

**Comment by shantigilbert** [comment]
I don't think I have tested Eduke on OGA, so I am not sure why this is happening, but seems resolution related. Try modifying `/storage/.config/eduke32/eduke32.cfg` and change/add these lines under `[Screen Setup]`: 

```
ScreenHeight = 320
ScreenWidth = 480
```

**Comment by Cee123** [comment]
Aha! You were right. Thanks! That worked! changing the screenheight and screenwidth worked. I tried other resolutions before but for some reason none of them stuck.

**Comment by Cee123** [comment]
That seemed to have fixed it.

**Comment by johannesbehr** [comment]
Could you please share your complete eduke32.cfg for the OGA?
I'm not getting the corect resolution to work :(

**Comment by Cee123** [comment]
> 
> 
> Could you please share your complete eduke32.cfg for the OGA?
> I'm not getting the corect resolution to work :(

Yeah of course. There are two separate config files on two separate partitions. Both called eduke32.cfg.

The first one goes in ./config/eduke32 on your storage partition. And the other one goes in the /ports/duke3d on your EEROMS partition. Hope it helps.

[Storage (Linux Partition).zip](https://github.com/EmuELEC/EmuELEC/files/6263166/Storage.Linux.Partition.zip)
[EERoms (Windows Partition).zip](https://github.com/EmuELEC/EmuELEC/files/6263167/EERoms.Windows.Partition.zip)

**Comment by Weestuarty** [comment]
Hey i keep getting stuck on a black screen could you confirm for me what DN3d files you added to the base install and anything else. desperately need help
