### ISSUE TITLE
NDS disappeared from my RGB10

### ISSUE THREAD

**Issue by tylibra2** [EmuELEC/EmuELEC#361]
NDS disappeared from my RGB10, but on the PC appears the NDS folder with the ROMS. Can you tell me how I could solve this problem?

**Comment by shantigilbert** [comment]
That device is not supported

**Comment by tylibra2** [comment]
I used it this morning And suddenly it was gone!And some emulators have a small screen eg: N64 and dreamcast, and the steering controls don't work!
________________________________
De: shantigilbert <notifications@github.com>
Enviado: sábado, 5 de dezembro de 2020 15:49
Para: EmuELEC/EmuELEC <EmuELEC@noreply.github.com>
Cc: tylibra2 <danipereirarj19@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [EmuELEC/EmuELEC] NDS disappeared from my RGB10 (#361)


That device is not supported

**Comment by shantigilbert** [comment]
Did you not read my comment?
