### ISSUE TITLE
Brightness adjust with hotkeys on Odroid Go Advance

### ISSUE THREAD

**Issue by stats121** [EmuELEC/EmuELEC#362]
**Describe the bug**
The brightness cannot be adjusted with the hot key on v3.9 on OGA. The volume adjustment with the hotkey works fine e.e. Hot key + Up/Down, however Hot key + Left/Right creates a save state instead of adjusting the brightness.

**To Reproduce**
Open up a game i.e. Mega drive, press hot key + right

**Expected behavior**
Brightness to adjust

**Screenshots**
None

**EmuELEC version:**
v3.9

**Comment by shantigilbert** [comment]
You are using the wrong hotkey, F1 is for retroarch, F5 is global

**Comment by stats121** [comment]
Thanks, just tested it and I was using wring HK.
