### ISSUE TITLE
powkitty rgb10 wifi dongle realtek https://m.aliexpress.com/item/1005001603487471.html do not work 

### ISSUE THREAD

**Issue by Levidccj** [EmuELEC/EmuELEC#365]
please help the dongle is https://m.aliexpress.com/item/1005001603487471.html
i use emuelec 3.9 any alts 

i might just need help installing it[](https://m.aliexpress.com/item/1005001603487471.html)

**Comment by shantigilbert** [comment]
That device is not supported
