### ISSUE TITLE
Add another NDS emulator - Other than Drastic, is it possible?

### ISSUE THREAD

**Issue by tylibra2** [EmuELEC/EmuELEC#367]
Is there no way for another NDS emulator that is open soucer? 
Since Drastic is closed source.

**Comment by shantigilbert** [comment]
Not AFAIK. 

Please use discord for these type of questions.

**Comment by Cee123** [comment]
> Is there no way for another NDS emulator that is open soucer?
> Since Drastic is closed source.

I managed to add the cores for both desmume and melonDS to a couple of my setups. But unfortunately melonDS didn't work on anything, and desmume ran at like 3 or 4 fps. But on my Odroid N2 the speed wasnt bad but sadly still slower than Drastic.
