### ISSUE TITLE
How to take a screenshot in OGA on terminal?

### ISSUE THREAD

**Issue by mtoensing** [EmuELEC/EmuELEC#374]
Hi! 

Normally I take screenshots with https://github.com/AndrewFromMelbourne/raspi2png but I am unable to unstall this on EmuELEC. How do you guys take direkt screenshots on the terminal?

**Comment by shantigilbert** [comment]
There is currently no option that I know of, you could try dumping the whole fb to a png, but at the moment I do not remember the exact command

I will look into the program you linked to see if I can incorporate it in future versions.

**Comment by mtoensing** [comment]
That would be great. I am working on an article about the best images for the RockChip RK3326 handhelds. But I am not able to take high quality screenshots in EmuELEC... =/

**Comment by shantigilbert** [comment]
Is this functionality available in other distros for the Rk3326 ?

**Comment by mtoensing** [comment]
If you have an open OS you can install software. EmuELEC uses OpenELEC which seems to be designed around a locked filesystem.

**Comment by shantigilbert** [comment]
Sure, but my question was if this is already available in other distros, or do you mean you installed that software you linked? 

if that is the case, try installing the binary to `/emuelec/bin` and libs to `/emuelec/lib`

**Comment by mtoensing** [comment]
I installed the software. 
If I try to do this in EmuELEC:

`curl -sL https://raw.githubusercontent.com/AndrewFromMelbourne/raspi2png/master/installer.sh | bash -`

I only get errors. 

If I try this: 

`apt-get -y install libpng12-dev git-core`

It tells me this is not the way it works on OpenELEC. How do I install it in these folders?

**Comment by mtoensing** [comment]
Even git clone https://github.com/AndrewFromMelbourne/raspi2png.git does not work. I am not a linux wizard so I think I might stop here.

**Comment by shantigilbert** [comment]
Yeah you won't be able to do that, EmuELEC is not a typical OS, if you have the binary already compiled you can follow what I said earlier, else, it will need to be compiled elsewhere first, that is why I asked if it was available on other Rk3326 devices already.

**Comment by shantigilbert** [comment]
I can check this in a few hours and let you know if it even works :)

**Comment by mtoensing** [comment]
Wow! Thank you!

**Comment by shantigilbert** [comment]
[screenshot.zip](https://github.com/EmuELEC/EmuELEC/files/5738662/screenshot.zip)
I compiled a version of fbgrab, but since I no longer have a 32bit environment I was not able to test it. 

Can you unzip it into ConfigFiles/emuelec/bin (using network share) and in SSH type `screenshot.sh` a screenshot of whats on the FB should appear in `/storage/roms/screenshots` 

I will repeat that I have not been able to test this, so please let me know if it worked.

**Comment by mtoensing** [comment]
Wie! Thank you! I will try and respond asap

**Comment by mtoensing** [comment]
Hi, 

thank you very much. It seems to work ... in parts. It takes a screenshot and saves it. See attached screenshot. But this from the boot process and not what the oga is currently displaying. I see the menu and browsed the roms and made several screenshots. All look like the attached one. 

![20201224092447963](https://user-images.githubusercontent.com/136737/103074503-0389b980-45ca-11eb-919c-e9649923dd8c.png)

**Comment by shantigilbert** [comment]
[screenshot_2.zip](https://github.com/EmuELEC/EmuELEC/files/5740364/screenshot_2.zip)

Can you try with this one? same procedure

**Comment by mtoensing** [comment]
Does this answer your question? Thank you! 
![image](https://user-images.githubusercontent.com/136737/103104392-25fdf000-4627-11eb-91e1-cd89d86c444e.png)

**Comment by mtoensing** [comment]
@shantigilbert 

One thing that could be changed: 

SCREENDIR="/storage/screenshots" 

this is better than /storage/roms/screenshots because there is already a directory for that.

**Comment by mtoensing** [comment]
Here is the new name: https://github.com/mtoensing/es-theme-Graphite-OGA

Sorry for the inconvenience.
