### ISSUE TITLE
N64 emulators freeze after a few minutes of playing. (Ram memory full)

### ISSUE THREAD

**Issue by durstboiler** [EmuELEC/EmuELEC#378]
**Describe the bug**
The N64 emulators freeze after a few minutes of play due to the infinite filling of the ram memory.

**EmuELEC version:**
 - Version 3.9

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: s905x
 - Model x96 1gb 8gb

**Additional context**
The duration varies from one game to another, with some games you can play 30min, others freeze after 1 min in the menus.
Each time the cause is the same, the ram memory fills up, (as if the textures accumulated without there ever being a dump), then at 690mb (on 806mb), freeze.
So of course, my box has very little ram, but the same problem would happen on any other system, it would just take longer.

**Comment by shantigilbert** [comment]
First, please provide LOGS, second please read the template, it clearly says to delete all the text above certain line, so that it shows that you have read the rules, clearly you have not, and third, 1gb ram is not really recommended for EmuELEC.

**Comment by durstboiler** [comment]
I do not know how to provide a log file, The box freezes does not crash, so I have to turn it off and no LOG file is created. Otherwise I shut down the game just before the crash by checking the ram, but I don't know if this will teach you anything.

`EmuELEC Run Log
##############################################
#                 EmuELEC                    #
#     Retro emulation for Amlogic Devices    #
#             Based on CoreELEC              #
##############################################
EmuELEC (Official - EmuELEC is FREE! NOT FOR SALE!): 3.9 (Amlogic.arm)
PLATFORM: n64
ROM NAME: /storage/roms/n64/Lylat Wars (Europe) (En,Fr,De).n64
BASE ROM NAME: Lylat Wars (Europe) (En,Fr,De).n64
USING CONFIG: /storage/.config/retroarch/retroarch.cfg
1st Argument: /storage/roms/n64/Lylat Wars (Europe) (En,Fr,De).n64
2nd Argument: -Pn64
3rd Argument: --core=mupen64plus
4th Argument: --emulator=libretro
Full arguments: /storage/roms/n64/Lylat Wars (Europe) (En,Fr,De).n64 -Pn64 --core=mupen64plus --emulator=libretro --controllers=-p1index 0 -p1guid 030000006d04000018c2000010010000 
Run Command is:
/usr/bin/retroarch -v -L /tmp/cores/mupen64plus_libretro.so --config /storage/.config/retroarch/retroarch.cfg /storage/roms/n64/Lylat Wars (Europe) (En,Fr,De).n64
Emulator Output is:
[INFO] RetroArch 1.9.0 (Git ddef65f626)
[INFO] [Overrides]: Redirection du fichier de sauvegarde vers "/storage/.config/retroarch/saves/Lylat Wars (Europe) (En,Fr,De).srm".
[INFO] [Overrides]: Redirection du fichier de sauvegarde instantanée vers "/storage/roms/n64/Lylat Wars (Europe) (En,Fr,De).state".
[INFO] === Build =======================================
[INFO] Capacités:  NEON VFPv3 VFPv4 ASIMD
[INFO] Built: Oct 23 2020
[INFO] Version: 1.9.0
[INFO] Git: ddef65f626
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [CORE]: Loading dynamic libretro core from: "/tmp/cores/mupen64plus_libretro.so"
[INFO] [Overrides]: Core-specific overrides found at /storage/.config/retroarch/config/Mupen64Plus GLES2/Mupen64Plus GLES2.cfg.
[INFO] [Overrides]: No content-dir-specific overrides found at /storage/.config/retroarch/config/Mupen64Plus GLES2/n64.cfg.
[INFO] [Overrides]: No game-specific overrides found at /storage/.config/retroarch/config/Mupen64Plus GLES2/Lylat Wars (Europe) (En,Fr,De).cfg.
[INFO] Config: appending config "/storage/.config/retroarch/config/Mupen64Plus GLES2/Mupen64Plus GLES2.cfg"
[INFO] [Environ]: SET_VARIABLES.
[INFO] Options par jeu : options de cœur spécifiques au jeu trouvées dans /storage/.config/retroarch/config/Mupen64Plus GLES2/Lylat Wars (Europe) (En,Fr,De).opt
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Remaps]: remap directory: /storage/.config/retroarch/config/remappings
[INFO] [Remaps]: core-specific remap found at /storage/.config/retroarch/config/remappings/Mupen64Plus GLES2/Mupen64Plus GLES2.rmp.
[INFO] [Overrides]: Redirection du fichier de sauvegarde vers "/storage/.config/retroarch/saves/Mupen64Plus GLES2/Lylat Wars (Europe) (En,Fr,De).srm".
[INFO] [Overrides]: Redirection du fichier de sauvegarde instantanée vers "/storage/.config/retroarch/states/Mupen64Plus/Lylat Wars (Europe) (En,Fr,De).state".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [CONTENT LOAD]: Chargement du fichier de contenu: /storage/roms/n64/Lylat Wars (Europe) (En,Fr,De).n64.
[INFO] Impossible de trouver un patch valide pour ce contenu.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGLES2 context.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[libretro INFO] EmuThread: M64CMD_ROM_OPEN
[libretro INFO] mupen64plus: Goodname: Lylat Wars (E) (M3) [!]
[libretro INFO] mupen64plus: Name: STARFOX64           
[libretro INFO] mupen64plus: MD5: 884CCCA35CBEEDB8ED288326F9662100
[libretro INFO] mupen64plus: CRC: F4CBE92C B392ED12
[libretro INFO] mupen64plus: Imagetype: .v64 (byteswapped)
[libretro INFO] mupen64plus: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
[libretro INFO] mupen64plus: ClockRate = F
[libretro INFO] mupen64plus: Version: 1448
[libretro INFO] mupen64plus: Manufacturer: Nintendo
[libretro INFO] mupen64plus: Cartridge_ID: 5846
[libretro INFO] mupen64plus: Country: Europe (0x50)
[libretro INFO] mupen64plus: PC = 80000400
[libretro INFO] mupen64plus: Save type: 0
[libretro INFO] EmuThread: M64CMD_ROM_GET_HEADER
[INFO] [SRAM]: Chargement de la SRAM ignoré..
[INFO] Sauvegarde instantanée automatique trouvée dans: /storage/.config/retroarch/states/Mupen64Plus/Lylat Wars (Europe) (En,Fr,De).state.auto
Chargement auto d'une sauvegarde instantanée depuis "/storage/.config/retroarch/states/Mupen64Plus/Lylat Wars (Europe) (En,Fr,De).state.auto" succeeded.
[INFO] Version de l'API libretro: 1
[INFO] Compilé avec l'API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /tmp/database/cht/Mupen64Plus GLES2/Lylat Wars (Europe) (En,Fr,De).cht
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Timings deviate too much. Will not adjust. (Display = 60.00 Hz, Game = 50.00 Hz)
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [GL]: Found GL context: fbdev_mali
[INFO] [GL]: Detecting screen resolution 0x0.
[INFO] [EGL]: Current context: 0x40000001.
[INFO] [GL]: Vendor: ARM, Renderer: Mali-450 MP.
[INFO] [GL]: Version: OpenGL ES 2.0.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 1 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Initializing HW render (1024 x 1024).
[INFO] [GL]: Max texture size: 4096 px, renderbuffer size: 4096 px.
[INFO] [GL]: Supports FBO (render-to-texture).
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Pad #0 (/dev/input/event4) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event4) supports 16 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: null
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 512 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[INFO] Déconnexion du périphérique depuis le port 6.
[INFO] Déconnexion du périphérique depuis le port 7.
[INFO] Déconnexion du périphérique depuis le port 8.
[INFO] Déconnexion du périphérique depuis le port 9.
[INFO] Déconnexion du périphérique depuis le port 10.
[INFO] Déconnexion du périphérique depuis le port 11.
[INFO] Déconnexion du périphérique depuis le port 12.
[INFO] Déconnexion du périphérique depuis le port 13.
[INFO] Déconnexion du périphérique depuis le port 14.
[INFO] Déconnexion du périphérique depuis le port 15.
[INFO] Déconnexion du périphérique depuis le port 16.
[INFO] [Playlist]: Chargement du fichier d'historique: [/storage/.config/retroarch/content_history.lpl].
[INFO] [Playlist]: Chargement du fichier d'historique: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] [Playlist]: Chargement du fichier d'historique: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] [Playlist]: Chargement du fichier d'historique: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] [Playlist]: Chargement du fichier des favoris: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[libretro INFO] EmuThread: M64CMD_EXECUTE. 
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[INFO] [Environ]: SYSTEM_DIRECTORY: "/storage/roms/bios".
[libretro INFO] mupen64plus: Memory initialized
[libretro INFO] mupen64plus: Starting R4300 emulator: Dynamic Recompiler
[libretro INFO] mupen64plus: Init new dynarec
[libretro INFO] mupen64plus: ARM CPU Features:, Half, Thumb, FastMult, VFP, ESDP, NEON, VFPv3, TLS, VFPv4, IDIVa, IDIVt
[INFO] Chargement de la sauvegarde instantanée: "/storage/.config/retroarch/states/Mupen64Plus/Lylat Wars (Europe) (En,Fr,De).state.auto", Taille de la sauvegarde instantanée: 16789316 octets.
[INFO] Sauvegarde instantanée en cours: "RAM", Taille de la sauvegarde instantanée: 16789316 octets.
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: VSync => off
[INFO] [EGL]: eglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] Sauvegarde instantanée en cours: "/storage/.config/retroarch/states/Mupen64Plus/Lylat Wars (Europe) (En,Fr,De).state.auto", Taille de la sauvegarde instantanée: 16789316 octets.
[INFO] Sauvegarde instantanée automatique vers "/storage/.config/retroarch/states/Mupen64Plus/Lylat Wars (Europe) (En,Fr,De).state.auto" succeeded.
[INFO] [Overrides]: Configuration overrides unloaded, original configuration restored.
[INFO] [config] Nouvelle configuration enregistrée vers "/storage/.config/retroarch/retroarch.cfg".
[INFO] [Cheats]: Save game-specific cheatfile: /tmp/database/cht/Mupen64Plus GLES2/Lylat Wars (Europe) (En,Fr,De).cht
[INFO] [SRAM]: Enregistrement du type de RAM #0 vers "/storage/.config/retroarch/saves/Mupen64Plus GLES2/Lylat Wars (Europe) (En,Fr,De).srm".
[INFO] [SRAM]: Enregistré avec succès vers "/storage/.config/retroarch/saves/Mupen64Plus GLES2/Lylat Wars (Europe) (En,Fr,De).srm".
[INFO] Content ran for a total of: 00 hours, 00 minutes, 21 seconds.
[INFO] [CORE]: Unloading game..
[INFO] [CORE]: Unloading core..
[libretro INFO] mupen64plus: Stopping emulation.
[INFO] [PERF]: Performance counters (libretro):
[INFO] [CORE]: Unloading core symbols..
[INFO] [Core Options]: Saved game-specific core options to "/storage/.config/retroarch/config/Mupen64Plus GLES2/Lylat Wars (Europe) (En,Fr,De).opt"
[?12l[?25hcontext_reset.
plugin_start_gfx success.
exit 0`

**Comment by dm2912** [comment]
S905x with 1gb ram is really not enough to run N64 games

My 905w (same chip) would not handle it. My 905x3 (4gb ram) did but even that had struggles with some games.

**Comment by durstboiler** [comment]
Another very strange thing about the operation of the ram: in Mario Golf, by doing nothing other than turning on myself, the ram increases until the box freezes, as if the same textures were loaded indefinitely.

**Comment by shantigilbert** [comment]
> the management of the ram of the emulator.

If this is the case the issue should be opened in the github of the core, as we cannot fix such big problem. Or try another core

**Comment by durstboiler** [comment]
This is the same for all n64 cores, the only thing that slows down the ram filling is not using texture enhancement, but if I play for a long time it will inevitably happen.

**Comment by shantigilbert** [comment]
The this is an issue that should be reported to the core directly, there is nothing we can do about this in general, all I know is that people with 2gb or 4gb do not have this issue. 1gb is still not enough for EmuELEC.

**Comment by ricardoandren** [comment]
I have the same problem

**Comment by durstboiler** [comment]
I am doing some tests.
Already, you should know that there are games, at certain times when the textures are loaded as in an infinite loop.
For example, the Starfox 64 map, or the Mario golf game phase.
To make things better, in mupen64plus-next:
-MAX TEXTURE CACHE SIZE : 1500
This caps the loading of large textures, as I understand it.

-TEXTURE ENHANCEMENT : AS IS or NONE
Exemple (After reaching the cap.) Mario Golf : 
NONE: 476mo 
AS IS: 490mo
HQ2X: 587mo
2XBRZ: 650mo

-RESOLUTION : ~15-20mo saving by lowering it.
-NOISE EMULATION : OFF
~15-20mo saving.
