### ISSUE TITLE
I optimized the carbon theme for the Odroid Go Advance

### ISSUE THREAD

**Issue by mtoensing** [EmuELEC/EmuELEC#382]
I changed the font size to a more reasonable size and removed the description text and added the genre. Some logos got reworked for the small screen and I added the European snes logo. Maybe this is useful for someone? 

![odroid-go-advance-theme-emuelec-g2](https://user-images.githubusercontent.com/136737/103311696-5543a100-4a1b-11eb-97d3-47878dfff2a4.png)

https://github.com/mtoensing/es-theme-EmuELEC-carbon-odroid-go-advance

**Comment by shantigilbert** [comment]
Thanks I am sure someone will find it useful. 

Do you want me to add it to the theme downloader ?

**Comment by mtoensing** [comment]
If you tell me how I do that I would gladly add it.

**Comment by mtoensing** [comment]
Ah, o

**Comment by shantigilbert** [comment]
> 
> 
> Sorry, I misread the answer. Of course. Please do. How can I update it after that? Do I just push new commits into my repository?

Yes, the script pulls "master" branch. _

**Comment by mtoensing** [comment]
Perfect. Thank you. If I would like to change the displayed name of my theme? Is this the name of the repository? Can I change that and your scripts adapt that? 

![20201229221557463](https://user-images.githubusercontent.com/136737/103314556-c5562500-4a23-11eb-8260-23a7a9c78b39.jpg)

**Comment by shantigilbert** [comment]
In that case I have to change it, I usually put the name of the repo but in theory it could be anything

**Comment by mtoensing** [comment]
Ok, I will rename the repo and post the new url here. That was just a working title, but I would like to rename it if that is ok.
