### ISSUE TITLE
Wifi not recognized. A95X Amlogic A905X3

### ISSUE THREAD

**Issue by sszcze000** [EmuELEC/EmuELEC#385]
The box works with WIfi in Android mode, but when booting from SD card using sm1_s905x3_4g.dtb, my Wifi Network is not detected in the menu.  The box specs are below.  Thank you for any help.  Much appreciated

Brand: A95X
Type: TV Box
System: Android 5.1
CPU: Amlogic S905x3
Core: 2.0GHz,Cortex A53,Quad Core
RAM Type: DDR3
Max. Extended Capacity: TF card up to 32GB (not included)

Decoder Format: H.263,H.264,H.265,HD MPEG4
Video format: ASF,AVI,DAT,FLV,ISO,MKV,MOV,MPEG,MPG,RM,RMVB,TS,VOB,WMV
Audio format: AAC,AC3,APE,DDP,DTS,FLAC,HD,MP3,OGG,TrueHD,WAV,WMA
Photo Format: BMP,GIF,HD JPEG,PNG,TIFF
Support 5.1 Surround Sound Output: Yes

5G WiFi: YES
Power Supply: Charge Adapter
Interface: AV,DC 5V,HD,LAN,TF card,USB2.0
Language: Multi-language
DVD Support: Yes
HDMI Version: 2.0
Other Functions: 3D Games,3D Video,DLNA,Miracast,NTSC,PAL
External Subtitle Supported: Yes
HDMI Function: CEC,HDCP,HEC
RJ45 Port Speed: 100Mbps

System Bit: 64Bit

**Comment by shantigilbert** [comment]
Try latest test release: https://github.com/EmuELEC/EmuELEC-tests/releases/tag/4.0-TEST-01012021
