### ISSUE TITLE
CIFS/SAMBA Share broken in 4.0-TEST-01012021

### ISSUE THREAD

**Issue by Frisk-0** [EmuELEC/EmuELEC#389]
**Describe the bug**
I can't mount my NAS as CIFS/SAMBA share in 4.0-TEST-01012021

**Screenshots**
This is status of my mount in 3.9:
![3 9](https://user-images.githubusercontent.com/59013471/103553934-73435280-4eae-11eb-8784-734aa6347fda.jpg)

This is status of my mount in 4.0:
![4 0](https://user-images.githubusercontent.com/59013471/103553970-7fc7ab00-4eae-11eb-9cd6-b5a1b30adbf4.jpg)

I'm enabling exactly the same file and don't know what's going on

**EmuELEC version:**
4.0-TEST-01012021

**Device**
 - S922X 
 - Beelink
 - GT-KING
 - rev. A

**Additional context**
Thx for your help here

**Comment by shantigilbert** [comment]
This has been fixed in dev

https://github.com/EmuELEC/EmuELEC/commit/ca532cc296758a878b8e3cca35e56c475377c06e
