### ISSUE TITLE
Duckstation crash

### ISSUE THREAD

**Issue by panchaboy** [EmuELEC/EmuELEC#394]
im on emuelec 4.0 it has duckstation core for PSX games... bur every game crash.... any suggestions?
I'm supposed to have the bios but I don't know if they're the right ones.... I want to use duckstation because it has better graph performance

please help! ✌️

**Comment by SamuEDL** [comment]
Good Morning, Can you tell which version of emuelec you use? (Ng, oga or normal). And a log would also help us to find the error, if you do not know how to obtain it. 
Here is a guide: https://github.com/EmuELEC/EmuELEC/wiki

**Comment by shantigilbert** [comment]
Please use the issue template, pretty hard to help with no information

**Comment by 0kti** [comment]
I have the same - OGA

**Comment by shantigilbert** [comment]
Closing this, since no response, feel free to reopen with the required information.
