### ISSUE TITLE
Updating Cores

### ISSUE THREAD

**Issue by emutronic** [EmuELEC/EmuELEC#408]
im using Emuelec 4.0 (Test version) amlogic s905x3 4gb Ram 

I decided to manually update cores for the next 2 reasons 

1. n64 emulation is slower compared to version 3.9
2. All the other cores work more smoothly than version 3.9 but flycast core won't let me modify TEXTURE UPSCALING (xBRZ)...and some games the characters look very pixelated.. (at the time of putting 2x or any digit the game crashes, this does not happen with version 3.9)

so I decided to manually update the cores along with their info files... the cores are updated correctly but now all games crash

any suggestions???.... thanks

**Comment by shantigilbert** [comment]
Yeah, Don't update the cores.
