### ISSUE TITLE
EmuELEC support for the new ODROID-Go Super by Hardkernel?

### ISSUE THREAD

**Issue by Hedda** [EmuELEC/EmuELEC#411]
**Is your feature request related to a problem? Please describe.**

I would like to request EmuELEC support for the new ODROID-Go Super by Hardkernel?

Hardkernel 's new ODROID-Go Super has the same Rockchip RK3326 internals as ODROID-Go Advance but comes with larger 5-inch 16:9 (FWVGA) square-pixel aspect radio screen with 854 x 480 pixels resolution, a higher capacity battery, and the addition of a second analog joystick and dedicated volume buttons.

**Describe the solution you'd like**

Support for EmuELEC on ODROID-Go Super Rockchip RK3326 hardware, 854 x 480 resolution display, mappings for all buttons, digital D-pad, and analog joysticks.

**Describe alternatives you've considered**

**Additional context**

I do not own an ODROID-Go Super (OGS) or an ODROID-Go Advance (OGA) yet but am planning to buy an OGS when available.

**Comment by shantigilbert** [comment]
Emuelec already supports it on the test version
