### ISSUE TITLE
emuelec freezes at loading screen

### ISSUE THREAD

**Issue by kaderr09** [EmuELEC/EmuELEC#414]
i had a problem with the dtb file for x88 pro x 3 tv box amlogic franklin s905x3 ,and after trying many images i have found a dtb file that boots into emuelec and create partitions then a black screen for 120 seconds after that boots again and freezes at the emuelec loading page for ever 
any one has had the same experience before ?

![139360114_1017388825417119_6593781388733252460_n](https://user-images.githubusercontent.com/72406732/104835038-0d8a9980-58a4-11eb-96ec-d7915acabde4.jpg)

**Comment by shantigilbert** [comment]
Don't open another issue about this.
