### ISSUE TITLE
Shutdown System does not work, EmuElec reboots instead of shutdown

### ISSUE THREAD

**Issue by ivan-yu** [EmuELEC/EmuELEC#421]
**Describe the bug**
After playing any game on Arcade emulator, go back to main menu, shutdown system.  System reboots instead of shutdown.

**To Reproduce**
1. Play any game on Arcade emulator, MaMe2010 or any other emulator is fine.
2. Go back to main menu, select Main Menu / Quit / Shutdown System, system appears to have gone into shutdown, but in fact, it performs reboot instead of shutdown.

**Expected behavior**
System should shut down, not reboot.

**EmuELEC version:**
 - Version 3.9

**Device**
 - SOC: S922X CPU
 - Brand: Odroid
 - Model: N2+
 - Version 4G Ram
 - Odroid WiFi Module 5A
 - USB wireless dongles for GameSir T4 Pro controllers

**Additional context**
I have CorecElec 9.2.5 on eMMC, EmuElec 3.9 on microSD, PetitBoot 20201020 on SPI.  System is Odroid N2+.
I have two 2.4GHz USB wireless dongles for my two controllers for EmuElec.

**Comment by shantigilbert** [comment]
Is it a clean install or upgrade?

**Comment by ivan-yu** [comment]
It is a clean install, EmuELEC-Amlogic-ng.arm-3.9-Odroid_N2.img

**Comment by fabioL78** [comment]
I have the same setup with the latest 4.0 test, also have the same problem, only intermittently.

**Comment by ivan-yu** [comment]
If I simply start EmuElec and do not start any emulator at all, then choose shutdown immediately, it can shut down properly.

After running emulator then quit back out to main menu, and choose shutdown, then it will restart instead of shutdown.

I am suspecting whether it has something to do with USB dongle waking up the system, just a thought.

**Comment by dm2912** [comment]
> I am suspecting whether it has something to do with USB dongle waking up the system, just a thought.

or CEC

**Comment by shantigilbert** [comment]
Can anyone ssh to the device and type this:

```
systemctl stop emustation
small-cores enable
systemctl reboot
```
see if it reboots correctly? 

Then

```
systemctl stop emustation
small-cores enable
systemctl shutdown
```
see if it shutdowns correctly?

**Comment by ivan-yu** [comment]
It seems there is no file named small-cores

EmuELEC:~ # small-cores enable
-sh: small-cores: command not found

EmuELEC:~ # find / -name small*
/storage/.config/emulationstation/themes/es-theme-EmuELEC-carbon/art/systemsbk/smallbox.xml
/storage/.config/emulationstation/themes/es-theme-EmuELEC-carbon/art/systemsbk/smallscreen.xml
/storage/.config/emulationstation/themes/es-theme-EmuELEC-carbon/art/systemsbk/smallvideo.xml
/sys/module/di/parameters/small_local_mtn
/sys/module/di/parameters/small_local_mtn1
/usr/config/emulationstation/themes/es-theme-EmuELEC-carbon/art/systemsbk/smallbox.xml
/usr/config/emulationstation/themes/es-theme-EmuELEC-carbon/art/systemsbk/smallscreen.xml
/usr/config/emulationstation/themes/es-theme-EmuELEC-carbon/art/systemsbk/smallvideo.xml
/usr/share/mc/syntax/smalltalk.syntax
EmuELEC:~ #

**Comment by ivan-yu** [comment]
> > I am suspecting whether it has something to do with USB dongle waking up the system, just a thought.
> 
> or CEC

I did not turn off anything along the HDMI chain when I experience this issue, so in my case, it cannot be due to CEC

**Comment by shantigilbert** [comment]
Sorry the command should be `emuelec-utils small-cores enable`

**Comment by ivan-yu** [comment]
Reboot works

Shutdown does not.  `systemctl shutdown` gives unknown operation.
EmuELEC:~ # systemctl stop emustation
EmuELEC:~ # emuelec-utils small-cores enable
EmuELEC:~ # systemctl shutdown
Unknown operation shutdown.
EmuELEC:~ #

However, `systemctl poweroff` works

**Comment by ivan-yu** [comment]
I tested this on the new v4.0 (bug fix updated) release, this bug is still there.

**Comment by shantigilbert** [comment]
I have tested it on 4 N2 (2 regular, 2 N2+) and the bug is not here, so there must be something else going on.

**Comment by ivan-yu** [comment]
Did you play a game first, then go to back main menu, then shutdown?

If I immediately shutdown after emuelec boots up, it works.

If I play some game on MaME, then exit back to main menu, then shutdown, it reboots instead of shutdown.

Thanks again.

**Comment by shantigilbert** [comment]
Which version of MAME?

**Comment by ivan-yu** [comment]
mame2010

**Comment by shantigilbert** [comment]
You are right, after playing a game it will not power-off, I will check it, thanks for reporting

**Comment by Ulisses-Medeiros** [comment]
this has also happened to me using the PCSx-Rearmed 32bit, play a game and sometimes it Reboot instead of performing the shutdown

**Comment by shantigilbert** [comment]
@ivan-yu can you create a file

`/storage/.config/emulationstation/scripts/quit/quit.sh`

then type this in that file 

```
#!/bin/bash

case ${1} in
 "reboot")
    systemctl reboot 
 ;;
 "shutdown")
    systemctl poweroff
 ;;
esac
```

**Comment by ivan-yu** [comment]
There is no folder named quit, create that as well?  Make quit.sh +x ?

**Comment by shantigilbert** [comment]
yes, and yes

**Comment by ivan-yu** [comment]
Seems to be working!
