### ISSUE TITLE
Wifi/bluetooth don't works, EmuElec 3.9 

### ISSUE THREAD

**Issue by ferlosio** [EmuELEC/EmuELEC#429]
Hello,

I have one X96 max+ 4/32gb 2021 with new chip Cdtech4761743 (China Dragon Technology Limited http://www.cdtech.cn/en).

It works properly with Android, but there is no wifi and no bluetooth with EmuELEC 3.9.

Any solution for this?

Thank you for your great job !

**Comment by shantigilbert** [comment]
Duplicate https://github.com/EmuELEC/EmuELEC/issues/323
