### ISSUE TITLE
Q: Is it possible to use KERNEL from EMUElec-Image with Emuelec-Addon on "vanilla" CE-installation?

### ISSUE THREAD

**Issue by walterheisenberg** [EmuELEC/EmuELEC#430]
**Is your feature request related to a problem? Please describe.**
OpenBOR is not included in the addon-version because of a change in Kernel to make it work.
Was mentioned in CE-forums in EMUElec-section

**Describe the solution you'd like**
I'm asking, if I can copy the KERNEL file from EMUElec-Image to the default CoreELEC (Kodi19?) installation. Then I can update SYSTEM with normal CE-Images, then replace KERNEL and run OpenBOR ;)

**Describe alternatives you've considered**
Installation of EMUElec is not often updated as CE-images

**Additional context**
Maybe OpenBOR is running together with the new Kernel and Kodi19?

Thx for the answer

**Comment by shantigilbert** [comment]
Nope, Kodi will break, and I assume the only reason you want to do that is too have still be able to use Kodi.
