### ISSUE TITLE
The latest version of emuelec, ROMs game name can't use Chinese name?

### ISSUE THREAD

**Issue by ji125443** [EmuELEC/EmuELEC#431]
The name of the game can not be in Chinese, for example, (Ghana fighter.Nes，ES front-end will appear：????? .nes）?

**Comment by ji125443** [comment]
Online neighbors can't upload game files with Chinese names

**Comment by ji125443** [comment]
![P10209-174837](https://user-images.githubusercontent.com/25021120/107346779-0dc33100-6b00-11eb-873f-54fad4ae94df.jpg)
![Uploading P10209-174518.jpg…]()

**Comment by ji125443** [comment]
![Uploading P10209-174837.jpg…]()

**Comment by ji125443** [comment]
-
![P10209-174518](https://user-images.githubusercontent.com/25021120/107461142-55939800-6b94-11eb-89b8-545158cad3a1.jpg)
![P10209-174837](https://user-images.githubusercontent.com/25021120/107461192-7956de00-6b94-11eb-8183-3d1217c89c83.jpg)

**Comment by mavisguo** [comment]
4.1 bata ng version fixed, but no ng version do not work.

**Comment by SmartYou1995** [comment]
The garbled code of FAT32 file system with windows in Linux.The problem still exists，on 4.1.

**Comment by SmartYou1995** [comment]
Add - O utf8 = 1 when using mount command

**Comment by shantigilbert** [comment]
The release that fixes this is not even public yet, its v4.1 that is what fixed_in_dev  means and it needs a CLEAN (no update) install as it will needs to recreate the partitions

**Comment by SmartYou1995** [comment]
> The release that fixes this is not even public yet, its v4.1 that is what fixed_in_dev means and it needs a CLEAN (no update) install as it will needs to recreate the partitions

Looking forward to the next new version update

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/commit/674ec9cbf7c6dd9a88e83535eacf944a95102c6b

**Comment by ws02589111** [comment]
Thanks for yout update, after my test,  the ES front-end，ssh, samba is fixed， but the display in retroarch is not fixed.

EmuELEC version: latest dev branch: f5d53ae824b9e721b9d128ac74236f648d9699b9
SOC: S905M

To Reproduce
1.Default is English in retroarch, set it to cn, now you can see it display properly, but after you save the config and reboot, you can see the below:
![112121651-6f47e680-8bfa-11eb-9a1c-ba4e5cb751cd](https://user-images.githubusercontent.com/10301545/113127602-86ff1a80-924b-11eb-9fbd-49d995fe8db9.jpg)
2.And then , set it back to en, you can get the below:
![IMG_20210331_180525](https://user-images.githubusercontent.com/10301545/113128917-e578c880-924c-11eb-8e73-8c652d64c2b3.jpg)

**Comment by ws02589111** [comment]
> Thanks for yout update, after my test, the ES front-end，ssh, samba is fixed， but the display in retroarch is not fixed.
> 
> EmuELEC version: latest dev branch: [f5d53ae](https://github.com/EmuELEC/EmuELEC/commit/f5d53ae824b9e721b9d128ac74236f648d9699b9)
> SOC: S905M
> 
> To Reproduce
> 1.Default is English in retroarch, set it to cn, now you can see it display properly, but after you save the config and reboot, you can see the below(ignore time on the screen):
> ![112121651-6f47e680-8bfa-11eb-9a1c-ba4e5cb751cd](https://user-images.githubusercontent.com/10301545/113127602-86ff1a80-924b-11eb-9fbd-49d995fe8db9.jpg)
> 2.And then , set it back to en, you can get the below:
> ![IMG_20210331_180525](https://user-images.githubusercontent.com/10301545/113128917-e578c880-924c-11eb-8e73-8c652d64c2b3.jpg)

@shantigilbert any idea for this？

**Comment by ws02589111** [comment]
Set the retroarch theme to xmb and add the xmb_font = "/tmp/assets/xmb/monochrome/font.ttf"(the font i have replaced to yahei for test) to the retroarch.cfg, the problem in xmb is solved, but not work in ozone
