### ISSUE TITLE
EMUELEC not support new cpu s905x3-b ?

### ISSUE THREAD

**Issue by naios81** [EmuELEC/EmuELEC#434]
Hello.
I buy android tv box x96 max+ in aliexpress(4GB/32GB).
Install emuelec 3.9,but not work eithernet, wifi.
Those are work on android.
check the cpu infomation in emuelec.

cpu : amlogic unknown soc rev.b

Not support this cpu or this cpu is fake?
What is solution this problem?

thanks for advise.

**Comment by igyenes** [comment]
Which dtb do you use?

**Comment by naios81** [comment]
> Which dtb do you use?

Use  sm1_s905x3_4g.dtb or sm1_s905x3_4g_1gbit.dtb .
Do not work both.

**Comment by naios81** [comment]
Closing this, same problem #323 .
