### ISSUE TITLE
EmuELEC wont boot past initial screen

### ISSUE THREAD

**Issue by vegas4917** [EmuELEC/EmuELEC#435]
I tried changing the screen resolution to fit my cabinet screen and after restarting the system i get a black screen after the emuELEC splahscreen comes up. I'm using a T95 Max+android box. Is there a simple fix for this problem or will I have to reflash the image to my sd card??

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/wiki/Common-Questions#how-to-change-resolution-i-get-black-screen-or-my-tv-is-not-working-with-your-image
