### ISSUE TITLE
Cdtech 4761743 wifi chip information.

### ISSUE THREAD

**Issue by naios81** [EmuELEC/EmuELEC#436]
Hello.
I get the information for cdtech 4761743 chip.
It is same Qualcomm Atheros QCA6174.
please add that chip support.

- andriod tv box spec
product  name : vontar x96 max+ (called Q2)
cpu : amlogic s905x3
         (amlogic unknown rev.b in emuelec infomation)
ram : 4GB
lan : 1000 M
wifi & bluetooth : cdtech 4761743

thanks for your greate job.

**Comment by eric4gith** [comment]
Just noticed the post. I have the same device. 
ath10k driver should be available for Linux.
https://wireless.wiki.kernel.org/en/users/drivers/ath10k

Maybe it's time for me to start learning to compile a Linux kernel from source code.
