### ISSUE TITLE
amlogic  s905x No sound at pcsx_rearmed on v4.0-TEST-02022021

### ISSUE THREAD

**Issue by antiKot** [EmuELEC/EmuELEC#438]
Hello. There in no sound on pcsx_rearmed (system by default) on v4.0-TEST-02022021

**Comment by SamuEDL** [comment]
To find the problem, we need a log. Here you have info on how to get it: https://github.com/EmuELEC/EmuELEC/wiki

P.D: Please, to report bugs, use the predefined template for it.

**Comment by antiKot** [comment]
Sorry. Here is the logs: http://ix.io/2OtH

**Comment by antiKot** [comment]
The sound appears when I turn on **tinyalsa** audiodriver at RetroArch Drivers, but it creaks
