### ISSUE TITLE
EmuELEC 3.9 on OGA: Netplay error "A netplay peer is running a different core" but it's a cloned image and cores match.

### ISSUE THREAD

**Issue by mtoensing** [EmuELEC/EmuELEC#442]
Hi! 

I am pleased with my OGA with EmuELEC 3.9! A friend and colleague of mine just bought the same OGA. Same EmuELEC, same cores, same roms. 

We tried NES (Nestopia, BattleCity) and SNES (Mario Kart) with the same Roms, but we always get the message "A netplay peer is running a different core". The Mario Kart ROM is from the NoIntro set. 

We double-checked the cores and roms. See attached screenshots. The port is open. What could be the cause of this problem? I search in google and since October 2020, many people report this problem. Is there an easy fix? We used the default settings. 

![oga2](https://user-images.githubusercontent.com/136737/107145209-69df5700-6940-11eb-9207-28b2f3e5f86c.jpeg)
![oga1](https://user-images.githubusercontent.com/136737/107145211-6ba91a80-6940-11eb-9f31-6318ec8934ef.jpeg)

**Comment by shantigilbert** [comment]
Can you test v4.0 ?

**Comment by mtoensing** [comment]
I will. do I need to start netplay from the EmulationStation Menu or can I start it via RetroArch directly?

**Comment by mtoensing** [comment]
It's the same with 4.0. I have a Netplay session open with a relay server. But I can switch off relay because my ports are open on my OGA EmuELEC 4.0. SNES, Mario Kart, MarcTVde Maybe someone can try to connect right now?

**Comment by shantigilbert** [comment]
This should be fixed on v4.4 tested and working
