### ISSUE TITLE
How to play Colecovision?

### ISSUE THREAD

**Issue by roro582** [EmuELEC/EmuELEC#443]
Downloaded the bios, cores, and placed machine and database files in bios but MSX works but Colecovision does not how to change autostart/autodetection of the emulator to play Colecovision?

**Comment by shantigilbert** [comment]
Please reopen this issue following the proper template.

**Comment by roro582** [comment]
Should I place this under Pull requests?

**Comment by lethal-guitar** [comment]
@roro582 no, issues is correct. But there is some pre-inserted text when you open a new issue (that's called the issue template). Please read that and do what it says

**Comment by roro582** [comment]
> @roro582 no, issues is correct. But there is some pre-inserted text when you open a new issue (that's called the issue template). Please read that and do what it says

I understand thank you.
