### ISSUE TITLE
Colecovision Compatibility

### ISSUE THREAD

**Issue by roro582** [EmuELEC/EmuELEC#445]
I have downloaded the bios, cores, and placed machine and database files in bios and MSX games work using Blue MSX EMULATOR but Colecovision does not as I am unable to change autostart/autodetection of the emulator to play Colecovision.

**Comment by shantigilbert** [comment]
Please stop opening this issue without the proper information, I told you before you need to fill in the template! 

When you open the issue it will ask you want kind of issue it is, choose bug report and FILL OUT all the information asked, otherwise your request will be ignored again.
