### ISSUE TITLE
EmuELEC 4.0 on OGA : RetroAchievements can't be activated with passwords that contain special characters

### ISSUE THREAD

**Issue by mtoensing** [EmuELEC/EmuELEC#447]
I had a password containing a "%". This works on the website of https://retroachievements.org/ and on 3.9. The result is that the switch in "game settings" -> "RetroAchievements" is switch off after this error. And yes, It is connected to wifi and I can put roms on it via wifi and can connect via SSH. Something is broken with the escaping of the url for the API call.

![IMG_6773D](https://user-images.githubusercontent.com/136737/107355970-7abed280-6ad0-11eb-91bf-b76a21884723.JPG)

**Comment by mtoensing** [comment]
This error is a regression and special characters like "%" worked in 3.9 but not in 4.0

**Comment by TheLastProject** [comment]
Same with the & symbol in passwords, it worked in 3.9 fine.

**Comment by shantigilbert** [comment]
Confirmed

As a workaround: 

add the password directly to `/emuelec/emuelec.conf` but emulationstation needs to be stopped first 

ssh:
```
systemctl stop emustation
nano /emuelec/emuelec.conf
```
change the `global.retroachievements.password=` line and add your password (no escaping necessary)

this will be fixed on next release.
