### ISSUE TITLE
Overlays/bezels for seperate systems (idea)

### ISSUE THREAD

**Issue by Cee123** [EmuELEC/EmuELEC#451]
**Is your feature request related to a problem? Please describe.**
You can add a bezel/overlay for a system, but the same bezel then gets shared amongst multiple systems and games. So when you change a bezel/overlay for one particular system, it changes it to that bezel all systems.

**Describe the solution you'd like**
A way to customize and add a seperate bezel/overlay for each system.

**Describe alternatives you've considered**
Saving core overrides. Saving a new config. Saving game overrides (this works but you'd have to do it for each separate game and that would take forever)

**Additional context**
Previously I could do this with RetroPie and RetroArena/Ares since the configs for different systems are saved in seperate folders. I can take some screenshots and show what I mean.

It is just an idea, but is there any way to do this currently? Or is it something that would need to be implemented?

**Comment by Cee123** [comment]
Just an example of what I mean.. how I had it set out on retroarena. Is it possible to do this on EmuElec?

![20210211_102504-20210211-10304612](https://user-images.githubusercontent.com/43462099/107597011-6acffb80-6c54-11eb-863e-6852c7e54c3a.jpg)

![20210211_102554-20210211-103045274](https://user-images.githubusercontent.com/43462099/107597017-6efc1900-6c54-11eb-8913-33551a7f2ddf.jpg)

![20210211_102713-20210211-103046976](https://user-images.githubusercontent.com/43462099/107597024-715e7300-6c54-11eb-8b89-3cce6fe4c394.jpg)

![20210211_102758-20210211-103046342](https://user-images.githubusercontent.com/43462099/107597027-758a9080-6c54-11eb-83b4-fc0d2e2a0ab9.jpg)

![20210211_102906-20210211-103045631](https://user-images.githubusercontent.com/43462099/107597049-7c190800-6c54-11eb-8eec-8d30a2c8fd0b.jpg)

![20210211_102337-20210211-103046686](https://user-images.githubusercontent.com/43462099/107597060-820ee900-6c54-11eb-9974-b359b4d8c7e9.jpg)

**Comment by shantigilbert** [comment]
That is already possible https://github.com/EmuELEC/EmuELEC/wiki/Bezels-&-Splash-screens read the manual installation part, it can use a bezel per system, per game or globally

**Comment by Cee123** [comment]
> That is already possible https://github.com/EmuELEC/EmuELEC/wiki/Bezels-&-Splash-screens read the manual installation part, it can use a bezel per system, per game or globally

Ah, thanks for that. That's fantastic. Was looking around for that.

**Comment by Cee123** [comment]
That's awesome, I was going to ask about splash screens as well. But it didn't occur to me to read the manual. /facepalm. Thanks again!
