### ISSUE TITLE
Issue with drastic in emuelec 3.9

### ISSUE THREAD

**Issue by amdultra** [EmuELEC/EmuELEC#452]
Hello, i got an issue with drastic 2.5.0.4 in emuelec 3.9 in an M8S pro l /s912 Box.

The Menue and the screen when the menue is opened is OK also the pen is Displayed normally but the Screen ist full of vertical black lines.

Tried to reinstall but didnt Help.
Any ideas on how to solve that?

https://user-images.githubusercontent.com/78900597/107613963-aca77480-6c49-11eb-8edf-936d5d5e174b.jpg

Thanks

**Comment by shantigilbert** [comment]
Drastic does not work on S912
