### ISSUE TITLE
Configure Reicast script stalls

### ISSUE THREAD

**Issue by emuchicken** [EmuELEC/EmuELEC#458]
**Describe the bug**
Choosing the Configure Reicast in the scripts menu stalls upon *please wait* - left it for an hour

**To Reproduce**
1. Go to settings
2. Click on Configure Reicast
3. Stalls on *please wait*

**Expected behavior**
To configure Reicast

**Screenshots**
... Not really needed

**EmuELEC version:**
4.0

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
Amlogic s905x 1GB RAM

**Additional context**

**Comment by shantigilbert** [comment]
Reicast is not intalled anymore, that script was left by mistake.
