### ISSUE TITLE
EmuELEC 4.0 on OGA : Wifi lost after power button hibernation

### ISSUE THREAD

**Issue by soimy** [EmuELEC/EmuELEC#460]
**Describe the bug**
Running EmuELEC 4.0 on OGA, connecting a working Mercury USB WIFI dongle. On power-on everything works flawlessly, but once I push the power button to hibernate the system and turned on again, I lost my wifi connection and no way to restore unless a system reboot.

**Comment by shantigilbert** [comment]
Please follow the issue templates,. I have no idea what a "Mercury USB WIFI dongle" uses, and I have no idea what version of the OGA you are using
