### ISSUE TITLE
[OGABE] The terminal cannot be closed.

### ISSUE THREAD

**Issue by british-choi** [EmuELEC/EmuELEC#464]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

**Describe the bug**
I cannot finish the terminal (setup scripts - 13 Launch Terminal)

**To Reproduce**
1. Go to 'Setup scripts'
2. Click on '13 - Launch Terminal'
3. Hot key (F1) + Start (F6) (for finishing terminal)
4. None

**Expected behavior**
Terminal is finished and showing previous screen

**Screenshots**

**EmuELEC version:**
 - Version 4.0

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: RK3326
 - Brand: Hardkernel
 - Model OGA BE
 - Version 1.1

**Additional context**
z_getkillkeys.sh
OGA (v1.0) gamepad is selected
OGA BE(v1.1) gamepad should be selected

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/463
