### ISSUE TITLE
Emuelec 4.0  The Mistaken Code Bug

### ISSUE THREAD

**Issue by qacjava** [EmuELEC/EmuELEC#466]
Hello!Thank you for update Emuelec 4.0 for S905.
When I use CN name game ROM in Emuelec 3.9 , it is very perfect！
But when I update Emuelec 4.0，All CN name games in My ROM  have many the Mistaken Code.
I try to replaced the 3.9 file in this path, but it didn't work .The Mistaken Code Bug  is still exists .
The File Path：
 "storage\config\emuelec\configs\locale\zh_CN"   
 "storage\config\emuelec\configs\locale\zh_CN.UTF8"   

pls, Help!

**Comment by shantigilbert** [comment]
duplicate https://github.com/EmuELEC/EmuELEC/issues/431
