### ISSUE TITLE
EmuELEC 4.0 on OGA: Brightness is not saved across reboots

### ISSUE THREAD

**Issue by miwasp** [EmuELEC/EmuELEC#470]
**Describe the bug**
No matter what value is set for brightness, it is reset to something different after reboot

**To Reproduce**
1. Go to 'Main menu' (F6)
2. Click on 'System settings'
3. Set brightness to e.g. 81%
4. Reboot
5. Brightness is set back to 31% (in my case)

**Expected behavior**
Brightness should be saved across reboots

**EmuELEC version:**
 - Version 4.0

**Device**
 - Odroid Go Advance Black Edition

**Comment by shantigilbert** [comment]
If you set brightness via the hotkey, does it also happen ?

**Comment by miwasp** [comment]
In short: Yes

If i change brightness via hotkey, this change can be seen in the system settings. So it makes no difference if you change brightness via hotkey or menu.
The current value is correctly saved in emuelec.conf, but for some reason another value is set after reboot or even after standby.

**Comment by shantigilbert** [comment]
Ok thanks, I will look into it.

**Comment by miwasp** [comment]
The problem is the different range of "brightness.level" in emuelec.conf (0..100) and "/sys/class/backlight/backlight/brightness" (0..255).

This works so far for me on my OGA, no idea if it works for other devices:

> $ diff /storage/.config/emuelec/scripts/odroidgoa_utils.sh.org /storage/.config/emuelec/scripts/odroidgoa_utils.sh
63,65c63,66
< STEPS="20"
< CURRENTBRIGHT=$(cat /sys/class/backlight/backlight/brightness)
< MAXBRIGHT="255" #$(cat /sys/class/backlight/backlight/max_brightness)
<---
\> STEPS="5"
\> CURBRIGHT=$(cat /sys/class/backlight/backlight/brightness)
\> CURRENTBRIGHT=$(($CURBRIGHT*100/255))
\> MAXBRIGHT="100"
77,78c78,80
< 	echo "${STEPBRIGHT}" > /sys/class/backlight/backlight/brightness
< 	set_ee_setting "brightness.level" $(cat /sys/class/backlight/backlight/brightness)
<---
\> 	NEWVAL=$(($STEPBRIGHT*255/100))
\> 	echo "${NEWVAL}" > /sys/class/backlight/backlight/brightness
\> 	set_ee_setting "brightness.level" $STEPBRIGHT

**Comment by shantigilbert** [comment]
Thank you, I will test it out

**Comment by shantigilbert** [comment]
I don't understand this part 

```
 	NEWVAL=$(($STEPBRIGHT*255/100))
 	echo "${NEWVAL}" > /sys/class/backlight/backlight/brightness
 	set_ee_setting "brightness.level" $STEPBRIGHT
```

you set one value to the /sys/class, but another to the .conf file? and his works?

**Comment by shantigilbert** [comment]
Ok I guess it does, since the value gets converted directly. Thanks for the fix I will push it

**Comment by miwasp** [comment]
This works on my OGA.
Today i got my OGS. On OGS i can change the value with the hotkeys and i can see the change in the menu. I can even go to standby and switch it on again and still have the correct value of brightness. But if i restart the OGS, brightness is always 50 and i don‘t know where this is set.

**Comment by shantigilbert** [comment]
its set here

```
set_ee_setting "brightness.level" $STEPBRIGHT
```
and its saved on `/emuelec/configs/emuelec.conf`

**Comment by miwasp** [comment]
max_brightness on OGA is 255 and i mistakenly assumed it is 255 on all devices.
But max_brightness on OGS is 160!
This works for both OGA and OGS:

>if [ "${1}" == "bright" ]; then
STEPS="5"
CURBRIGHT=$(cat /sys/class/backlight/backlight/brightness)
MAXSYSBRIGHT=$(cat /sys/class/backlight/backlight/max_brightness)
CURRENTBRIGHT=$(($CURBRIGHT*100/$MAXSYSBRIGHT))
MAXBRIGHT="100"
MINBRIGHT="2"
        if [ "${2}" == "+" ]; then
                STEPBRIGHT=$(($CURRENTBRIGHT+$STEPS))
        elif [ "${2}" == "-" ]; then
                STEPBRIGHT=$(($CURRENTBRIGHT-$STEPS))
        else
                STEPBRIGHT=${2}
        fi
        [ "$STEPBRIGHT" -ge "$MAXBRIGHT" ] && STEPBRIGHT="$MAXBRIGHT"
        [ "$STEPBRIGHT" -le "$MINBRIGHT" ] && STEPBRIGHT="$MINBRIGHT"
        #echo "Setting bright to $STEPBRIGHT"
        NEWVAL=$(($STEPBRIGHT*$MAXSYSBRIGHT/100))
        echo "${NEWVAL}" > /sys/class/backlight/backlight/brightness
        set_ee_setting "brightness.level" $STEPBRIGHT
fi

**Comment by shantigilbert** [comment]
Thank you!

**Comment by shantigilbert** [comment]
If you wish you can open a PR, or I can push the fix, let me know.

**Comment by miwasp** [comment]
Please push the fix...
