### ISSUE TITLE
EmuELEC 4.0 on Odroid Super : Issue with RetroAchevements password in RetroArch when using ee_defaults.txt

### ISSUE THREAD

**Issue by Desani** [EmuELEC/EmuELEC#475]
**Describe the bug**
I am using the ee_defaults.txt file to store login information for RetroAchievements 

In Emuelec menu's, RetroAchievements work fine. I click on RetroAchievements on the Emuelec screen, it logs in without issue and I can see my achievements

In each game I launch through retroarch gives me the following error:

RetroAchievements: Error with login. Please try again.

I think I found the culprit for the Retroarch RA error. When looking into the retroarch.cfg, at the cheevos_password = field, it looks like it inserts a new line character at the end of the password. So it is attempting to authenticate with a password with a new line character inserted.

**To Reproduce**
1. Create ee_defaults.txt with values for wifi and retroachievements 
2. Copy to the root of the boot partition
3. Validate that it has picked up the login info for retroachievements by testing the Emuelec menu
4. Start a game with achievements and validate the error with being able to login

**Expected behavior**
The same password that is supplied in the ee_defaults.txt file to be used to the login for retroarch retroachevements without the additional new line character on the end.

**EmuELEC version:**
 - 4.0 release

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - Brand: Odroid
 - Model: Super

**Comment by shantigilbert** [comment]
Yes this has been fixed in dev. meanwhile use a text editor that uses Linux end lines and make sure you have no spaces at the end of the passwords.

**Comment by Desani** [comment]
Okay sounds good. I was just reviewing the known bugs for 4.0 release and I did not see it mentioned, so I thought I would open a bug report.

Thanks for the fix.
