### ISSUE TITLE
Emuelec 4.0 s905x3 4gb ram scraper not working!!

### ISSUE THREAD

**Issue by Destes099** [EmuELEC/EmuELEC#479]
I downloaded the new 4.0 software. I reinstalled all of my ROMs. Everything was going smoothly and good still trying to add additional ROMs to complete my collection. When I go install a new rom I then click the select button go down to game options then I go down to scrape it pulls up two different box arts. I then go to select the one that I want. Then it takes me back out to the screen where you select the games. But there is no box art. If you go back in and look at the game's metadata it shows all the info in there but no box art. Please fix!!!!

**Comment by dm2912** [comment]
reload gamelists after scraping

main menu > game settings > update game lists

**Comment by Destes099** [comment]
I tried that. Doesn't do anything.

**Comment by Destes099** [comment]
I even tried restarting the whole system and box. But it still does nothing. On version 3.9 all I had to do was scrape it would pull up the box art then I would push save at the bottom and voila it was on there.

**Comment by Destes099** [comment]
![16137029273842204964508137848215](https://user-images.githubusercontent.com/79292857/108450391-bf621080-722a-11eb-97f8-c01219079a4d.jpg)

**Comment by Destes099** [comment]
![16137030540586211527451688689049](https://user-images.githubusercontent.com/79292857/108450551-0cde7d80-722b-11eb-9553-d3623d864ea3.jpg)

AFTER PUSHING ACCEPT RESULTS

**Comment by Destes099** [comment]
![16137031504081618829830087797701](https://user-images.githubusercontent.com/79292857/108450702-40210c80-722b-11eb-9b2f-b6c2a59cfe65.jpg)

And once again after updating games list.

**Comment by Destes099** [comment]
![1613703311159296910320240865399](https://user-images.githubusercontent.com/79292857/108450976-a443d080-722b-11eb-8a0b-5fe96a911dec.jpg)
All the information is filled in after scraping.

**Comment by Destes099** [comment]
But no box art!!

**Comment by Destes099** [comment]
Also whenever I have the previous game aren't set to show a little preview of the game. None of them are showing so when I go into the metadata and select the box art for the preview it will show. Then when when I update games list it then takes the previews away.

**Comment by dm2912** [comment]
it literally says on your screenshot that it does not have a logo/box/titleshot so there is nothing to show. If the box doesnt exist it cannae show it

what do you have for scraper settings? Do you have all those sources enabled?

Are you logged in to a screenscraper account?

Also, screenscraper put out an announcement last night that they were having issues

![image](https://user-images.githubusercontent.com/25871666/108521514-b4a78a00-72c3-11eb-9f62-d9af51de6194.png)

**Comment by Destes099** [comment]
All the other games that I have that have box arts on them and they dont have anything in the logo/box/titleshot. Also I do not have a login to screen scraper as I did not on the last version and it worked just fine. Also they added two new box art collectors on this version. But they are not working also.

**Comment by Destes099** [comment]
Also I was able to add box art manually before as well and now this is what it says when I try to do that

**Comment by Destes099** [comment]
![Uploading 16137746595383106660752932589327.jpg…]()

**Comment by Destes099** [comment]
![16137768710611165281292566076530](https://user-images.githubusercontent.com/79292857/108571965-e5dd8580-72d6-11eb-871e-bfed68fdcd79.jpg)

**Comment by Destes099** [comment]
It says the disk write is protected.

**Comment by dm2912** [comment]
> All the other games that I have that have box arts on them and they dont have anything in the logo/box/titleshot. Also I do not have a login to screen scraper as I did not on the last version and it worked just fine. Also they added two new box art collectors on this version. But they are not working also.

its not version related, screenscraper closed their API in late december to members only, they only reopened it today or so. 




> It says the disk write is protected.

that generally happens when you have access the storage and not done a safe eject - so either you took it out of your computer without ejecting it (linux) or clicking safely remove (windows) - or you shut down your box by hard reset, ie turning the power off. That causes partitions to lock themselves as read only.

Put the storage back in your device, reboot properly a few times via the menu and eventually the read only should lift.

**Comment by dm2912** [comment]
> All the other games that I have that have box arts on them and they dont have anything in the logo/box/titleshot. Also I do not have a login to screen scraper as I did not on the last version and it worked just fine. Also they added two new box art collectors on this version. But they are not working also.

if they dont have anything for boxart in the metadata they 100% cannot display a boxart. thats simply impossible

what is likely is that you downloaded box art to "image" rather than boxart.. and changed the scraper settings.

I did ask what your scraper settings were

**Comment by dm2912** [comment]
> ![1613703311159296910320240865399](https://user-images.githubusercontent.com/79292857/108450976-a443d080-722b-11eb-8a0b-5fe96a911dec.jpg)
> All the information is filled in after scraping.

no it isnt. logo, box and title shot are not filled in.

**Comment by Destes099** [comment]
The desk lock went away and for whatever reason the screen scraper just started working. Screenshot I sent to you was accessing ROMs over IP address.

**Comment by dm2912** [comment]
> The desk lock went away and for whatever reason the screen scraper just started working. Screenshot I sent to you was accessing ROMs over IP address.

if the drive was locked that is why the scraper could not download and add the artwork.

if a drive becomes locked its 99/100 because

a) the device was hard reset or shut down direct at the power point.; linux especially likes to mount and unmount drives properly, if you shut down without unmounting for whatever reason the drive will lock as read only because it things its mounted by another system

b) the usb or card being removed from a windows (or linux) machine without doing the safely eject removable media routine. again, it leads the drive to believe its still mounted so prevents further access

a few proper reboots usually sorts it out. it went away for whatever reason presumably because you either rebooted or did a safe unmount.
