### ISSUE TITLE
Any chance to include ECWolf?

### ISSUE THREAD

**Issue by miwasp** [EmuELEC/EmuELEC#480]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Any chance to include ECWolf? It is a port of the Wolfenstein 3D engine based of Wolf4SDL.
Source can be found here: https://bitbucket.org/ecwolf/ecwolf/src/master/
I just saw there is also a libretro port, but i haven't tested it yet: https://github.com/libretro/ecwolf

**Describe alternatives you've considered**
None

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/commit/f0aac2db4bedb3b8e07d236bd38b77a57ce51cb2
