### ISSUE TITLE
EmuELEC 4.0 on Odroid Go Advance 1.0：can not CPU Overclock

### ISSUE THREAD

**Issue by lancherliu** [EmuELEC/EmuELEC#487]
Describe the bug
can not CPU Overclock

To Reproduce
1. Go to 'EMUELEC SETTINGS'-'DANGER ZONE'-
2. Click on 'OVERCLOCK'
3. Set  'OVERCLOCK' to 1.5GHZ
4. In SSH the CPU stats CPU Freq  is also 1296000

Screenshots
![image](https://user-images.githubusercontent.com/77196551/108626048-2d0b7800-7489-11eb-8a3e-a7b14f226a75.png)
![image](https://user-images.githubusercontent.com/77196551/108626054-372d7680-7489-11eb-91f3-6238cbe59d0e.png)

**EmuELEC version:**
 - Version 4.0

Device
Odroid Go Advance 1.0

**Comment by shantigilbert** [comment]
This has been fixed on v4.1 test/beta

* Fixed issue with OGA/S OC not beeing applied correctly (this does not solve the random lockups on some devices)

**Comment by Lyteral** [comment]
From what I can tell, the Overclock on Odroid Go Advance 1.0 is still not applied on most current version 4.3-TEST

![image](https://user-images.githubusercontent.com/50910144/131494172-10c4442c-5483-4601-bd3a-b05d34c22593.png)
 
Was set up via UI to 1.4 GHz
