### ISSUE TITLE
Movie Player has no functions (Pause/Skip/ect.) on OGS with EmuELEC 4.0 / 4.1-beta

### ISSUE THREAD

**Issue by MicJeRon** [EmuELEC/EmuELEC#488]
Hi.
I have a Odroid-Go-Super with a fresh install of EmuElec 4.0.
The movie-player ist working. But there are no functions available such as pause / play / skipping forward or backward.
Only volume-keys are working and "hotkey+start" quits the movie.
I updated to 4.1-beta but the same there.

Regards

**Comment by shantigilbert** [comment]
Known problem, no solution yet

**Comment by shantigilbert** [comment]
fixed for next release https://github.com/EmuELEC/EmuELEC/commit/b0c182d9e2cc156385d020becdf8152519b01b7f
