### ISSUE TITLE
EmuELEC 4.0 - DraStic settings

### ISSUE THREAD

**Issue by Owtinho** [EmuELEC/EmuELEC#490]
Hello, 
I installed the new version from EmuELEC and everything work fine. But I don't know how I can change the settings from DraStic for the key assignment or that I see only one screen and not both at the same time.

Thank you for an answer.

**Comment by AlienatedDiego** [comment]
Please follow the template or provide the minimum necessary information of the device and version of EmuELEC

**Comment by AlienatedDiego** [comment]
Drastic by default is configured to display both screens as in the original system. Where did you get that Emuelec 4.0?

**Comment by Owtinho** [comment]
I installed it on my rk2020. I tried all the buttons to get into the menu without success. I found out that I can close the game with start and select.

**Comment by SamuEDL** [comment]
We do not support rk2020.

**Comment by Owtinho** [comment]
That's sad. Maybe it is possible to change the button layout in a file?
