### ISSUE TITLE
Cannot access Amiberry setup/settings on OGA/OGS

### ISSUE THREAD

**Issue by M1L0S-R5** [EmuELEC/EmuELEC#491]
**Describe the bug**
Cannot access Amiberry setup/settings screen on OGA/OGS. I have tested all possible key combinations on both devices but I cannot find right one. Entering setup is necessary because of e.g. save states in Amiberry.

**To Reproduce**
Start any game in Amiberry and try to access settings screen.  Tested only with LHA WHD games.

**Expected behavior**
Enter Amiberry settings screen by pressing correct key combination

**EmuELEC version:**
 - 4.0 final and 4.1. test

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE]
OGA 1.0 and OGS

**Additional context**

**Comment by shantigilbert** [comment]
Second bottom left button + x
