### ISSUE TITLE
ROMS USB/SD-media ver 4.0 4.1

### ISSUE THREAD

**Issue by Djglitch2011** [EmuELEC/EmuELEC#492]
На новой версии 4.0 ,4.1 перестала работать функция ромы с SD/usb носителей по данной инструкции ничего не работает
https://github.com/EmuELEC/EmuELEC/wiki/ROMS-on-USB-media
В версии 3.9 все работает. Как включить в 4.0 и 4.1 данную функцию?
Для чего мне это нужно.
Я добавил в прошивку TV BOX второй системой вместо CoreElec==>EmuElec
И 2го раздела у меня нет с EEROMS.

Заранее прошу извинить за мой английский.

On the new version 4.0, 4.1, the function of ROMs from SD / usb media stopped working according to this instruction, nothing works
https://github.com/EmuELEC/EmuELEC/wiki/ROMS-on-USB-media
Everything works in version 3.9. How to enable function in 4.0 and 4.1?
Why do I need this.
I added a second system to the TV BOX firmware instead of CoreElec ==> EmuElec
And I don't have the 2nd section with EEROMS.

I apologize in advance for my english.

**Comment by shantigilbert** [comment]
I use this function all the time, and it is still working, I have no idea what you are doing or how you are setting up, but please reopen this issue and follow a proper template.
