### ISSUE TITLE
Game shortcuts

### ISSUE THREAD

**Issue by durstboiler** [EmuELEC/EmuELEC#493]
Sorry to post here, but I was unable to write a message on Discord.

**Is your feature request related to a problem? Please describe.**
I cannot create several configuration (widescreen, test, HD ect) for the same N64 games, without duplicating the rom.

**Describe the solution you'd like**
I would like to be able to create game shortcuts to have multiple configurations for the same game. It works with m3u on PSX and DC, but not for N64. 

**Describe alternatives you've considered**
I found several commands in the Emuelec folders, but I don't know how to set them up.

`/usr/bin/retroarch -v -L /tmp/cores/flycast_libretro.so --config /storage/.config/retroarch/retroarch.cfg /storage/roms/dreamcast/Dino Crisis.chd`

`<command>/emuelec/scripts/emuelecRunEmu.sh %ROM% -P%SYSTEM% --core=%CORE% --emulator=%EMULATOR% --controllers="%CONTROLLERSCONFIG%"</command>`

**Additional context**
...

**Comment by dm2912** [comment]
i think i know what you mean, i guess you could create simlinks

so if you have mario_kart.n64

you could create mario_kart2.n64 as a simlink to the first, but im not sure how drive space would be reported.. i think it would still treat the linked file as the same size as the original

**Comment by shantigilbert** [comment]
As is I think this is currently not possible, not without copying the ROMS

**Comment by shantigilbert** [comment]
As is I think this is currently not possible, not without copying the ROMS
