### ISSUE TITLE
FAILURE: scripts/install PPSSPPSDL has failed!

### ISSUE THREAD

**Issue by dovart** [EmuELEC/EmuELEC#495]
Can't build EmuELEC dev branch.

The issue is with the PPSSPPSDL and libpng.

-- Could NOT find PNG: Found unsuitable version "1.6.36", but required is at least "1.7" (found /EmuELEC/build.EmuELEC-Amlogic.aarch64-4.0/toolchain/aarch64-libreelec-linux-gnueabi/sysroot/usr/lib/libpng.so)
CMake Error: File /EmuELEC/build.EmuELEC-Amlogic.aarch64-4.0/PPSSPPSDL-39198b53a521ae7d8031303173b1b12164659017/ext/miniupnp/miniupnpc/miniupnpcstrings.h.cmake does not exist.
CMake Error at CMakeLists.txt:1894 (configure_file):
  configure_file Problem configuring file

**Comment by shantigilbert** [comment]
Read the error "Could NOT find PNG: Found unsuitable version "1.6.36", but required is at least "1.7"

**Comment by shantigilbert** [comment]
update this package: https://github.com/EmuELEC/EmuELEC/blob/dev/packages/graphics/libpng/package.mk

**Comment by ws02589111** [comment]
-- Found PNG: /home/liwx/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.0/toolchain/aarch64-libreelec-linux-gnueabi/sysroot/usr/lib/libpng.so (found suitable version "1.7.0beta89", minimum required is "1.7") 
CMake Error: File /home/liwx/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.0/PPSSPPSDL-39198b53a521ae7d8031303173b1b12164659017/ext/miniupnp/miniupnpc/miniupnpcstrings.h.cmake does not exist.


The libpng 1.7 version is only found beta，the version check can not pass

**Comment by ws02589111** [comment]
The issue  maybe relate to https://github.com/hrydgard/ppsspp/pull/12748

**Comment by miwasp** [comment]
I just made a complete fresh clone, checkout and make of dev and get exactly this error.
The package.mk of libpng loads the latest stable version 1.6.37 but PPSSPPSDL somehow wants version 1.7.

Additionally there are two versions of libpng in the build directory, the above mentioned 1.6.37 and another one with version 1.6.36?

**Comment by miwasp** [comment]
I did it all again from scratch and now it compiled!?
I don't know what went wrong last time.

**Comment by ws02589111** [comment]
@shantigilbert 
Any suggestion？

**Comment by ws02589111** [comment]
> I did it all again from scratch and now it compiled!?
> I don't know what went wrong last time.

what branch you compiled?  dev？

**Comment by miwasp** [comment]
> what branch you compiled? dev？
Yes, i compiled dev. In the meantime i did it again from scratch and it worked again.

**Comment by ws02589111** [comment]
> > what branch you compiled? dev？
> 
> Yes, i compiled dev. In the meantime i did it again from scratch and it worked again.

Finally， I reinstalled my system to solved the problem，I don't know why after `make clean`  to run `make image` is no use
