### ISSUE TITLE
Generic x86-64 build error

### ISSUE THREAD

**Issue by ut-slayer** [EmuELEC/EmuELEC#496]
Hi i am trying build for x86-64 image and i get this 

Traceback (most recent call last):
  File "scripts/genbuildplan.py", line 365, in <module>
    REQUIRED_PKGS = processPackages(args, ALL_PACKAGES, args.build)
  File "scripts/genbuildplan.py", line 291, in processPackages
    raise Exception(msg)
Exception: Invalid package reference: dependency Generic in package oem::PKG_DEPENDS_TARGET is not valid
Parallel build failure - see log for details. Time of failure: Fri Feb 26 15:21:13 CET 2021
make: *** [Makefile:12: image] Error 1

 I dont know what is it happend. Anybody can help me? 
I am in ubuntu 20.10 thanks.

**Comment by shantigilbert** [comment]
There is no support for x86, only Amlogic chipsets
