### ISSUE TITLE
No sound on X96 Max+ S905x3 with Emuelec 4.0

### ISSUE THREAD

**Issue by durstboiler** [EmuELEC/EmuELEC#505]
**Describe the bug**
No sound on emulationstation, retroarch or PPSSPP, HDMI or AV.

**Expected behavior**
I don't have any sound anywhere. The games work but without sound.

**EmuELEC version:**
v4.0

****Device :**
 - SOC: S905x3
 - Brand: OTT TV BOX
 - Model X96 Max+
 - Version 2g 16g
 - sm1_s905x3_2g.dtb

**Steps to reproduce :**
-I turn on the box
-I'm going to the play list.
-I launch a game

**Comment by shantigilbert** [comment]
Steps to reproduce?

**Comment by durstboiler** [comment]
In the emuelec log I saw a line with an audio driver initialization problem. But this line is no longer displayed ...

**Comment by shantigilbert** [comment]
Well... if you changed the audio driver, what do you expect to happen? please reproduce this on a clean image, as I cannot reproduce this, all the games have no problems with sound.

**Comment by durstboiler** [comment]
But you can imagine that I changed the audio driver because it was not already working ...

**Comment by shantigilbert** [comment]
No, I could not, since you did not mentioned that. and Like I said I cannot reproduce this, so try with a clean image

**Comment by durstboiler** [comment]
I reinstalled emuelec v4, very clean image, same result, no sound. I have tried the other dtb S905x3 but only the one mentioned above works.

**Comment by shantigilbert** [comment]
are you using HDMI?

**Comment by durstboiler** [comment]
Yes ! Big thanks. I hadn't seen this option, sorry.

**Comment by shantigilbert** [comment]
> Yes ! Big thanks. I hadn't seen this option, sorry.

is it working now? what option worked for you?

**Comment by durstboiler** [comment]
Yes it working, it's Audio 0.1.
