### ISSUE TITLE
Custom collection problem when setting Korean

### ISSUE THREAD

**Issue by gamsija** [EmuELEC/EmuELEC#506]
**problem ==>** Infinite loading occurs when setting custom collection

**Update Language File**
Update with attachment ==> /emuelec/configs/locale/ko/LC_MESSAGES
[emuelec-locale-ko-patch-main.zip](https://github.com/EmuELEC/EmuELEC/files/6088901/emuelec-locale-ko-patch-main.zip)

**Comment by Langerz82** [comment]
@gamsija Is this still an issue with the latest revision? It's been awhile try the latest EE version 4.7 and let us know if it's still a problem.
