### ISSUE TITLE
Unnable to configure Dolphin Controls

### ISSUE THREAD

**Issue by mrabssalom** [EmuELEC/EmuELEC#509]
While loading a gamecube game, it started but you cannot do anything. Also (as i guess the emulator is an standalone version that doesnt load retroach) it doesnt recognyze any of the shotcuts... So basically i am stuck unnable to do anything or configure anything with no other option that reset the tvbox.

TV BOX Beelink Gt-King
Amlogic s922x
It happen in Emuelec 4.0 and test versions.

**Comment by shantigilbert** [comment]
Did you read the release notes on V4.0?

**Comment by shantigilbert** [comment]
`Dolphin has been added to the Amlogic-ng devices, but it is only really playable on S922x devices and gamepad stills needs to be set manually. Will fix this on v4.1`
