### ISSUE TITLE
How to use the Dolphin emulator?

### ISSUE THREAD

**Issue by durstboiler** [EmuELEC/EmuELEC#510]
I downloaded the dolphin pack from retroarch, I now have a Dolphin folder in the folder
roms / download
but I do not know where to place the roms?
Thanks.

**Comment by SamuEDL** [comment]
If you talk about the dolphin that comes in EmuELEC 4.x. The roms are put in EEROMS/wii and EEROMS/gamecube.

P.D: EEROMS is the partition where the roms are.

**Comment by durstboiler** [comment]
roms/wii 
roms /gamecube
Simply.
