### ISSUE TITLE
Cannot save retroarch config for onscreen notification - "show fps"

### ISSUE THREAD

**Issue by emuchicken** [EmuELEC/EmuELEC#511]
**Describe the bug**
Retroarch menu / Show FPS does not save to the configuration on next load of any game.

**To Reproduce**
1. Load any game
2. Enter Retroarch menu, turn on showfps in onscreen notifications
3. save configuration (I think it should on exit anyways)
4. re-enter game

**Expected behavior**
FPS should be displayed

**Screenshots**
No need

**EmuELEC version:**
4.0

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
-S905x3 4gb
- hk1box

**Additional context**

**Comment by dm2912** [comment]
its in emuelec settings

![image](https://user-images.githubusercontent.com/25871666/110210621-5addbd00-7e8a-11eb-9a21-a43e9fd56eb1.png)
