### ISSUE TITLE
Bluetooth and Wifi Drivers to X96 MAX PLUS new version

### ISSUE THREAD

**Issue by elwaskop** [EmuELEC/EmuELEC#515]
Hello good Morning
Will it be possible to add the drivers for the new hardware that is coming is the x96 max plus? I have tried to find the model of the wifi and bluetooth chip and through applications it appears AR6K_WLAN, from what I have read it refers to a chip for Atheros. I do not know if you know it and can include it, thank you very much and I thank you for all your effort.

**Comment by AlienatedDiego** [comment]
Hi, first you should provide the chip model (probably need to open the box for this) and check if there are drivers for it.

**Comment by Iamghostfor** [comment]
> Hi, first you should provide the chip model (probably need to open the box for this) and check if there are drivers for it.

Hello ,I found the wifi and bluetooth chip is rtl8822cs（both of them is one chip）；

and is this it driver? https://github.com/chewitt/RTL8822CS

**Comment by elwaskop** [comment]
> > Hi, first you should provide the chip model (probably need to open the box for this) and check if there are drivers for it.
> 
> Hello ,I found the wifi and bluetooth chip is rtl8822cs（both of them is one chip）；
> 
> and is this it driver? https://github.com/chewitt/RTL8822CS

Hello friend, first of all I thank you very much for your prompt response. Really I have not dared to open the tvbox for warranty reasons. Is there a way to test the driver? Or find out the chip through software? I have used HWINFO.apk and I only got AR6L_WLAN and RTL8211F ethernet. In case you tell me that there is no option then I will open it to verify.
 :)
Greetings
