### ISSUE TITLE
Cannot pair a new device via Bluetooth in v4.1-TEST-02262021

### ISSUE THREAD

**Issue by mrabssalom** [EmuELEC/EmuELEC#516]
**Describe the bug**
After updating v4.0 (bug fixed) to latest Test Version, my device doesnt search for new bluetooth controlers.

**To Reproduce**
1. Go to 'Emuelec menu'
2. Click on 'Pair a new bluetooth device'
3. A message "Searching for devices" appears but last only a few seconds and dont found anything.

**Expected behavior**
Previously message "Searching for devices" lasted arround a minute or two and devices were found.

**EmuELEC version:**
 v4.1-TEST-02262021

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: s922x
 - Brand: Bellink
 - Model GT King
 - Version RevB

**Comment by shantigilbert** [comment]
Thanks for the report I will try to reproduce on my Gt-King

**Comment by shantigilbert** [comment]
so on v4.0 it works and on the same box on 4.1 does not?

**Comment by shantigilbert** [comment]
Can you try the newest test?

**Comment by mrabssalom** [comment]
> Can you try the newest test?

Will try this afternoon. 

v4.0 works perfectly, with that test version i try to pair a new bluetooth device and it doesnt search for nearby devices (message last 2 seconds and then fades out)

**Comment by shantigilbert** [comment]
After 14 days no information, will close this, feel free to reopen if the issue persists
