### ISSUE TITLE
Get some building error in lastest dev branch

### ISSUE THREAD

**Issue by ws02589111** [EmuELEC/EmuELEC#520]
System: ubuntu server 18.04 (get image from http://releases.ubuntu.com/18.04/) in vmware

Version: dev branch, commit id 104846af418430adc4ca29f147cd4e884a53b86b

Command:
`sudo apt update && sudo apt upgrade
sudo apt-get install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet default-jre

sudo apt-get install tzdata xfonts-utils lzop

git clone https://github.com/shantigilbert/EmuELEC.git EmuELEC    
cd EmuELEC  
git checkout dev
PROJECT=Amlogic ARCH=aarch64 DISTRO=EmuELEC make image `

1.
![image](https://user-images.githubusercontent.com/10301545/110791703-7ba07b00-82ad-11eb-9926-360a29ef4dc0.png)

After run `sudo apt-get install xsltproc` the error  is resolved, maybe add xsltproc install to readme?

2.
![image](https://user-images.githubusercontent.com/10301545/110807356-eb1e6680-82bd-11eb-85e7-ffe64005b076.png)

configure: error: ncurses selected, but library not found
FAILURE: scripts/install linux has failed!
[064/452] [FAIL] install linux

I tried to run `sudo apt-get install libncurses5-dev libncursesw5-dev` but no effect

Maybe the issue is relate the commit #7733f6674caddab2878579ebb82731576e02f8cc  ?

**Comment by shantigilbert** [comment]
You need to find out what package is giving you the error, and then add `ncurses` as a dependency.

**Comment by shantigilbert** [comment]
fixed on this commit: https://github.com/EmuELEC/EmuELEC/commit/368aa8e0d45213ad6cd26c8fafd98cc8b6dc2ea3

**Comment by ws02589111** [comment]
OK，thanks，the issue solved
