### ISSUE TITLE
Game request - Super mario war

### ISSUE THREAD

**Issue by keiem** [EmuELEC/EmuELEC#521]
There is a sdl2 port for super mario world: https://github.com/mmatyas/supermariowar/

I found the link in this post on the SMW forum: http://72dpiarmy.supersanctuary.net/index.php?topic=11252.0

I wondered if it would be possible to include it in EmuElec.

**Comment by shantigilbert** [comment]
It is not Super Mario World (it's War) , this is a MP game. However It will be added on the next release

**Comment by keiem** [comment]
Thanks!
