### ISSUE TITLE
[OpenBOR] symlink file should be removed in Paks folder

### ISSUE THREAD

**Issue by british-choi** [EmuELEC/EmuELEC#529]
symlink file should be removed in Paks folder after finishing OpenBOR game

## openbor.sh

 	# Run OpenBOR in the config folder
 	    cd "${CONFIGDIR}"
 	        SDL_AUDIODRIVER=alsa OpenBOR

	# Delete symlink from Paks folder
 	    rm -rf ${PAKS}/*

 	/usr/bin/setres.sh
 	killall gptokeyb &

**Comment by shantigilbert** [comment]
why?

**Comment by british-choi** [comment]
@shantigilbert 
The first game you run is normal.
However, when I run another OpenBOR game, the game I run does not run and launcher runs.
And the resolution of the launcher screen is not correct in OGA, 

Please try running 2 or more OpenBOR games on OGA.
