### ISSUE TITLE
Problems with using the B button in games

### ISSUE THREAD

**Issue by guy2010** [EmuELEC/EmuELEC#531]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

**Comment by guy2010** [comment]
![IMG_20210321_103122927](https://user-images.githubusercontent.com/78619497/111901856-512f8a00-8a32-11eb-9033-1adf542f1d64.jpg)
The game crashes.

**Comment by AlienatedDiego** [comment]
Do you suppose that we have a palantir to know what device, controller, game, EmuELEC version, emulator etc etc ... are you using? Please read the wiki first

**Comment by guy2010** [comment]
Ipega 9090 joypad 
Emuelec 3.9
