### ISSUE TITLE
Characters (CN, JP, KO) are not displayed properly in RetroArch

### ISSUE THREAD

**Issue by ws02589111** [EmuELEC/EmuELEC#534]
**Describe the bug**
This issue get from latest dev branch but the  latest release image  v4.0 is ok
I tried to replace the font in path /tmp/assets/xmb/monochrome/font.ttf and update video_font_path = "/tmp/assets/xmb/monochrome/font.ttf" in retroarch.cfg but no use

**To Reproduce**
1. Go to 'RetroArch'
2. Change the language to one of CN, JP, KO
3. Save config
4. Restart RetroArch

**Expected behavior**
Display characters normal

**Screenshots**
![991D8523C26ECDC587091C0536AECB6F](https://user-images.githubusercontent.com/10301545/112121651-6f47e680-8bfa-11eb-9a1c-ba4e5cb751cd.jpg)

**EmuELEC version:**
 -  latest dev branch

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE]
 - SOC: S905M, S905L

**Additional context**
1.Send roms with CN, JP, KO name over ssh is failed also
2.Use DiskGenius copy roms with CN, JP, KO name to card  ，open rom folder with samba，the files name get ??? characters 
![image](https://user-images.githubusercontent.com/10301545/112128852-c8ffdf00-8c01-11eb-9253-e4e5fd087580.png)
3.The roms uploaded by step2， show in es menu is(The game is running normally):
![image](https://user-images.githubusercontent.com/10301545/112130431-71fb0980-8c03-11eb-9a80-c729c0e3d3aa.png)

**Comment by ws02589111** [comment]
I tried revert retroarch to old version to test, until reverted to 7450f049e72dd3388dfed2439c1af73e088e4fd9， the RetroArch  not displayed properly issues is no longer occurs. but the other issues is also existed

**Comment by shantigilbert** [comment]
#431

**Comment by insmagic** [comment]
not resolved in #431,it worked on 4.0.When I update to 4.1,the retroarch displayed still wrong like this but the game roms are display all right in emuelec.

**Comment by insmagic** [comment]
I replace the .ttf files to the storage/.config/retroarch/assets,then change the language to CN,it displayed perfect,but if I quit the retorarch and select restart to retorarch,it displayed all as □□□□

**Comment by shantigilbert** [comment]
This is a Retroarch issue,  I could not find a solution so this has to be directed to them.

**Comment by insmagic** [comment]
Yes I found that it seems a bug in retroarch 1.9.1,thank you!😄

**Comment by mavisguo** [comment]
You know that you can fix it but you don't. It's not the problem of RA. You can't anger all Chinese players just because a Chinese manufacturer wants to pay and ask you to make customized EMUELEC. Please fix it. Please!

**Comment by shantigilbert** [comment]
> 
> 
> You know that you can fix it but you don't. It's not the problem of RA. You can't blame all Chinese players just because a Chinese manufacturer wants to pay and ask you to do customized EMUELEC. Please fix it. Please!

if you are so angry, fix it yourself then.

**Comment by shantigilbert** [comment]
For future reference: https://github.com/libretro/RetroArch/issues/12215

**Comment by mavisguo** [comment]
ok,ok,well.

> > You know that you can fix it but you don't. It's not the problem of RA. You can't blame all Chinese players just because a Chinese manufacturer wants to pay and ask you to do customized EMUELEC. Please fix it. Please!
> 
> If you are so angry, fix it yourself then. I do not know how to fix it, I already told you its a RA issue. Not something I can just flip a switch and fix.

**Comment by ssmax** [comment]
in EMUELEC 4.2 , Retroarch version 1.9.4 , 32 bit (don't know why, haha)
when it quit, it will set a hidden config line in retroarch.cfg:
xmb_font = ""
this config will lead to the problem.
you should set it to your font path manually by ssh or samba.
after you set it , you will resolve the problem.
only when you select xmb menu_driver in Emulationsation, it will replace the menu_driver option before start retroarch.
