### ISSUE TITLE
A trick to make two controllers of the same type work via bluetooth

### ISSUE THREAD

**Issue by thanghn90** [EmuELEC/EmuELEC#537]
**Describe the bug**
When two controllers of the same type (e.g. PS4 AND PS5 controllers) are connected via bluetooth, one button on a controller is registered on both input 1 and 2. The problem disappears after loading a game or quit to retroarch ONCE, and then back to the main emulationstation.

**To Reproduce**
1. Plug a wired controller in (can be one of the two bluetooth controller)
2. Use the wired controller to pair two bluetooth controllers of the same type
3. Unplug the wired controller
4. The buttons on either bluetooth controllers now registered with both input 1 and 2.
5. Now, either load a game or quit to retroarch, then quit retroarch. The bluetooth controllers button are now correctly assigned to different inputs.

**Expected behavior**
Two different bluetooth controllers should register as two different input right after pairing.

**EmuELEC version:**
EmuELEC-Amlogic-ng.aarch64-4.0-Generic.img.gz

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: S095X2
 - Brand: H96
 - Model H96 Max X2

**Additional context**
No big deal, just something funky that can be resolved with a quick trick.

**Comment by Langerz82** [comment]
Ha I noticed this too, when I was charging 3 controllers, and unplugged one to play.
