### ISSUE TITLE
EmuELEC 4.0 RetroArch config issue

### ISSUE THREAD

**Issue by miaoanbang** [EmuELEC/EmuELEC#545]
Hi, I am using OGS and EmuELEC 4.0. I have seen issues with RetroArch configs. For example, I changed Global RetroArch setting driver->menu to ozone, but when I am inside GBA gpsp game and calls out retroarch in game, the driver->menu changed to xmb.
Such changes is hard especially when I want to have some global settings, some system level settings and maybe some game specific settings.
I have no sure issue with retropie and I am not sure if this can be resolved.

**Comment by shantigilbert** [comment]
On v4.1 you will be able top choose the RA menu, meanwhile those are hardcoded. 

https://github.com/EmuELEC/EmuELEC/commit/e1383e90f3bff36c57171ede47b593206c891865
