### ISSUE TITLE
Incorrect time zone entry `Asia/Hong_ong` which should be `Asia/Hong_Kong`

### ISSUE THREAD

**Issue by PikachuEXE** [EmuELEC/EmuELEC#546]
**Describe the bug**
Odroid-GO Super has displayed a time zone entry value `Asia/Hong_ong` in time zone config menu

**To Reproduce**
1. Go to 'Main Menu', 'System Setting', 'Timezone'
2. Scroll down to 'Asia/HOVD'
3. Look at the entry above 'Asia/HOVD'

**Expected behavior**
1. Displayed as `ASIA/HONG_KONG`
2. When it's selected as timezone, system clock display time in UTC+8

**Actual behavior**
1. Displayed as `ASIA/HONG_ONG`
2. When it's selected as timezone, system clock display time in UTC+0

**Screenshots**

**EmuELEC version:**
v4.0
(Has not tried on latest test version yet)

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
Odroid-GO Super

**Comment by british-choi** [comment]
@shantigilbert 
emuelec-emulationstation
diff --git a/es-core/src/platform.cpp b/es-core/src/platform.cpp
index 82d4704b..655e53c0 100644
--- a/es-core/src/platform.cpp
+++ b/es-core/src/platform.cpp
@@ -381,7 +381,7 @@ std::string getShOutput(const std::string& mStr)
     while(fgets(buffer, sizeof(buffer), pipe) != NULL)
     {
         file = buffer;
-        result += file.substr(0, file.size() - 1);
+        result += file.substr(0, file.size());
     }

     pclose(pipe);

**Comment by shantigilbert** [comment]
> 
> 
> @shantigilbert
> 
> emuelec-emulationstation / platform.cpp
> check below function
> std::string getShOutput(const std::string& mStr)
> `- result += file.substr(0, file.size() - 1);`
> `+ result += file.substr(0, file.size());`

does this fixes the issue? does it cause any other issues? `getShOutput` is used on many places

**Comment by TheLastProject** [comment]
It's interesting that this only seems to happen on the Odroid Go Super. My GameForce Chi is not affected. May be a version difference though, my OGS is on V4.1-TEST-02182021 and my GFC is on V4.1-TEST-03082021.

I thought maybe the zone1970.tab file was different (see https://github.com/EmuELEC/EmuELEC/pull/279/files#diff-c903f109b5cb8349fe96edbe90f34eabe6a13627e6877d4611e97794b37e27a5R193) but it's not, it's written as "Asia/Hong_Kong" there correctly.

**Comment by shantigilbert** [comment]
I think its even more strange that it only happens with that particular string none of the others seem affected, and none of the other places that use the same function are affected either... I am thinking there is something that changes `_K` to `_` somewhere in the code but I have not looked into it yet.

**Comment by PikachuEXE** [comment]
My `/usr/share/zoneinfo/zone1970.tab` on device does have `Asia/Hong_Kong`

Another incorrect timezone spotted would be `Amrica/Nipigon` which should be `America/Nipigon` (hard to find it in file)

**Comment by british-choi** [comment]
@shantigilbert 
this fixes the issue!
string substr(size_t pos = 0, size_t len = npos) const;
len parameter should be file size(max 256 byte) in reading pipe.
However, 256 bytes were read from the pipe, and only 255 bytes were copied to the result.
So some characters are missing.

**Comment by shantigilbert** [comment]
I just tested that and it causes a LOT more issues, 
Shaders no longer work for example. 

But this gives an idea as to why there are broken, so I will investigate 

I think that `/usr/bin/emuelec-utils timezones` should return a list of TZ with a new line at the end for it to work

**Comment by shantigilbert** [comment]
```
function timezones() {
	cat /usr/share/zoneinfo/zone1970.tab | grep -v "^#" | awk '{ print $3"," }' | sort -u
}
```
in https://github.com/EmuELEC/EmuELEC/blob/f5d53ae824b9e721b9d128ac74236f648d9699b9/packages/sx05re/emuelec/bin/emuelec-utils#L171

This is the fix, ES code is untouched and now both of those TZ display correctly

**Comment by shantigilbert** [comment]
![20210331191615583](https://user-images.githubusercontent.com/18634770/113230150-adc24e80-9255-11eb-9574-33277b89d8a7.png)

**Comment by PikachuEXE** [comment]
Will try again once next test version released
