### ISSUE TITLE
Retroarch menu selection's description wrong

### ISSUE THREAD

**Issue by ws02589111** [EmuELEC/EmuELEC#549]
**Describe the bug**
Retroarch menu selection's description wrong， it should be XMB right？

**To Reproduce**
1. Go to EMUELEC SETTINGS
2. Click on RETROARCH MENU

**Screenshots**
![image](https://user-images.githubusercontent.com/10301545/113266209-96439e00-9307-11eb-9322-bca77652965e.png)

**EmuELEC version:**
 - the dev commit: 1af7d7b461f527bec7dd2fcaef83ad2cedbacd5e

 - SOC:  S905M

**Comment by british-choi** [comment]
XMB is correct. 
The emulationstation is displaying it incorrectly.

**Comment by shantigilbert** [comment]
This has been fixed in dev, thanks for the report
