### ISSUE TITLE
Emuelec 4.0 screen issue with x96 max+ with s905x3 4g

### ISSUE THREAD

**Issue by eranlenga** [EmuELEC/EmuELEC#550]
hi.
i have x96 max+ with s905x3 4gb ram 64gb storage .
i'v made sd card with Emuelec 4.0.
when i turn on the tv box with the sd card for the first time i see Emuelec logo. 
after that i see the Emuelec start up screen but in a wired way. the picture multiply 3 time.
every version of Emuelec doesnt work good. i tried with 4k TV and 720P TV with HDMI cable
​​​​​​​any idea?

![WhatsApp Image 2021-04-01 at 19 36 15](https://user-images.githubusercontent.com/81709158/113326574-85545600-9322-11eb-9800-9a54947a0872.jpeg)
![WhatsApp Image 2021-04-01 at 19 36 33](https://user-images.githubusercontent.com/81709158/113326576-85ecec80-9322-11eb-9b7c-1c9afb9aa049.jpeg)

**Comment by shantigilbert** [comment]
Set your Android TV box to 1080p, then reboot to EmuELEC

**Comment by eranlenga** [comment]
I did it already. 
Maybe it something i can change in the config.ini file?
