### ISSUE TITLE
Add Support for new variant, Amlogic S905W p282 , the p281 don't boot properly. i tried all

### ISSUE THREAD

**Issue by KirbDev** [EmuELEC/EmuELEC#561]
Like i said before, i bought unafortunately some tv box with the variant P282 , equivalent to S905W with 2gb ram and 16 rom specs. the device in question is T95 S1 , i tried executing emuelec for P281 1gb, boots but it turn his screen in black.

How is possible other tv boxes can run emuelec and this model can't?

(sorry broken grammar)

Context: i attach some pictures for better understanding
![IMG_20210413_152038](https://user-images.githubusercontent.com/80369700/114628347-54f2ad00-9c7c-11eb-975d-18b2973a4b6d.jpg)
![61A1WdZGxtL](https://user-images.githubusercontent.com/80369700/114628368-60de6f00-9c7c-11eb-98f5-281e5fab39c3.png)
![IMG_20210412_164134](https://user-images.githubusercontent.com/80369700/114628376-6340c900-9c7c-11eb-95d3-5d4ca79749e6.jpg)
![IMG_20210412_192935](https://user-images.githubusercontent.com/80369700/114628387-65a32300-9c7c-11eb-9e92-0b722cad47f9.jpg)

**Comment by dm2912** [comment]
the trouble with all these generic t95 / h96 / x88 / etc etc is they can all have very different internal components so frequently they will run into dtb errors because the hardware does not exactly match what the dtb expects. 

people have struggled to get coreelec running on this box as well https://discourse.coreelec.org/t/t95-s1-which-device-tree/12058/18

**Comment by KirbDev** [comment]
oh i see, for now coreelec and emuelec are currently unsupported for my device?

**Comment by KirbDev** [comment]
i think, no ... basically i gonna close the thread. sadly i think gonna use slow emmc boot up

**Comment by KirbDev** [comment]
Solved i do the test with some help, i used EE Video mode ntsc with p281 dtb device tree (1G)
