### ISSUE TITLE
TX3 Mini - Just purchased it, and Im not sure which verison of emuelec to download and the dtb file to use, can  anyone recomend something that workks.

### ISSUE THREAD

**Issue by amhayawan** [EmuELEC/EmuELEC#563]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/wiki/How-to-Install
