### ISSUE TITLE
Deleting all game metadata from game in collection crashes ES

### ISSUE THREAD

**Issue by chucksmith** [EmuELEC/EmuELEC#564]
**Describe the bug**
When I delete a game's metadata from a collection, ES crashes and restarts.

**To Reproduce**
1. Go to any game within a collection
2. Click on EDIT THIS GAME'S METADATA
3. Click on DELETE
4. Confirm the deletion
5. ES crashes and restarts

**Expected behavior**
I expect it to delete that game from my drive. (I usually do this when I discover duplicate games in my library while browsing collections.)

**Screenshots**

**EmuELEC version:**
 - 4.1-TEST-03302021

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: S922x
 - Brand: Beelink
 - Model: GT-King

**Additional context**

**Comment by shantigilbert** [comment]
Thanks for the report, I cannot reproduce it on newer test so maybe its already fixed, but just in case, does this happen on ALL systems? or just some ?

**Comment by chucksmith** [comment]
It doesn't happen on any systems, only on custom collections like the list of 2-player games.

**Comment by chucksmith** [comment]
This is no longer a bug in EmuELEC 4.2-TEST-05142021. Feel free to close this issue!
