### ISSUE TITLE
No available connection into WIFI connection on x96 max plus. Please help

### ISSUE THREAD

**Issue by nicknix1** [EmuELEC/EmuELEC#567]
Hi guys,im new here and only starting to use and program emuelec into my tv box 
X96 max+ Running S906x Im unable to connect the tv box into WIFI on emuelec 4.0 build. Every time i want to connect to the wifi, Its not showing the wifi network to connect. What can I do to fix this? Step by step if someone can please.

**Comment by shantigilbert** [comment]
Please read all the other issues regarding this, short answer is it does not work.
