### ISSUE TITLE
x96 max plus amlogic unkown soc rev b wifi not working

### ISSUE THREAD

**Issue by difrah1** [EmuELEC/EmuELEC#568]
Hi i installed few ver of emuelec and i cant search wifi when i checked my box i got the x96 max plus q2 that have diffrent wifi chipset and i try to change the dbt.img file and noting is working.

**Comment by SamuEDL** [comment]
Good afternoon. Without knowing that chipset WiFi has the TVBOX, we can not know if you can solve the problem.
