### ISSUE TITLE
Scummvm issue (PQ4 Crash, and MP3 Files)

### ISSUE THREAD

**Issue by eviltroooper** [EmuELEC/EmuELEC#569]
scummvm 2.3.0git-dirty seems to have some errors.
if i enable in Police quest 4 speech and Subtitle i cant save (it crash)
also seems that it has no MP3 Support

`ScummVM 2.3.0git-dirty (Jan  9 2021 13:53:49)
Features compiled in: Vorbis FLAC ALSA SEQ TiMidity RGB zLib MPEG2 FluidSynth FreeType2 FriBiDi JPEG PNG cloud (local) TinyGL OpenGL OpenGL ES 2`

on my PC i got installed ScummVM 2.2.0

`ScummVM 2.2.0 (Sep 14 2020 23:43:32)
Features compiled in: Vorbis FLAC MP3 RGB zLib MPEG2 FluidSynth Theora AAC A/52 FreeType2 FriBiDi JPEG PNG cloud (servers, local)`

also PQ4 is not crashing. is it possible to use the stable Scummvm Version?

**Comment by shantigilbert** [comment]
I have no idea about PQ4, you failed to provide logs so its hard to even guess, Mp3 support has been added for next release
