### ISSUE TITLE
NEC PC-FX music issues

### ISSUE THREAD

**Issue by Cebyo** [EmuELEC/EmuELEC#570]
Hi the team.

First of all, I would like to thank you for the wonderful work you do.

I'm writing to you because I am having problems with the emulation of the pc-fx which is a console that I love. The problem is that the sound lags. Do you have any advice for me.

For information, I am running emuELEC version 3.9 on an H96 Max X3 android box. The games I use are in several bin and one cue formats.

Thank you in advance

**Comment by shantigilbert** [comment]
No idea, you need to use v4.0 and see if the same issue happens there, other wise your device might not be powerful enough to emulate it

**Comment by Cebyo** [comment]
Hello,

this weekend I updated my system to 4.0 but the problem persists. I did indeed think about the power of the Android Box but on the other hand, when I see that the Dreamcast or PSP games work very well, i do not understand how this technically less powerful console has trouble working.
