### ISSUE TITLE
Two timezone menus in system settings

### ISSUE THREAD

**Issue by british-choi** [EmuELEC/EmuELEC#572]
**Describe the bug**
There are two time zone menus.

**To Reproduce**
1. Go to 'system settings' menu
2. Check timezone menu (information / TIMEZONE / language / TIMEZONE)

**Expected behavior**
There should be only one time zone menu.

**EmuELEC version:**
 - 4.1

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: rk3326
 - Brand: hardkernel
 - Model: oga v1.1

**Comment by PikachuEXE** [comment]
Same for 
EmuELEC: 4.1
SOC: RK3326
Brand: HardKernel
Model: OGS

No issue in 4.0

**Comment by PikachuEXE** [comment]
Don't see it in `4.2-TEST-05142021`
what changed?
