### ISSUE TITLE
If brightness is set to 35% or lower, it lowers by 1% each boot.

### ISSUE THREAD

**Issue by PunnX86** [EmuELEC/EmuELEC#574]
**Describe the bug**
If screen brightness is set to 35% or lower, it will lower itself by 1% each boot. A workaround is to set the brightness to 40% or higher.

**To Reproduce**
1. Enter system settings.
2. Adjust brightness to 35%.
3. Exit system settings, at which point brightness will be set immediately to 34%.
4. Reboot or shutdown/boot.
5. Enter system settings and see that the brightness is now 33%. The next boot will be 32, 31, etc.

**Expected behavior**
Brightness should remain the same across reboots no matter the initial setting.

**EmuELEC version:**
 - Version 4.1

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: RockChip RK3326
 - Brand: Odroid
 - Model Go Advance Black Edition
 - Version 1.1

**Additional context**
A workaround is to set the brightness to 40% or higher.

**Comment by miwasp** [comment]
Just created a pull request with a fix.
Problem was that math in bash only uses integer and no floating. This resulted in rounding errors, which are now hopefully fixed using awk for the math.
