### ISSUE TITLE
Dolphin automatic gamepad support

### ISSUE THREAD

**Issue by iCanuck** [EmuELEC/EmuELEC#576]
In release v4.0 the notes said “ Dolphin has been added to the Amlogic-ng devices, but it is only really playable on S922x devices and gamepad stills needs to be set manually. Will fix this on v4.1”

On v4.1 gamepads don’t work automatically with Dolphin. Any idea when this will be implemented? 

Can you point me in the right direction how to setup manually? 

Thnx appreciate all the work you do!

**Comment by shantigilbert** [comment]
It did not made it to the final 4.1, so it will be for 4.2
