### ISSUE TITLE
Khadas VIM3 3705 FAN is not working, seems  i2c-tools is needed

### ISSUE THREAD

**Issue by eviltroooper** [EmuELEC/EmuELEC#579]
i installed the 3705 FAN on my VIM3 but the Fan is not spinning..

there is a Fan.sh script.. but it seems i2c-tools need to add on busybox. is that possible?

https://github.com/hyphop/khadas-utils/blob/master/utils/fan

**Comment by eviltroooper** [comment]
on Coreelec under Hardware there is "FAN" and i can enable it.. dont know how it works.. but it would be cool if someone can enable this on emuelec too.. :)

**Comment by eviltroooper** [comment]
Mhh looks like it only use /sys/class/fan
Any idea how to change this on startup?

https://github.com/CoreELEC/service.coreelec.settings/blob/coreelec-19/src/resources/lib/modules/hardware.py#L646-L664

**Comment by shantigilbert** [comment]
You can edit autostart.sh

**Comment by eviltroooper** [comment]
Yeah I tested it with Autosparte.so..
Just need to remind that I need to edit it every update. 
don’t know if can can build a button on the Menu?

**Comment by shantigilbert** [comment]
autostart.sh does not get removed on updates

**Comment by eviltroooper** [comment]
For me it’s okay to use autostart.sh 
But don‘t know if autostart.sh will updated (if emulationstation will be updated), I will keep it in Mind.

If you want to build a switch it would be cool also..
