### ISSUE TITLE
error when build ecwolf@4.1

### ISSUE THREAD

**Issue by insmagic** [EmuELEC/EmuELEC#580]
I have met the error when build ecwolf
it showed error as :
CMake Error at Locate SDL2.cmake
Please set SDL2_net_DIR to the location of sdl2_net-config.cmake.
then I get install with:
sudo apt install libsdl2-dev libsdl2-net-dev
It seems done.
when 4.0 I have not seen it.

**Comment by shantigilbert** [comment]
So if you fixed it, what is the issue?

**Comment by ChiaYen-Kan** [comment]
Hi 
i also build v4.1 fail on ecwolf 
the attach file is my build log, how to fix this error?
thank

[ecwolf_error.txt](https://github.com/EmuELEC/EmuELEC/files/6418880/ecwolf_error.txt)

**Comment by insmagic** [comment]
> Hi 
> i also build v4.1 fail on ecwolf 
> the attach file is my build log, how to fix this error?
> thank
> 
> [ecwolf_error.txt](https://github.com/EmuELEC/EmuELEC/files/6418880/ecwolf_error.txt)
> 

sudo apt install libsdl2-dev libsdl2-net-dev
I used this command，your problem seems not the same as mine.Goodluck!

**Comment by ChiaYen-Kan** [comment]
> 
> 
> > Hi
> > i also build v4.1 fail on ecwolf
> > the attach file is my build log, how to fix this error?
> > thank
> > [ecwolf_error.txt](https://github.com/EmuELEC/EmuELEC/files/6418880/ecwolf_error.txt)
> 
> sudo apt install libsdl2-dev libsdl2-net-dev
> I used this command，your problem seems not the same as mine.Goodluck!

i try the `sudo apt install libsdl2-dev libsdl2-net-dev`, but don't work for my case

**Comment by miwasp** [comment]
Please try `sudo apt install libsdl2-mixer-dev libfluidsynth2`
