### ISSUE TITLE
Odroid Go Super: 4.1 Stable - Reset config/binary script removes drastic saves/save states

### ISSUE THREAD

**Issue by PikachuEXE** [EmuELEC/EmuELEC#589]
**Describe the bug**

**To Reproduce**
1. Restore 4.0 stable backup SD card image
2. Update to 4.1 via SD card direct copy of tar file into `.update`
3. Boot again, update, reset binary, reconnect network, install drastic
4. Start a random game
5. No save state/normal save

**Expected behavior**
- Drastic game saves/save states retained

Drastic save folders:
- `/storage/.config/emulationstation/scripts/drastic/backup`
- `/storage/.config/emulationstation/scripts/drastic/savestates`

**EmuELEC version:**
4.1

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: Rockchip
 - Brand: HardKernel
 - Model: Odroid-GO Advance

**Comment by shantigilbert** [comment]
This is what the script keeps
      
      ```
        tar -zcvf "${BACKUPFILE}" /storage/.local/share/VVVVVV/* \
					  /storage/.cache/bluetooth/* \
					  /storage/.cache/timezone \
					  /storage/.config/scummvm/* \
					  /storage/.config/emuelec/configs/emuoptions.conf \
					  /storage/.config/emuelec/configs/emuelec.conf \
					  /storage/.emulationstation/es_*.cfg \
					  /storage/.emulationstation/themesettings \
					  /tmp/joypads/* \
					  /storage/.config/retroarch/*.cfg \
					  /storage/.config/ppsspp/* \
					  /storage/.config/retroarch/config/* \
					  /storage/.config/supertux* \
					  /storage/.emulationstation/scripts/drastic/config/* \
					  /storage/.emulationstation/scripts/drastic/*.dsv \
                      /storage/.config/emuelec/bin/pico-8/*
                      
```

As you can see drastic is there, unless you manually installed some where else?

**Comment by PikachuEXE** [comment]
The game saves & save states are not backup

Drastic save folders:
- `/storage/.config/emulationstation/scripts/drastic/backup`
- `/storage/.config/emulationstation/scripts/drastic/savestates`

**Comment by PikachuEXE** [comment]
Was trying to test on 4.1 but the script seems to be on some readonly partition?

**Comment by PikachuEXE** [comment]
Keeping this opened until I am able to test the script myself

**Comment by PikachuEXE** [comment]
Tested in `4.2-TEST-05142021`
