### ISSUE TITLE
Changing theme makes Emuelec loading screen freeze after reboot

### ISSUE THREAD

**Issue by FragDAnvers** [EmuELEC/EmuELEC#592]
Like the titel says:

Whenever I change the theme in emulationstation, and I reboot, I get stuck on the Emuelec loading screen (sometimes is blinks black for a second)
Only solution so far is reflashing the image. So far I had it with Alekfull Artflix and ckau-book.

Anyone got suggestions/solutions?

**Comment by snakect77** [comment]
Prova a modificare i parametri vram

**Comment by shantigilbert** [comment]
Please follow the template and fill out all the information.
