### ISSUE TITLE
I found that the PSX gamepad sequence was inconsistent with the emulationStation gamepad sequence When I connected more different gamepads

### ISSUE THREAD

**Issue by zcl226403** [EmuELEC/EmuELEC#593]
Describe the bug
I found that the PSX gamepad sequence was inconsistent with the emulationStation gamepad sequence When I connected more different gamepads

To Reproduce
1. Connect 3 or more different gamepads
2. For example: if you go to arcade, 1P is Xbox 360 gamepad, but if you go to PSX, Xbox 360 gamepad becomes 2P

EmuELEC version:
 - Version 4.x

**Comment by shantigilbert** [comment]
You need to define the players in the controller config.

**Comment by shantigilbert** [comment]
For these kind of issues, please use either the forum (https://emuelec.org) or discord
