### ISSUE TITLE
PPSSPP controller PS3 issue

### ISSUE THREAD

**Issue by Cebyo** [EmuELEC/EmuELEC#594]
Hi, i've tried many times to map my ps3 controler in PPSSPP but it's very crazy.  The buttons do not correspond at all ... like he tells me that the cross is the "pad up" ... well, so,  I configure anyway but then if I manage that the controls of the game is relatively correct ... after to enter the menu ... it no longer corresponds at all.  Result : I can't exit. You have any ideas ?

**Comment by shantigilbert** [comment]
Please don't use github for this kind of issue, either use the forum or discord.
