### ISSUE TITLE
about the stepmania，I don’t know if it helps

### ISSUE THREAD

**Issue by zcl226403** [EmuELEC/EmuELEC#615]
about the stepmania，I don’t know if it helps
Compile StepMania on Raspberry Pi：https://github.com/SpottyMatt/raspbian-stepmania-build
StepMania Arcade on Raspberry Pi：https://github.com/SpottyMatt/raspbian-stepmania-arcade

**Comment by shantigilbert** [comment]
That seems very specific for the PI, if someone else wants to try that, feel free, I don't think I want to translate all of that for EmuELEC
