### ISSUE TITLE
Gameforce hotkey switches sound

### ISSUE THREAD

**Issue by spacerighthere** [EmuELEC/EmuELEC#618]
A hotkey combination seems to be assigned to two functions at the same time on the Gameforce handheld.
Homekey+R1 is supposed to save the game, but also switches sound between speakers and headphones.

**Comment by spacerighthere** [comment]
The homekey + left or right dpad also has a double function in games. It supposed to change the brightness but it also switches the save slot.

**Comment by shantigilbert** [comment]
as it says on the label, this has been added to dev, read the changelog here:

https://github.com/EmuELEC/EmuELEC/blob/master/CHANGELOG
