### ISSUE TITLE
Update bsnes

### ISSUE THREAD

**Issue by IdiotBlueMage** [EmuELEC/EmuELEC#621]
While bsnes may still be a dream for most things that use emuELEC now, removing the mercury cores and replacing them with the libretro core based on the latest would head off a whole lot of problems in the long run.  IIRC current bsnes has everything mercury does and more with regards to speed while still being more up to date, and it would fix confusion about which bsnes core to use that commonly happens on other platforms.

This is however more about the future than the present.

**Comment by shantigilbert** [comment]
Can you please read the template for issues and post this either on the forum or discord? this is not a BUG nor an issue!
