### ISSUE TITLE
Build dosbox-svn problem#4.1

### ISSUE THREAD

**Issue by leoliao2021** [EmuELEC/EmuELEC#628]
1、see build install dosbox-svn failed#4.1 #627
2、I update package and copy GitHub file into my project.(packages/sx05re/libretro/dosbox-svn/package.mk)
3、rm build.EmuELEC-Amlogic.aarch64-4.1/dosbox-svn-97425232734636594d615f900b5971498451d794/ -rf
4、PROJECT=Amlogic ARCH=aarch64 DISTRO=EmuELEC make image
It's the same error,It didn't solve the problem.It's strange that we need to update other places？

**Comment by shantigilbert** [comment]
Can you please stop opening issues about this? Build the dev branch or learn how to Google these errors. I do not know how to solve then because I don't get those errors, you are most likely missing a library or are using another os other than Ubuntu, for which I cannot help you.
