### ISSUE TITLE
Sunvell T95z plus/3gb/amlogic S912

### ISSUE THREAD

**Issue by RyanH86** [EmuELEC/EmuELEC#630]
Hi. I am wanting to install emuELEC on a Sunvell t95z plus with 3gb ram. I have been following this tutorial on youtube https://www.youtube.com/watch?v=eXfultzENjY&t=333s and I have looked at the wiki page which states that you can install older versions of emuELEC (up to version 3.9) on a box with an amlogic S912 cpu. I have downloaded the "EmuELEC-Amlogic-ng.arm-3.9-Generic.img" and also the 3.8 image and installed them onto a micro sd with etcher but when it comes to device trees there isn't a DTB file for the S912 chip in the device tree folder...

Am I downloading the wrong images or is there a particular DTB file which will work on my box?

![Screenshot 2021-05-31 141205](https://user-images.githubusercontent.com/85115376/120198759-66871880-c21a-11eb-9965-e5c1056957ad.jpg)

**Comment by shantigilbert** [comment]
Yes its the wrong image, please read how to install on the WiKi https://github.com/EmuELEC/EmuELEC/wiki/How-to-Install
