### ISSUE TITLE
How to install new themes in version 4.1

### ISSUE THREAD

**Issue by nicknix1** [EmuELEC/EmuELEC#632]
Hi guys
I’m unable to find any topic in regards to installing new themes on version 4.1 by using ES Themes options such as cartoon, soda or turtle via settings same as the version 3.9. What will be the easiest way to install or get the other themes? As the one that’s in downlods and updates are limited to 18 themes.
Let us know cheers

**Comment by shantigilbert** [comment]
Please do not post general questions here! use the forum or discord.

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/604
