### ISSUE TITLE
Gameforce CHI - 4.1/4.2 test - Retroachievements not working with SNES9x

### ISSUE THREAD

**Issue by matteozel** [EmuELEC/EmuELEC#633]
Ciao,

I'm having a strange issue with retroachivements in 4.1 on the gameforce chi.
I can login in emulationstation with my account, I can see the achievements list in emulationstation but in retroarch retroachievements is not working properly.

In retroarch settings I can see username and password (both are correct) but the "achievements" menu in the quick menu says that I'm not logged in

![image](https://user-images.githubusercontent.com/3006006/120883224-3b1a7a00-c5dc-11eb-89b0-285fbd7d7829.png)

I've tried to re-enter username and password in retroarch, also I've re-flashed from scratch 41 but the issue still occur.
With 4.1 on OGS there is no issue

(same rom, same emulator, same emuelec version, different device) 

![image](https://user-images.githubusercontent.com/3006006/120883288-a95f3c80-c5dc-11eb-9dd7-31c51976825a.png)

**Comment by shantigilbert** [comment]
Can you try latest 4.2-test?

**Comment by shantigilbert** [comment]
![20210605122627095](https://user-images.githubusercontent.com/18634770/120900255-8727e780-c5f9-11eb-9432-0302264ab5ac.png)
I am using the GF with 4.2-test and this seems to work fine

**Comment by matteozel** [comment]
Same issue after the update to the latest 4.2 test, I've done some other test and this is what I've understand:
- problem it's related to SNES9X emulator (I've tried the different snes9x cores)
- problem is on 4.1 and 4.2 test as well
- launching another emulator/rom (eg: Genesis Plus GX + Sonic 1), retroachievements is working as expected:
![immagine](https://user-images.githubusercontent.com/3006006/120922938-4fd63b00-c6cc-11eb-8fb6-f7b69ea611db.png)
- launching again snes9x the message is different but the issue is the same (no achievements):
![immagine](https://user-images.githubusercontent.com/3006006/120922953-5f558400-c6cc-11eb-991b-f8c4003f1971.png)

Screens are from 4.1 but it's the same on 4.2.
As you can see from this:
![immagine](https://user-images.githubusercontent.com/3006006/120923035-a479b600-c6cc-11eb-94d9-2e982ba0d2ba.png)
it seems that with snes9x core retroarch is not able to reach retroachievements at all. The snes rom is the same as on the first post so I'm sure that the rom is supported.

**Comment by shantigilbert** [comment]
I have no idea why this is happening, and I cannot reproduce it, Using Snes9x on my Chi, achievements work as usual 
![20210606123239409](https://user-images.githubusercontent.com/18634770/120934283-590eda00-c6c3-11eb-84d2-ef60eab85d01.png)

**Comment by shantigilbert** [comment]
![20210606123544917](https://user-images.githubusercontent.com/18634770/120934541-48ab2f00-c6c4-11eb-9868-cfa4b6815e11.png)
![20210606123935580](https://user-images.githubusercontent.com/18634770/120934542-4943c580-c6c4-11eb-94d3-9f58f8a7c515.png)

here another 2 screenshots one before and one after unlocking an achievement

**Comment by matteozel** [comment]
Thanks for the feedback @shantigilbert, probably I'm making some dumb mistake (like wrong rom or whatever), I'm closing this one and I will investigate on my own :)

**Comment by shantigilbert** [comment]
Let me know if you find something that I am missing.
