### ISSUE TITLE
No video after launching any ResidualVM game

### ISSUE THREAD

**Issue by ehula** [EmuELEC/EmuELEC#635]
I am running EmuELEC v3.9 on a S912 rev a. When I launch a ResidualVM game, I just get a black screen. Sometimes after a cold boot, the first time I run a game, I may hear the game's audio, but if I quit (ctrl-q) and run it a second time, no audio.

**Comment by shantigilbert** [comment]
S912 has a lot of issues with standalone emulators, there is no fix, sorry,
