### ISSUE TITLE
Latest 4.2 TEST build. Parallel 32b core crashes N64 titles.

### ISSUE THREAD

**Issue by tegnkush** [EmuELEC/EmuELEC#636]
**Describe the bug**
When loading any N64 title after upgrading to 4.2. No matter the build type. OGA or Amlogic devices the games immediately crash with a red screen indicating there is no path for cores.

**To Reproduce**
1. Go to games after updating
2. Click on any n64 title
3. Load game
4. Appears red screen with error message

**Expected behavior**
N64 titles to play

**Screenshots**

**EmuELEC version:**
 - Version 4.2-TEST-06062021

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: S095x -
 - Brand: HK1 - OGA - Powkiddy
 - Model  Odroid Go Advance - Powkiddy RGB10Max
 - Version xx

**Additional context**
This happens after updating directly over air or using tar file. Only core that works is Mupen NEXT

**Comment by shantigilbert** [comment]
logs?
