### ISSUE TITLE
MPV unbindable buttons?

### ISSUE THREAD

**Issue by MoreFoxBeans** [EmuELEC/EmuELEC#639]
I was customizing the keybinds for the built-in MPV video player (I think it's MPV, I did hours of research and only found one thing saying that but that's what it seems to be) and found out that some buttons are duplicates of others or aren't bindable at all. The L, R, L2, R2, Y2-, Y2+, F1, F2, F3, and F4 buttons can't be recognized by MPV (as far as I know). Also X2- and X2+ are duplicates of LEFT and RIGHT. Is there any way I can reliably bind to these buttons?

**Comment by shantigilbert** [comment]
Please reopen and follow the issue template, they are there for a reason.
