### ISSUE TITLE
No folders in the ROM folder when setting up emuelec

### ISSUE THREAD

**Issue by iopearce** [EmuELEC/EmuELEC#644]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

**Comment by AlienatedDiego** [comment]
Do you mean that the systems folder structure is not shown inside the roms folder?

It looks like something from the sd card or a bad flash; try again . In any case, you must provide more information such as version of EmuELEC and device.
