### ISSUE TITLE
When I played the PSP game LocoRoco2, I got a blurred screen.

### ISSUE THREAD

**Issue by zhendery** [EmuELEC/EmuELEC#648]
Version 4.1 & 4.2
Device S905M
I can play LocoRoco 1 fluently, but not LocoRoco 2.
I can enter and operate in the menu screen. But when I enter the game playing, I got a blurred screen and can do any operations except force quiting.

**Comment by shantigilbert** [comment]
Please post this type of questions on the Forum or Discord
