### ISSUE TITLE
The advanced game settings option disappeared in version 4.2.

### ISSUE THREAD

**Issue by ZOMBIE39** [EmuELEC/EmuELEC#649]
![QQ图片20210624091603](https://user-images.githubusercontent.com/37724369/123184032-cc8b5680-d4cd-11eb-95f6-9adad8c8130f.jpg)
Because English is not good, so I use the translation website.
The hardware is oga1.0. This option is still available in 4.1. I use img.gz image.

**Comment by shantigilbert** [comment]
Press and hold the A button
