### ISSUE TITLE
Force update doesn't work in 4.1

### ISSUE THREAD

**Issue by dsfghedhtehj34typu5re5rgewh** [EmuELEC/EmuELEC#662]
I have no way to update or downgrade from 4.1 using the force update method.

Normal update doesn't work either.

I am stuck.

**Comment by dsfghedhtehj34typu5re5rgewh** [comment]
It will save the metadata, delete the 4.2 tar in .update and then start emulationstation again.

**Comment by shantigilbert** [comment]
Please either fill out the issue template properly if its a reproducible issue or use discord or the forum for these issues, this is not a bug but user error!

**Comment by dsfghedhtehj34typu5re5rgewh** [comment]
So i can't update or fill out the issue template properly.

Fuck this.. the games are old anyway...
