### ISSUE TITLE
351Files was successfully built, but could not be run. 

### ISSUE THREAD

**Issue by wolflink2021** [EmuELEC/EmuELEC#671]
351Files was successfully built, but could not be run. 
Prompt 
"Rga built version:1.04 2134dde+2021-05-29 16:28:45
SDL_image could not initialize! IMG_GetError: JPEG images are not supported"

**Comment by shantigilbert** [comment]
How are you compiling it and what device are you using it in? I tested it on all of the devices and it works for me

**Comment by wolflink2021** [comment]
I deleted and recompiled SDL2_image, and it is ready to run.
