### ISSUE TITLE
Several emulators don't work

### ISSUE THREAD

**Issue by 6david99** [EmuELEC/EmuELEC#672]
In Emuelec 4.2:

ResidualVM - don't work
ScummVM - emulator Scummvmsa no controller response
SPECTRUM - no virtual keyboard
Amstrad GX4000 - no show in emulationstation
File manager - in emulationstation menu press F1 don't work
Wii - no controller config

**Comment by shantigilbert** [comment]
Can you please follow the issue templates?

**Comment by 6david99** [comment]
anyone who downloads the latest version 4.2 and tries it will see that it does not work, it is not my problem, it is a general problem

**Comment by shantigilbert** [comment]
Never said it was your problem I said you need to fill in the template... I have no idea what gamepad, what device, or anything else. 

The only one that is "general" is this, "Wii - no controller config" as it is a known issue. the others I will ignore until you provide logs, or fill out the template.  no logs, no problem.

**Comment by 6david99** [comment]
I'm sorry I don't know how to fill in the ticket, I have already mentioned the problems, if anyone is curious you can see it, it is not with any gamepad, the errors are with the keyboard.

**Comment by shantigilbert** [comment]
OK, well when you feel like helping out so I can help you, feel free to reopen the ticket.
