### ISSUE TITLE
Build openssl failed

### ISSUE THREAD

**Issue by keeno1982** [EmuELEC/EmuELEC#673]
BUILD      openssl (host)
    TOOLCHAIN      configure
Can't locate ExtUtils/MM.pm in @INC (you may need to install the ExtUtils::MM module) (@INC contains: /home/dietpi/emu64/build.EmuELEC-Amlogic.arm-4.2/openssl-1.1.1k/.x86_64-linux-gnu/util/perl /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl/5.28/ExtUtils/MakeMaker.pm line 50.
Compilation failed in require at /usr/share/perl/5.28/IPC/Cmd.pm line 235.
Configuring OpenSSL version 1.1.1k (0x101010bfL) for linux-x86_64
Using os-specific seed configuration
FAILURE: scripts/build openssl:host has failed!
[017/412] [FAIL] build   openssl:host

The following logs for this failure are available:
  stdout: /home/dietpi/emu64/build.EmuELEC-Amlogic.arm-4.2/.threads/logs/17/stdout
  stderr: /home/dietpi/emu64/build.EmuELEC-Amlogic.arm-4.2/.threads/logs/17/stderr

parallel: This job failed:
package_worker 2 17 412 'build openssl:host'
Parallel build failure - see log for details. Time of failure: Fri Jul 23 16:22:33 CST 2021
make: *** [Makefile:12: image] Error 1

**Comment by shantigilbert** [comment]
I will repeat what I have said before I have never compiled it using dietpi, so all these errors are not something I can help you with, I use Ubuntu and I do not have any issues since the build system is made to be used there.
