### ISSUE TITLE
EmuELEC v4.2 , no wifi.

### ISSUE THREAD

**Issue by Gods69** [EmuELEC/EmuELEC#679]
**Describe the bug**
No Wi-Fi

**EmuELEC version:**
 - Version 4.2

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
 - SOC: S905x3
 - Brand: TT TV BOX
 - Model X96 Max plus 2
 - Version 4GB Ram, 64 GB flash, 1Gbit Rj45

**Additional context**
Use one "Fn-Link 6222B-SRB" module, RTL8822BS chipset i think.

![IMG_20210723_094138664](https://user-images.githubusercontent.com/54769290/126914040-a0d89530-dda3-47ba-b125-f77927942172.jpg)

**Comment by shantigilbert** [comment]
Please do a search for x96 on this issues, there is no fix for your chiptset, use a usb dongle, or ethernet. 

Also read: https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices

```
SPECIAL NOTE: Recently the market has been flooded with cloned/generic TV boxes that use known names like X88, H96, X96, S96, T95, with sub-models like king/Mini/Pro/Max/Max+/Pro+. These devices use many different internals, your device will most likely boot to EmuELEC but some of them are not even using Amlogic SOC and some of them are not compatible with EmuELEC at all. If your device does boot into EmuELEC, note that you will most likely run into some problems, from WiFi/Ethernet not working, to the device not booting at all, so buyer beware.
```
