### ISSUE TITLE
[EmuELEC 4.2][Amlogic-ng] Gamepad not recognised 4 of 5 times after reboot on Vontar X3

### ISSUE THREAD

**Issue by JohanBrwrts** [EmuELEC/EmuELEC#686]
**Describe the bug**
After starting / rebooting the Gamepad ("Retroflag Classic USB Gamepad UPad" or "Retroflag Classic USB Gamepad MPad") are not working. 
Disconnecting the Gamepad and reconnecting the gamepad may solve the problem (1 time out of 5 attempts).
Sometimes, lsusb does not show the Gamepad.
If lsusb shows the Gamepad and the gamepad is not working, dmesg shows one of two possible errors: 
    usb 1-2: can't set config #1, error -110 (on the USB2.0 port)
    usb 1-1: can't set config #1, error -71 (on the USB3.0 port)

**To Reproduce**
Install Version 4.2, connect Gamepad and configure Gamepad (if it is recognised).
Reboot system and check if Gamepad is working.

**Expected behavior**
Controls/Gamepads are working fine after a reboot / shutdown

**Screenshots** 
none

**EmuELEC version:**
 - Version [4.2]

**Device (please complete the following information):**
 - SOC: S905X3
 - Brand: Vontar
 - Model X3
 - Version 4 GB RAM / 32 GB ROM
 - firmware: PPR1.180610.011release-keys<20201116_1048>
 - (PCB mentions HK1_S905X3_4BIT_V11 2019-11-05)

**Additional context**
    Logs of a successful reboot and a working Gamepad (USB 2.0 port): http://ix.io/3vK2 
    Logs of "usb 1-2: can't set config #1, error -110" after shutdown, remove/reconnect power (USB 2.0 port): http://ix.io/3vK8
    Logs of "usb 1-2: device descriptor read/64, error -71" after rebooting and lsusb not showing the Gamepad (USB 2.0 port) : http://ix.io/3vKc
    Logs of a successful reboot and a working Gamepad (USB 3.0 port): http://ix.io/3vKh
    Logs of "usb 1-1: can't set config #1, error -71" after reboot (USB 3.0 port): http://ix.io/3vKl

**Comment by shantigilbert** [comment]
Thanks for the detailed report. But I don't think this is an EmuELEC problem, it seems to me a problem with your USB controller (or the USB device controller) test on other software to make sure the same thing is not happening.
