### ISSUE TITLE
Cannot set timezone

### ISSUE THREAD

**Issue by MiltonLai** [EmuELEC/EmuELEC#69]
The system time is 16 hours behind my local time, I found /etc/localtime is pointed to /usr/share/zoneinfo/Mexico/General through /var/run/localtime
```
EmuELEC:~ # ll /etc/localtime 
lrwxrwxrwx    1 root     root            18 Dec 21 00:16 /etc/localtime -> /var/run/localtime
EmuELEC:~ # ll /var/run/localtime 
lrwxrwxrwx    1 root     root            34 Dec 26 02:21 /var/run/localtime -> /usr/share/zoneinfo/Mexico/General
```
But if I change /var/run/localtime, it will be restored after reboot.
I found nowhere to set the timezone after I looked through ES and RA. Is there any way to change it?

Thanks!

**Comment by shantigilbert** [comment]
Change it in /emuelec/configs/emuelec.conf

**Comment by MiltonLai** [comment]
It works. Thank you!
