### ISSUE TITLE
master_32bit: SDL and SDL_sound tar.gz files have new checksums

### ISSUE THREAD

**Issue by panreyes** [EmuELEC/EmuELEC#691]
SDL and SDL_sound packages in the current master_32bit branch have different checksums than the tar.gz files.

These are the files that need a checksum update:
SDL : /packages/sx05re/tools/SDL/package.mk
New SHA-256 checksum: c689d626ab6fbc0ed0bd03a49aad6b0af483a6cd5c352cd130e177587e0f97c1

SDL_sound : /packages/sx05re/tools/SDL/SDL_sound/package.mk
New SHA-256 checksum: 2d98c599d8bd120e75a9366d4d5c0b1284fee04cfdae4152898e0950544aa8eb

Sorry for not doing a git pulI, I still need to find time to get used to git :)
Thanks!

**Comment by shantigilbert** [comment]
`master_32bit` is not updated anymore its there for reference, if you want to build it, you will need to do these changes manually.
