### ISSUE TITLE
[EmuELEC 4.2][Amlogic-ng]duckstation link 404 Not Found

### ISSUE THREAD

**Issue by leoliao2021** [EmuELEC/EmuELEC#716]
Compiling the source code of emuelec-4.2 failed.
    FAILURE: scripts/install duckstation has failed!
I try to find package.mk on GitHub and replace it locally, but the same error was reported.
found that this link failed.(https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip)

The detailed error reports are as follows:
FAILURE: scripts/install duckstation has failed!
[425/464] [FAIL] install duckstation
The following logs for this failure are available:
  stdout: /home/leoliao/project/v4.2/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4.2/.threads/logs/417/stdout
  stderr: /home/leoliao/project/v4.2/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4.2/.threads/logs/417/stderr

parallel: This job failed:
package_worker 4 417 464 'install duckstation'
Parallel build failure - see log for details. Time of failure: Fri Sep 17 13:13:06 CST 2021
make: *** [Makefile:12: image] Error 1
leoliao@leoliao-virtual-machine:~/project/v4.2/EmuELEC$ cat /home/leoliao/project/v4.2/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4.2/.threads/logs/417/stdout
config/options duckstation
GET      duckstation (archive)
--2021-09-17 13:11:00--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M   190KB/s    in 38s     

2021-09-17 13:11:45 (104 KB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:11:45--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:11:46--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:11:47 ERROR 404: Not Found.

--2021-09-17 13:11:47--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M   776KB/s    in 5.1s    

2021-09-17 13:11:54 (776 KB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:11:54--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:11:54--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:11:55 ERROR 404: Not Found.

--2021-09-17 13:11:55--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M   990KB/s    in 4.0s    

2021-09-17 13:12:01 (990 KB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:12:01--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:12:01--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:12:02 ERROR 404: Not Found.

--2021-09-17 13:12:02--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M   884KB/s    in 5.1s    

2021-09-17 13:12:09 (786 KB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:12:09--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:12:10--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:12:11 ERROR 404: Not Found.

--2021-09-17 13:12:11--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M   969KB/s    in 4.1s    

2021-09-17 13:12:18 (969 KB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:12:18--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:12:19--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:12:20 ERROR 404: Not Found.

--2021-09-17 13:12:20--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M   724KB/s    in 5.5s    

2021-09-17 13:12:27 (724 KB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:12:27--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:12:27--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:12:29 ERROR 404: Not Found.

--2021-09-17 13:12:29--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M  1.12MB/s    in 3.5s    

2021-09-17 13:12:34 (1.12 MB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:12:34--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:12:34--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:12:35 ERROR 404: Not Found.

--2021-09-17 13:12:35--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M   423KB/s    in 12s     

2021-09-17 13:12:49 (331 KB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:12:49--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:12:49--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:12:50 ERROR 404: Not Found.

--2021-09-17 13:12:50--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M   892KB/s    in 4.5s    

2021-09-17 13:12:56 (892 KB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:12:56--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:12:57--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:12:58 ERROR 404: Not Found.

--2021-09-17 13:12:58--  https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Resolving www.duckstation.org (www.duckstation.org)... 45.63.29.71
Connecting to www.duckstation.org (www.duckstation.org)|45.63.29.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4076978 (3.9M) [application/zip]
Saving to: '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip'

/home/leoliao/proje 100%[===================>]   3.89M   900KB/s    in 4.4s    

2021-09-17 13:13:04 (900 KB/s) - '/home/leoliao/project/v4.2/EmuELEC/sources/duckstation/duckstation-200fb85f.zip' saved [4076978/4076978]

    WARNING      Incorrect checksum calculated on downloaded file: got 5c0563c1ca68b099c3936097f132a737ad6e270a90198743e45acc3f1cbd8830 wanted 1b4a0038e208a1c9a0938f34c52eb09313f89fbb228380fc36b21b3c109548d8
--2021-09-17 13:13:04--  http://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip [following]
--2021-09-17 13:13:04--  https://sources.libreelec.tv/mirror/duckstation/duckstation-200fb85f.zip
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-17 13:13:05 ERROR 404: Not Found.

Cannot get duckstation sources : https://www.duckstation.org/libretro/duckstation_libretro_linux_aarch64.zip
Try later!

**Comment by shantigilbert** [comment]
Please compile dev branch, this is already fixed...if you don't want to compile dev branch then look for the fix in that branch
