### ISSUE TITLE
confuse about cpufreq/scaling_available_frequencies

### ISSUE THREAD

**Issue by keeno1982** [EmuELEC/EmuELEC#72]
S905L can force work max_freq 2.016Ghz on android, but on EmuELEC/CoreELEC only work max_freq on 1.56Ghz, why? 
![20191230202314](https://user-images.githubusercontent.com/13664097/71582009-17c7e180-2b43-11ea-9c4d-fc911d3464be.png)
![20191230202301](https://user-images.githubusercontent.com/13664097/71582010-18607800-2b43-11ea-99df-f6c5e9d55d5e.png)

**Comment by shantigilbert** [comment]
Are you sure that when you set 2.016 ghz it is actually running at 2.016 ?

**Comment by keeno1982** [comment]
@shantigilbert Yes, I can check it work on 2.016 ghz by cpu-z. And then I run some DC emu games like DOA2, it more smoother than force set 1.536 ghz.

**Comment by keeno1982** [comment]
![20191231_042810](https://user-images.githubusercontent.com/13664097/71600663-f68ae380-2b8a-11ea-91fd-c6323214035b.jpg)

**Comment by shantigilbert** [comment]
What DTB are you using ?

**Comment by keeno1982** [comment]
gxl_p212_1g.dtb or gxl_p281_1g.dtb

**Comment by shantigilbert** [comment]
Sorry I am not sure what is going on, the dtb has the correct info AFAIK

`max-frequency = <200000000>;`

But I am surprised it even works on S905L as the p211 is not in the Linux Kernel so that might be the problem.

**Comment by keeno1982** [comment]
@shantigilbert I had decompiled  gxl_p212_1g.dtd and get gxl_p212_1g.dts, if possibly to change some parameters about cpu max_freq and let it work on 2.016 ghz? gxl_p212_1g.dts contains many parameters and I don't know what should I modify. Can you help me to point out it or make a new one?

**Comment by shantigilbert** [comment]
Unfortunately I do not know how to make a dtb for a device.

**Comment by asakous** [comment]
I am not sure it's related to https://forum.odroid.com/viewtopic.php?t=23044&start=50, but worth to know.

**Comment by shantigilbert** [comment]
@asakous that is something I've read before, which is why I asked him if he noticed any difference... he claims yes, but I don't think the CPU is running at 2ghz

**Comment by shantigilbert** [comment]
@keeno1982 I am closing this as the link that @asakous shared proves that the CPU doesn't really go over 1.5ghz, if you find any other information feel free to reopen
