### ISSUE TITLE
EMUELEC 4.2 Can't boot from MicroSD.

### ISSUE THREAD

**Issue by phantoma13** [EmuELEC/EmuELEC#727]
Hi everybody
I have a x96 Max+ tv box that has s905x3 2 GB RAM Not the gigabit version
I can't boot to EMUELEC from MicroSD, I think I'm using the right DTB because the device succesfully boots if I use a USB Flash Drive instead of the MicroSD. The attached screen is the result of trying to boot from MicroSD

Could anyone help me please? I bought this device because I read that was compatible.

Thanks in advance

![image](https://user-images.githubusercontent.com/91387734/134781482-5301d7d0-ab93-4ba7-bea3-b51b717452fb.png)

**Comment by shantigilbert** [comment]
file:///android_asset/md/#about-cheap-devices

**Comment by british-choi** [comment]
The attached screen is the result of trying to boot from MicroSD? where?

**Comment by phantoma13** [comment]
> The attached screen is the result of trying to boot from MicroSD? where?

Sorry, i didn't notice i used the wrong picture.
