### ISSUE TITLE
The link mode does not allow each game to have its own configuration, and it is recommended to restore the copy mode.

### ISSUE THREAD

**Issue by wolflink2021** [EmuELEC/EmuELEC#729]
https://github.com/EmuELEC/EmuELEC/blob/3a1dac2e6235300a60cb854cef42eacb67c161b4/packages/sx05re/emulators/openbor/scripts/openbor.sh#L26

The link mode does not allow each game to have its own configuration, and it is recommended to restore the copy mode.

cp -rf "${CONFIGDIR}/master.cfg" "${SAVES}/${pakname}.cfg"

**Comment by shantigilbert** [comment]
Can you elaborate as to what settings need to be unique per game? all the ones I have seen share the same settings as they are provided by the emulator...

**Comment by wolflink2021** [comment]
All right, suit yourself！

**Comment by shantigilbert** [comment]
???
