### ISSUE TITLE
Intro video not working on S912/PK7

### ISSUE THREAD

**Issue by Oberworld** [EmuELEC/EmuELEC#73]
Hi, merry christmas, intro video is not working, seems it's a wrong path in \\EMUELEC\Storage\.config\emuelec\scripts\show_splash.sh.

The lines from 12 to 14:

`GAMELOADINGSPLASH="/storage/.config/splash/loading-game.png"
 DEFAULTSPLASH="/storage/.config/splash/splash-1080.png"
 VIDEOSPLASH="/usr/config/splash/emuelec_intro_1080p.mp4"`

But the intro video is in "/storage/.config/splash/emuelec_intro_1080p.mp4"

I have edit show_splash.sh pointing to the right path but intro video still not working.

My best regards, sorry my poor english.

**Comment by shantigilbert** [comment]
Every time I do a release the version goes into the test server, and I personally test it on 9 different devices, and nobody else seems to have this problem. so I am 99% sure this is something on your end, without more information I do not know why this problem is happening. 

Path is not the problem

**Comment by Oberworld** [comment]
I did a 3.2 fresh install in my pandora key 7.
If you need more info I'm pleased to help you.
Regards.

**Comment by shantigilbert** [comment]
well I see no problem with the intro video, so it is something on your side, not sure what error you are getting, try enabling the option to always show intro video and reboot

**Comment by shantigilbert** [comment]
Pk7/s912 seems to have problems with the recent changes to the splash, for the moment I do not intend to fix this, but maybe in the future I will try to find a solution that is suitable for S912 as well, sorry

**Comment by futxi** [comment]
A mi tampoco se me ve el video de introducción de pk7, me pasa lo mismo.
Si encontráis alguna manera lo comunicáis. 
Gracias

**Comment by Oberworld** [comment]
Thanks for your answer, it's good to know that is not my fault.
I hope you can spend some time in the future to fix this little (but not important) issue.
Again, thanks for your great work.
Regards.

**Comment by shantigilbert** [comment]
I think I just figured out a way to make this work, next release will probably have this fixed (if all tests go as I plan).
