### ISSUE TITLE
Emuelec Error: Error in mount_sysroot

### ISSUE THREAD

**Issue by linhduonghg** [EmuELEC/EmuELEC#732]
i got and error after install MMC into TVbox (Gamebox G5/D905, Amlogic S905L, and use tree type P281_1G281 core ): ***Error is mount_sysroot: mount_common: COuld not mount /flash/SYSTEM***
*** Starting debugging shell for boot step: mount sysroot...type exit to quit***
Anyone can fix this, tks so much
* Picture of this error:
https://ibb.co/s92gRLS
https://ibb.co/KFBvn6w

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices#special-note
