### ISSUE TITLE
A95X F3 Air Wi-Fi / Bluetooth not working 

### ISSUE THREAD

**Issue by Amphil13** [EmuELEC/EmuELEC#733]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!

On the device info page it says :
Network info
Loopback interface status : unknown
Ethernet connection status : down
Wireless connection status : down
How do I fix this
I am using A95X F3 Air box with Amlogic S905X3 SoC and 4GB RAM
I need help

**Comment by shantigilbert** [comment]
Please read the template instructions.
https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices#about-cheap-devices
