### ISSUE TITLE
File retroarch.cfg changes

### ISSUE THREAD

**Issue by andygil93** [EmuELEC/EmuELEC#734]
When I open the file retroarch.cfg located in root/usr/config/retroarch/retroarch.cfg sometimes shows a file like the first image A but in other moments open a file like the second one B. I don't understand why the file is changing, it is in the same location and it has the same name. I'm trying to set up an autoconfig file for the joypads. When I select the option "Reset retroarch config to default" nothing happens, I've tried to modify the retroarch.cfg file, but it doesn't work. 

The changes that I've done in file A were specified in the images K to L and M to N.

The changes that I've done in file B were specified in the images C to D, E to F, G to H and I to J.

![A](https://user-images.githubusercontent.com/91346459/136286011-379e0e61-7b50-4aeb-8869-06049af90718.PNG)
![B](https://user-images.githubusercontent.com/91346459/136286027-18d79976-eaac-4e8b-8fdc-c87e9dfe806a.PNG)

![K](https://user-images.githubusercontent.com/91346459/136290508-da0a17fe-ddab-4c6a-ae16-8387fa5d0108.PNG)
![L](https://user-images.githubusercontent.com/91346459/136290513-ba8ff238-3b4a-4db1-bb57-ca01a2d6a9d2.PNG)

![M](https://user-images.githubusercontent.com/91346459/136290519-1cb86f5c-b49a-4498-b840-e7b25f4dbd34.PNG)
![N](https://user-images.githubusercontent.com/91346459/136290528-7ea3550a-36b4-4214-975a-85395f8053cf.PNG)

![C](https://user-images.githubusercontent.com/91346459/136290540-b9a13785-010f-4090-afcd-b1c057dcc57b.PNG)
![D](https://user-images.githubusercontent.com/91346459/136290543-b88d4c2c-f953-4141-86e8-ef261bdd35f1.PNG)

![E](https://user-images.githubusercontent.com/91346459/136290548-36ea5944-b5c1-42fc-90ed-52db8f31d951.PNG)
![F](https://user-images.githubusercontent.com/91346459/136290558-638d48e3-518f-4953-9048-dd7bfab42e6c.PNG)

![G](https://user-images.githubusercontent.com/91346459/136290565-c0dd8476-7a59-4b37-94d4-119a8446e696.PNG)
![H](https://user-images.githubusercontent.com/91346459/136290574-f9fc0de9-6a8e-47e0-b78b-a5626fdfd442.PNG)

![I](https://user-images.githubusercontent.com/91346459/136290580-04b89658-ae57-4dda-b8ea-8325ae8ed84d.PNG)
![J](https://user-images.githubusercontent.com/91346459/136290585-d50a8fcc-03ec-475e-8e6f-1e02d26a7bf5.PNG)

Thanks for the answers.

**Comment by shantigilbert** [comment]
> I'm trying to set up an autoconfig file for the joypads.

Please don't, EmuELEC does NOT work like that, you are most likely going to break the gamepad configuration on other emulators and ES. 

But if you insist, **under your own responsibility**

> `root/usr/config/retroarch/retroarch.cfg`

this is a read only path, nothing is going to happen on that file. 
`/storage/.config/retroarch/retroarch.cfg` is what you want.

**Comment by AltPlus30** [comment]
> Please don't, EmuELEC does NOT work like that, you are most likely going to break the gamepad configuration on other emulators and ES.

It doesn't break anything, actually. If you know what buttons do you can at least remove useless hotkeys. Also, RA hotkeys should be configurable in ES menu or at least shouldn't be preconfigured in a weird way.
I would recommend OP using autoconfig file located in /tmp/joypads since any changes to configuration in retroarch.cfg can be easily overwritten by some frontend-voodoo-magic.
