### ISSUE TITLE
PSP doesnt exit

### ISSUE THREAD

**Issue by chenteparao** [EmuELEC/EmuELEC#74]
HI, I installed for first time Emuelec and is awesome the performance for PSP but i have a problem, when I press start + hotkey doesnt exit, but all of emulators yes.

Emuelec generic

X96mini with 2gb

Thanks

**Comment by shantigilbert** [comment]
Ppsspp has its own menu, depends on your game pad, in my case it's the middle button (xbox controller)

**Comment by chenteparao** [comment]
So, if I set any button to exit, can I exit?

**Comment by shantigilbert** [comment]
yes, from the PPSSPP menu itself
