### ISSUE TITLE
[Emuelec 4.3] Slowdown in Streets of Rage Remake - SORR

### ISSUE THREAD

**Issue by moisesvgomes** [EmuELEC/EmuELEC#740]
I updated emuelec to V.4.3 and while playing SORR, an increasing slowdown is noticeable. At the right time, you need to shut down and restart Sorr, and then the speed returns to normal.

**Comment by Langerz82** [comment]
Which Emulator does it use? In Emulation station select the gamelist, then press select, select Advanced System Options, Native Video and try 640x480.
The emulator might also have a clock setting in retroarch but I am not sure which emulator you are using.

**Comment by shantigilbert** [comment]
> The port is running on RK2020

Please read this https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices#special-note
