### ISSUE TITLE
PLEASE,SUPPORT S905L3B ,THANKS.

### ISSUE THREAD

**Issue by wang80919** [EmuELEC/EmuELEC#752]
[E900-V21C-DTB p211 p215 p261 S905L3B p265 p291 p295.zip](https://github.com/EmuELEC/EmuELEC/files/7407017/E900-V21C-DTB.p211.p215.p261.S905L3B.p265.p291.p295.zip)

I found some dts dtb files form internat.
p261 is S905L3B 
P211 is some S905L

if it can  use. please support it.
if can not ,you can  close this issue.
thanks.

**Comment by NERCH-GH** [comment]
I think so. 
Thanks for you support this device.
