### ISSUE TITLE
Please help I can't run drastic games on update 4.3 

### ISSUE THREAD

**Issue by jrm0710** [EmuELEC/EmuELEC#758]
help please i can't run drastic games in 4.3 update on tv box s905x3
 I get this error when running any nds rom

EmuELEC Run Log
##############################################
#                 EmuELEC                    #
#     Retro emulation for Amlogic Devices    #
#             Based on CoreELEC              #
##############################################
EmuELEC (Official - EmuELEC is FREE! NOT FOR SALE!): 4.3 (Amlogic-ng.aarch64)
PLATFORM: nds
ROM NAME: /storage/roms/nds/New Super Mario Bros.nds
BASE ROM NAME: New Super Mario Bros.nds
USING CONFIG: /storage/.config/retroarch/retroarch.cfg
1st Argument: /storage/roms/nds/New Super Mario Bros.nds
2nd Argument: -Pnds
3rd Argument: --core=
4th Argument: --emulator=
Full arguments: /storage/roms/nds/New Super Mario Bros.nds -Pnds --core= --emulator= --controllers=-p1index 0 -p1guid 050000004c050000cc09000000010000 
Run Command is:
/usr/bin/bash /storage/.emulationstation/scripts/drastic.sh /storage/roms/nds/New Super Mario Bros.nds
Emulator Output is:
[H[Jexit 127

how can I solve that?

**Comment by shantigilbert** [comment]
# PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!
