### ISSUE TITLE
X96 Max Plus - 3.5 mm Audio Jack Error

### ISSUE THREAD

**Issue by rnadesignlab** [EmuELEC/EmuELEC#764]
Dear EmuElec Team,

Many Thanks for supporting the X96 Max Plus. The new update (EmuElec 4.3) just works flawlessly. We have the opengl es 3.2, wifi and also bluetooth working out of the box. However, I just noticed that the Audio has a problem. I noticed that my 3.5mm Audio Jack does not work. I also tried using the USB Soundcard, but it was not detected and does not work as well. 

This issue is very important for us, especially for someone that does have a built in speaker via HDMI monitor. Could you please support this in the future?

Many Thanks,
rna

**Comment by shantigilbert** [comment]
EmuELEC Settings > AUDIO DEVICE > 0,1, SAVE, reboot
