### ISSUE TITLE
adaptive resolution not support?

### ISSUE THREAD

**Issue by keeno1982** [EmuELEC/EmuELEC#769]
I bought a 4:3 monitor dell 2007fpb, resolution ratio is 1600x1200. But I get a black screen when start, massgae is Resolution mismatch. I don't know how to change the resolution in emuelec. I use retropie on pi, the monitor work normal.

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/604

**Comment by keeno1982** [comment]
Sorry, I think it maybe a bug or a improment,  adaptive resolution is friendly for low resolution monitor and TV. When I first time boot emu system, it's black screen. Then I had tried 1600x1200, 1024x768 and other 4:3 aspect ratio and the result is black screen too. Only 720P worked, that's strange.
