### ISSUE TITLE
[BUG] IP address in footer does not update until you close and reopen the menu

### ISSUE THREAD

**Issue by gingerbeardman** [EmuELEC/EmuELEC#776]
### Describe the bug
IP address in footer does not update until you close and reopen the menu

### To Reproduce
1. Press start to open menu
2. Choose Network settings
3. Switch on wifi
4. look at IP address in footer, it doesn't change

### Workaround
1. press start to close menu
2. press start to open menu

### Informations
 - LE Version: 4.3
 - Hardware Platform: Gameforce Chi

**Comment by shantigilbert** [comment]
Not a bug, this is expected.

**Comment by gingerbeardman** [comment]
Then I would say this is misleading as it makes it seem like wifi toggle/connect isn't working.

**Comment by shantigilbert** [comment]
You can say whatever you like, nowhere is this promised as a feature, so nobody is "misleading" anyone. 

The fact is that not many people are connecting and disconnecting their network just to see if the IP changes, it takes 2 button presses, or less than 1 second to refresh the screen, if you think this is wrong or you don't like it then I welcome PRs with your code to refresh screen every time something in the background happens.

**Comment by gingerbeardman** [comment]
It's not a big deal. Take it easy

**Comment by gingerbeardman** [comment]
BTW I meant the out-of-date information in the display was misleading. I wasn't referring to any person, so please don't take it that way.

**Comment by shantigilbert** [comment]
No problem, all good 👍
