### ISSUE TITLE
[BUG] No key repeat on soft keyboard

### ISSUE THREAD

**Issue by gingerbeardman** [EmuELEC/EmuELEC#777]
### Describe the bug
No key repeat on soft keyboard

### To Reproduce
1. Open something that requirs keyboard (eg. Scraper username)
2. Press and hold right on dpad

### Expected
- cursor should move continuously

### Actual
- cursor moves only once

### Informations
 - LE Version: 4.3
 - Hardware Platform: Gameforce Chi

**Comment by shantigilbert** [comment]
Already fixed in dev

**Comment by gingerbeardman** [comment]
Thanks. 

So to get this shall I update to beta? Or some other way? Or wait?
