### ISSUE TITLE
[BUG] emuelec_copy_roms_from_here cannot copy roms from previous emuelec microsd

### ISSUE THREAD

**Issue by emuchicken** [EmuELEC/EmuELEC#778]
### Describe the bug
having the file emuelec_copy_roms_from_here next to all the roms, on a previous emuelec installation/ microsd will not copy them over when using the script on emuelec

### To Reproduce
Load up emuelec
Insert USB with emuelec / eeroms *with emuelec_copy_roms_from_here next to the roms folders
Load up script from the tools menu

### Informations
905x3, pretty sure it's non-system-specific
By newly creating a roms folder, then moving all the folders from eeroms (with the emuelec_copy_roms_from_here), and THEN starting the script- the roms will copy over correctly.
Pretty sure it just needs to check for an additional place.

**Comment by shantigilbert** [comment]
Can you provide more information as to what you mean with previous installation? do you also have an "emuelecroms" file in the ROMS folder? 

> Insert USB with emuelec / eeroms *with emuelec_copy_roms_from_here next to the roms folders

The file should be INSIDE the roms folder, not next to, like the instructions here: https://github.com/EmuELEC/EmuELEC/wiki/Copy-ROMS-from-external-USB-SD-to-EmuELEC
