### ISSUE TITLE
[BUG] Notification of update even though I'm on 4.3 stable

### ISSUE THREAD

**Issue by gingerbeardman** [EmuELEC/EmuELEC#779]
### Describe the bug

Notification of update even though I'm on 4.3 stable. 

### To Reproduce
1. Update to 4.3 stable
2. Power cycle device
3. Update available notification is displayed 

### Informations
 - LE Version: 4.3 stable
 - Hardware Platform: CHI

### Additional context

I did a second update just in case something has changed, but the banner is still being displayed afterwards.

**Comment by shantigilbert** [comment]
I will take a look at this, this was supposed to be fixed and nobody else has reported it, so not sure what is going on.

**Comment by gingerbeardman** [comment]
Video: https://imgur.com/MZcr6UR

**Comment by countbuggula** [comment]
I'm seeing this happen too, on my N2+

**Comment by linkous8-2** [comment]
Ditto for OGA-BE

**Comment by jpsutton** [comment]
Also observed on Odroid C4.

**Comment by snakect77** [comment]
Idem amlogic s903

**Comment by shantigilbert** [comment]
This bug has been confirmed and its fixed on dev.
