### ISSUE TITLE
[BUG] WiFi toggle incorrect after restart

### ISSUE THREAD

**Issue by gingerbeardman** [EmuELEC/EmuELEC#780]
### Describe the bug

WiFi toggle incorrect after restart

### To Reproduce
1. Toggle wifi off
1. Power off device
1. Charge device
1. Power device back on
1. Check network settings

### Expected
- Toggle should be off
- WiFi should be off

### Actual
- Toggle is off
- WiFi is on

### Informations
 - LE Version: 4.3 stable
 - Hardware Platform: CHI

### Screenshot
- ![](https://i.imgur.com/cBhxiKv.jpg)

**Comment by gingerbeardman** [comment]
WiFi also switches itself back on in other circumstances.

**Comment by Langerz82** [comment]
Might need the following line:
```
SystemConf::getInstance()->saveSystemConf();
```
after the lines that contain:
```
SystemConf::getInstance()->setBool("wifi.enabled", wifienabled);
```
So it saves immediately to the file.
I might create a mini patch after some other changes have been pushed.

**Comment by gingerbeardman** [comment]
I found that WiFi was on inside RetroArch by default, I switched it off there and all seems well.

It would be ideal if the RetroArch setting synced with the ES system setting.

**Comment by shantigilbert** [comment]
> It would be ideal if the RetroArch setting synced with the ES system setting.

This seems like something that should be doable. I'll see what I can do.
