### ISSUE TITLE
Configuration menu not accessible in Retrorun Flycast Core on Odroid Go Advance

### ISSUE THREAD

**Issue by groovey2k** [EmuELEC/EmuELEC#781]
When using Odroid Go Advance with Retrorun/Flycast there is no possibility to enter a configuration menu for setting key mapping or transparent sorting (Per Triangle/Per Strip).

### Steps to reproduce

- using Emulation Station choose Rom and hold A button
- configure to use RETRORUN/FLYCAST as emulator in Advanced settings
- no configuration options other than "RGA Scaling" and "Enable Max Performace" appear directly in Emulation Station
- after starting Rom no hotkeys are available to configure emulator

### Expected behaviour

- either in Emulation Station or via Hotkey user is able to configure key mapping and and transparent sorting as well as further options of emulator

**Comment by shantigilbert** [comment]
At the moment, there are no options for retrorun to set.
