### ISSUE TITLE
[BUG] No possibility to configure Retrorun Flycast Core

### ISSUE THREAD

**Issue by groovey2k** [EmuELEC/EmuELEC#782]
When using Odroid Go Advance with Retrorun/Flycast there is no possibility to enter a configuration menu for setting key mapping or transparent sorting (Per Triangle/Per Strip).

### Steps to reproduce

- using Emulation Station choose Rom and hold A button
- configure to use RETRORUN/FLYCAST as emulator in Advanced settings
- no configuration options other than "RGA Scaling" and "Enable Max Performace" appear directly in Emulation Station
- after starting Rom no hotkeys are available to configure emulator

### Expected behaviour

- either in Emulation Station or via Hotkey user is able to configure key mapping and and transparent sorting as well as further options of emulator

### Informations
 - EMUELEC Version 4.3
 - Hardware Platform: Odroid Go Advance Rev. 1.1

**Comment by SamuEDL** [comment]
Yesterday they answered you here: https://github.com/EmuELEC/EmuELEC/issues/781

**Comment by groovey2k** [comment]
Sorry, I thought I did a mistake!
Thanks for the information.
