### ISSUE TITLE
Failed to mount assets directory when booting

### ISSUE THREAD

**Issue by wolflink2021** [EmuELEC/EmuELEC#792]
https://github.com/EmuELEC/EmuELEC/blob/7d51b8e7105c9bad63c8866554071e16b72b08c0/packages/sx05re/libretro/retroarch-assets/package.mk#L36
Failed to mount assets directory when booting. I added "mkdir -p $INSTALL/usr/share/retroarch-assets" in mk file and it worked.

**Comment by shantigilbert** [comment]
Not sure I understand, but this has nothing to do with booting... 

`
make install
`

Should automatically creates the necessary folders. And this package has been used like that since it was introduced, so I am sure it works.
