### ISSUE TITLE
neogeo game failed

### ISSUE THREAD

**Issue by zhangguanzhang** [EmuELEC/EmuELEC#797]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!
![image](https://user-images.githubusercontent.com/18641678/150647282-d2aa15ac-8e7e-43c7-a4b8-9b61536439cc.png)
![image](https://user-images.githubusercontent.com/18641678/150647294-5c8b91dc-dccb-4e02-9819-40fd7fac340b.png)
![image](https://user-images.githubusercontent.com/18641678/150647309-7fcf0cdd-bb23-4b51-b74d-17ba4bb1df49.png)

```
# cat /etc/os-release 
NAME="EmuELEC"
VERSION="4.0"
ID="coreelec"
VERSION_ID="9.2"
PRETTY_NAME="EmuELEC (Official - EmuELEC is FREE! NOT FOR SALE!): 4.0"
HOME_URL="https://github.com/EmuELEC"
BUG_REPORT_URL="https://github.com/EmuELEC/EmuELEC"
BUILD_ID="597b8729000c4d53cc036e36b015aae1a66693da"
OPENELEC_ARCH="Amlogic.aarch64"
LIBREELEC_ARCH="Amlogic.aarch64"
COREELEC_ARCH="Amlogic.aarch64"
COREELEC_BUILD="Official - EmuELEC is FREE! NOT FOR SALE!"
COREELEC_PROJECT="Amlogic"
BUILDER_VERSION="4.0"
```
game file:
[neobombe.zip](https://github.com/EmuELEC/EmuELEC/files/7918737/neobombe.zip)

**Comment by zhangguanzhang** [comment]
[neobombe.zip](https://github.com/EmuELEC/EmuELEC/files/7918747/neobombe.zip)
I use the file will be ok

**Comment by shantigilbert** [comment]
Sorry was I not clear last time? DO NOT POST ROMS!!!!!
