### ISSUE TITLE
mame mage "grdians" cannot play

### ISSUE THREAD

**Issue by zhangguanzhang** [EmuELEC/EmuELEC#798]
# BEFORE YOU OPEN AN ISSUE MAKE SURE IT IS NOT ALREADY RESOLVED IN THE WIKI https://github.com/EmuELEC/EmuELEC/wiki

# MAKE SURE YOUR DEVICE IS A [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices)  

# PLEASE DO NOT POST GENERAL HELP QUESTIONS! EITHER USE THE FORUM (https://emuelec.org) OR USE DISCORD FOR THAT (https://discord.gg/cbgtJTu), THIS IS ONLY FOR BUG/ISSUES REPORTING!

# DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!
![image](https://user-images.githubusercontent.com/18641678/150648195-6e15843b-3198-407e-9e45-b4fba2062252.png)
```
# cat /etc/os-release 
NAME="EmuELEC"
VERSION="4.0"
ID="coreelec"
VERSION_ID="9.2"
PRETTY_NAME="EmuELEC (Official - EmuELEC is FREE! NOT FOR SALE!): 4.0"
HOME_URL="https://github.com/EmuELEC"
BUG_REPORT_URL="https://github.com/EmuELEC/EmuELEC"
BUILD_ID="597b8729000c4d53cc036e36b015aae1a66693da"
OPENELEC_ARCH="Amlogic.aarch64"
LIBREELEC_ARCH="Amlogic.aarch64"
COREELEC_ARCH="Amlogic.aarch64"
COREELEC_BUILD="Official - EmuELEC is FREE! NOT FOR SALE!"
COREELEC_PROJECT="Amlogic"
BUILDER_VERSION="4.0"
```
game rom file:
[grdians.zip](https://github.com/EmuELEC/EmuELEC/files/7918775/grdians.zip)

**Comment by shantigilbert** [comment]
Please, do not open this kind of issues here, use discord or the forum, and PLEASE do not share ROMS!

**Comment by zhangguanzhang** [comment]
😢ok
