### ISSUE TITLE
How to shorten the 90 secs waiting time while using systemd mounting a disk.

### ISSUE THREAD

**Issue by edouardlicn123** [EmuELEC/EmuELEC#807]
Hello everyone.

I am successfully mount a drive to  /storage/roms and automatically start using the customstart script.Now I am facing a problem that every time it boot it shows a job starting and need to wait 90 secs.How can I set the timeout waiting time?

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/604
