### ISSUE TITLE
Retroarch SaveRAM Autosave Interval is off by default

### ISSUE THREAD

**Issue by Azuredragon48** [EmuELEC/EmuELEC#809]
Retroarch's SaveRAM Autosave Interval option is entirely disabled by default, which automatically saves a game's save data to a file at a set interval. While it does save on exit, this means that if power is lost, such as when the battery dies on a handheld, the save will be lost. Which is unfortunately what happened to me after nearing the end of a game in one sitting.

This seems to be the default setting for Retroarch normally, and makes sense for a lot of systems Retroarch is on, as it's a lot less likely for power to suddenly be cut to a proper PC or a console, but considering EmuELEC's focus on handhelds with batteries as well as SBCs that are generally easy to pull the plug on, it feels to me like this should be enabled by default. A "low battery" message would be appreciated as well, if possible.

Setting is in Settings > Saving > SaveRAM Autosave Interval, in the XMB menu at least. I don't know how consistent that is. I'm using an OGA BE, and I installed about half a year ago, now fully up to date, if that changes anything.

Apologies if this has already been brought up / was fixed in a version after the one I installed, I did my best to search the issues and didn't find anything, and I don't have the internet speed or a spare SD card to check the newest image.

**Comment by shantigilbert** [comment]
Sorry but this seems to be a personal preference setting, and you have figured out how to enable it. As far as I can tell, it is not enabled on RA by default. 

You can see the only changes I do to the Retroarch settings here https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/libretro/retroarch/package.mk#L114

I know from experience now that many people rather not have something writing on the SD card at all times, so its up to them to enable this or not, the setting will be saved permanently when you change it as there is no (as afar as I know) other place where this setting is changed.
