### ISSUE TITLE
Versión 3.3 invented colors bug 

### ISSUE THREAD

**Issue by Carlosaleqwe** [EmuELEC/EmuELEC#81]
![806625982_360135](https://user-images.githubusercontent.com/59778643/72315193-ec271a00-365f-11ea-80f0-0af3aba2bcf4.jpg)

Versión 3.3

**Comment by shantigilbert** [comment]
Edit config.ini on the first partition and un-comment this line

# use_rgb_to_yuv=0

**Comment by Carlosaleqwe** [comment]
It doesnt work 
![15789825994497915334886228921820](https://user-images.githubusercontent.com/59778643/72318897-935d7e80-366b-11ea-8657-2be24baba435.jpg)
![15789826298242763094265742193016](https://user-images.githubusercontent.com/59778643/72318917-9e181380-366b-11ea-8e05-b3fc9c3431dd.jpg)

**Comment by shantigilbert** [comment]
un-comment does not mean delete 

just take away the # and just leave use_rgb_to_yuv=0
