### ISSUE TITLE
I can't start a broadcast in the 4.4 trial version

### ISSUE THREAD

**Issue by LeoWalk77** [EmuELEC/EmuELEC#813]
I have a TV Box T95 Max Plus and I'm on the last test version of EmuELEC 4.4 and I noticed that when I try to use the streaming feature to do lives on Twitch, Facebook Gaming or even Youtube, the system cannot transmit. I entered the broadcast keys for these three social networks correctly. In version 4.3 Stable this feature works perfectly. Could you fix this problem? Thanks in advance for the attention of the developers and thank you for creating this great system.

**Comment by shantigilbert** [comment]
Please fill out ALL the information asked when opening an issue and provide logs.

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/604
