### ISSUE TITLE
Retrorun:Flycast does not work on Gameforce

### ISSUE THREAD

**Issue by SamuEDL** [EmuELEC/EmuELEC#815]
**Bug:**
Retrorun: Flycast does not start and returns to Emulationstation. It has been tested both with the Core Flycast and Flycast32b. And in both failure.

**Informations:**
Version: 4.4-TEST-02152022
Hardware Platform: Gameforce Chi

**Log:**
[emuelec.log](https://github.com/EmuELEC/EmuELEC/files/8081802/emuelec.log)

Video: https://youtu.be/wA5pLekzGDs

**Comment by SamuEDL** [comment]
Sorry for the late reply, I've been busy.
In EmuELEC 4.5, it already starts retrorun:flycast. The problem now is that the controls don't work and the screen rotates.

![imagen](https://user-images.githubusercontent.com/59443298/164654688-950f1039-c622-40b6-89e9-c6a2be24cd31.png)

**Comment by Langerz82** [comment]
retroarch has a rotation setting you can add to the emulator Flycast.opt file ( /storage/.config/retroarch/config/Flycast/Flycast.opt ):
```
screen_orientation = “1”
```
also in /storage/.config/retroarch/config/remappings/Flycast/Flycast.rmp add:

```
input_libretro_device_p1 = "1"
input_libretro_device_p2 = "1"
input_player1_analog_dpad_mode = "3"
input_player2_analog_dpad_mode = "3"
input_remap_port_p1 = "0"
input_remap_port_p2 = "1"
```

**Comment by SamuEDL** [comment]
But that's only for retroarch right? Retroarch works fine, what doesn't is retrorun.
P.D: I have also tried what you say and there is no effect on "RetroRun"

**Comment by Langerz82** [comment]
Im not sure that flycast standalone has a screen rotation option.

**Comment by Langerz82** [comment]
can you copy and paste the files in: /storage/.config/flycast , particularly emu.cfg and your remappings files.

**Comment by Langerz82** [comment]
sorry for triple post, but you can also try setting the native video for flycast SA as well to maybe: 640x480 and see if that makes any difference in its orientation.

**Comment by SamuEDL** [comment]
Flycast: SA also works correctly in controls, resolution and rotation. The only one that doesn't is "Retrorun: Flycast" and "Retrorun: Flycast_32B". Also thanks for the help.

**Comment by Langerz82** [comment]
retrorun launches retroarch with the libretro emulators. Something in your settings files is majorly screwing with it's execution.

**Comment by Langerz82** [comment]
Hey, I got a portable so I know a little about this issue more. Retrorun is indeed a seperate process. On my device I have the same issue, not the rotation that the controls arent being recognised. If I find a solution I will let you know. From what I've been reading it seems the controller config is auto-detected and hard-coded so there is no controller config file that I am aware of.

**Comment by Langerz82** [comment]
Hey can you SSH in and run the following command:
```
cat /proc/bus/input/devices 
```
And post the output in http://gist.github.com
The retrorun file needs to be coded, and to support your device and I need to know the event id.

**Comment by SamuEDL** [comment]
Here is the output of the command: https://gist.github.com/SamuEDL/769383b512795d2dc67bcdfa9d47ed51

**Comment by SamuEDL** [comment]
Good afternoon,
Here you have the file (I have compressed it for you, because github does not support .cfg file)
[retrorun.zip](https://github.com/EmuELEC/EmuELEC/files/8709691/retrorun.zip)
:

**Comment by Langerz82** [comment]
@SamuEDL 
Your config looks fine. The rotation is caused most likely because of the over-rotation the code makes. Good news is that I think we can fix the issues, the bad news is you will probably have to wait until the next Emuelec release or if your able to build from this PR see:
https://github.com/EmuELEC/EmuELEC/pull/907

**Comment by Langerz82** [comment]
@SamuEDL 
That's strange on my device thats rockchip based it's the opposite lol. Ok, well I've submitted some fixes for retrorun and hopefully we can commit the changes before next release for you.

**Comment by Langerz82** [comment]
Hey man it's no big deal getting this to run, because flycast standalone runs much better.

**Comment by Langerz82** [comment]
Closing this issue as Gameforce CHI's are archaic now, and the flycast standalone runs better anyway.

If someone needs a fix for this which requires a modified build:
In https://github.com/OtherCrashOverride/retrorun-go2/blob/master/src/video.cpp#L240C31-L240C43:
```
go2_rotation_t rotation = opt_portrait ? GO2_ROTATION_DEGREES_180 : GO2_ROTATION_DEGREES_270;
```
change it to:
```
go2_rotation_t rotation = GO2_ROTATION_DEGREES_180;
```
and it should work. I haven't tested it but im pretty sure thats the line that needs patching.

**Comment by Langerz82** [comment]
See PR:
https://github.com/EmuELEC/EmuELEC/pull/1267

Needs testing. I do not have a Gameforce Chi so I cannot test myself. haha.

**Comment by Langerz82** [comment]
test with the latest build. if it doesnt work please reply here and let me know.

See merged PR:
https://github.com/EmuELEC/EmuELEC/pull/1267
