### ISSUE TITLE
Supertuxkart does not work

### ISSUE THREAD

**Issue by SamuEDL** [EmuELEC/EmuELEC#816]
**Bug:**
SuperTuxKart does not start and returns to Emulationstation. 

**Informations:**
Version: 4.4-TEST-02152022
Hardware Platform: Gameforce Chi

**Logs:**
[es_launch_stderr.log](https://github.com/EmuELEC/EmuELEC/files/8081953/es_launch_stderr.log)
[emuelec(1).log](https://github.com/EmuELEC/EmuELEC/files/8081956/emuelec.1.log)
[es_launch_stdout.log](https://github.com/EmuELEC/EmuELEC/files/8081957/es_launch_stdout.log)

**Comment by shantigilbert** [comment]
Here as well, press the "A" button when it prompts to install. instead of the "START"

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/817#issuecomment-1052681236

**Comment by SamuEDL** [comment]
Already download the game. But do not start the game, keep going back to EmulationStation.
[es_launch_stderr.log](https://github.com/EmuELEC/EmuELEC/files/8148429/es_launch_stderr.log)
[es_launch_stdout.log](https://github.com/EmuELEC/EmuELEC/files/8148430/es_launch_stdout.log)
[emuelec.log](https://github.com/EmuELEC/EmuELEC/files/8148431/emuelec.log)

**Comment by shantigilbert** [comment]
If you had old data you need to delete it first

**Comment by miwasp** [comment]
According to the logs he already has the latest ‚stk-code‘ in the data-folder. Exactly that is the problem, the binary does not match the ‚stk-code‘ repo.
Some configs in the stk-code repo were moved recently. The binary still searches these configs in the old place.

Binary and stk-code have to match. I think this will only work if both are of the same release version and not master.

**Comment by shantigilbert** [comment]
> According to the logs he already has the latest ‚stk-code‘ in the data-folder. Exactly that is the problem, the binary does not match the ‚stk-code‘ repo. Some configs in the stk-code repo were moved recently. The binary still searches these configs in the old place.
> 
> Binary and stk-code have to match. I think this will only work if both are of the same release version and not master.

So maybe we need to change the ASSETS and DATA variables here: 
https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emuelec-ports/supertuxkart/scripts/run_supertuxkart.sh

To match the commit, is that what you mean? right now I am using master, but if they do in fact change then there might be the issue.

**Comment by miwasp** [comment]
I think to be really safe you have to use the same version (1.3 for now) for ASSETS, DATA and BINARY.

**Comment by shantigilbert** [comment]
> I think to be really safe you have to use the same version (1.3 for now) for ASSETS, DATA and BINARY.

I think you are right, we need to move to releases instead of commits for both SuperTux and SuperTuxKart

**Comment by djibux** [comment]
Sorry for digging out an old bug, but my Gameforce Chi, running the latest 4.6 version, still references v1.3 and does not start.

Indeed https://github.com/supertuxkart/stk-code/archive/refs/heads/1.3.zip is broken and so the game does not download.

Shouldn’t I have the new script in version 4.6?

**Comment by shantigilbert** [comment]
> Shouldn’t I have the new script in version 4.6?

the one mentioned here, yes, the new one, no, it came after the 4.6 release. You can download and copy the script

**Comment by djibux** [comment]
Yes, it works.  Thanks.
