### ISSUE TITLE
[v4.4-TEST-02152022] OGS unable to play drastic nor install drastic

### ISSUE THREAD

**Issue by PikachuEXE** [EmuELEC/EmuELEC#819]
### Env
EMUELEC version: `v4.4-TEST-02152022`
Update method: From `4.4-TEST-12242021`, put `tar` file into SD card `.update` folder, `RESET EMUELEC SCRIPTS AND BINARIES TO DEFAULT`

#### 1. Unable to install drastic via `Install Drastic` (in setup category)
It would only display a few lines and exit

Lines:
- `Rga build version: xxxxxx`
- `Game controller mappings loaded`
- `Only .sh scripts are supported`

#### 2. Unable to view last emuelec.log
`Show last emuelec.log`, same output as `Install Drastic`

#### 3. Unable to start drastic, even with previously backed up binaries
Using FTP I backup the binaries from previous working version `4.4-TEST-12242021`
Then restore them after (1) and (2)
However I am still unable to start any NDS game

**Comment by shantigilbert** [comment]
#817
