### ISSUE TITLE
Screenscraper http status 401

### ISSUE THREAD

**Issue by Carlosaleqwe** [EmuELEC/EmuELEC#84]
![15793811458883547605904959704903](https://user-images.githubusercontent.com/59778643/72670456-7deda900-3a0b-11ea-8d6d-8b608d43bea4.jpg)

**Comment by taso-tac** [comment]
Hi! i've the same problem. I can dowload themes but not scrap images.

**Comment by shantigilbert** [comment]
The scraper site was down for maintenance and as of right now it seems the website now requires a username and login to use, nothing I can do for the moment.
