### ISSUE TITLE
Wifi driver QCA6174 (S905L) 

### ISSUE THREAD

**Issue by 331105363** [EmuELEC/EmuELEC#841]
Please add wifi driver QCA6174 for S905L

I have the same problem as #611  

https://github.com/EmuELEC/EmuELEC/issues/611

Please add wifi driver QCA6174 for Amlogic, thank you very much!

**Comment by SamuEDL** [comment]
What version of Emuelec is using?

**Comment by 331105363** [comment]
> What version of Emuelec is using?

4.4

**Comment by 331105363** [comment]
> What version of Emuelec is using?

EmuELEC-Amlogic.aarch64-4.3

**Comment by 331105363** [comment]
> What version of Emuelec is using?

The driver of this chip is added in Amlogic-ng, can it be added in Amlogic

**Comment by SamuEDL** [comment]
> > What version of Emuelec is using?
> 
> The driver of this chip is added in Amlogic-ng, can it be added in Amlogic

If it's as you're commented, in the next version it will be solved since you will only have "amlogic-ng". If you can try Emuelec 4.4-test, to check that it works: https://github.com/EmuELEC/EmuELEC-tests/releases/tag/v4.4-TEST-02152022

**Comment by 331105363** [comment]
> > > What version of Emuelec is using?
> > 
> > 
> > The driver of this chip is added in Amlogic-ng, can it be added in Amlogic
> 
> If it's as you're commented, in the next version it will be solved since you will only have "amlogic-ng". If you can try Emuelec 4.4-test, to check that it works: https://github.com/EmuELEC/EmuELEC-tests/releases/tag/v4.4-TEST-02152022

Emuelec 4.4-test can not be used for s905L, I update Emuelec 4.4-test based on Emuelec 4.3, indicating file damage or insufficient space, 64GB USB flash drive

> > > What version of Emuelec is using?
> > 
> > 
> > The driver of this chip is added in Amlogic-ng, can it be added in Amlogic
> 
> If it's as you're commented, in the next version it will be solved since you will only have "amlogic-ng". If you can try Emuelec 4.4-test, to check that it works: https://github.com/EmuELEC/EmuELEC-tests/releases/tag/v4.4-TEST-02152022

Emuelec 4.4-test can not be used for s905L, I update Emuelec 4.4-test based on Emuelec 4.3, indicating file damage or insufficient space, 64GB USB flash drive

**Comment by shantigilbert** [comment]
You can wait for 4.4 next test or final to see if it's fixed, otherwise, there will not be a fix for this.

**Comment by zeus0368** [comment]
Please resolv... Thank you.
