### ISSUE TITLE
PPSSPP-SDL cheat code not detect

### ISSUE THREAD

**Issue by dewenhsu** [EmuELEC/EmuELEC#846]
Odroid N2+, EmuELEC TEST 0215
I put chest file *.ini and cheat.db in /storage/.config/ppsspp/PSP/Cheats
but PPSSPPSDL seems can not detece these cheat codes, in the cheat code menu,
it will not show the cheat list.
thank you.

**Comment by shantigilbert** [comment]
cheats go in `/storage/roms/savestates/PPSSPPSDL/PSP/Cheats/`
