### ISSUE TITLE
Delay in the controller during play games.

### ISSUE THREAD

**Issue by taso-tac** [EmuELEC/EmuELEC#85]
Hi friends! I see a delay in the controller during play games. All platforms have the same delay, only can reduce this if do not select any shader filter. I test with ps2 controller with usb adapter and with a xbox 360 controller with wireless usb adapter,  Tested in two Android Tv: s905s (2+16gb) and s905w (1+8gb). Both with same dealys, the emulation magic dissapear with this problem.

**Comment by shantigilbert** [comment]
This is normal, not all shaders work on old hardware, either find other shaders that do work or don't use shaders. It also depends on the emulator and game you are using.
