### ISSUE TITLE
Request separate build command

### ISSUE THREAD

**Issue by clondy999** [EmuELEC/EmuELEC#864]
If I want to build a module separately, for example, I just want to build the retroarch project, what is the correct build command

**Comment by miwasp** [comment]
This is not really an issue, so this kind of questions should be placed in the forum or on discord.

There is an entry in the wiki which describes exactly what you are looking for:
https://github.com/EmuELEC/EmuELEC/wiki/DEV:-How-to-compile-toolchain-only
