### ISSUE TITLE
32x Cosmic Carnage crashing before ending a fight since 3.x and still in 4.4

### ISSUE THREAD

**Issue by psaezdev** [EmuELEC/EmuELEC#871]
In amlogic x905x3 (as far I can remember in x905 too), the 32x emulator crashes with Cosmic Carnage if you try a fight. Before ending the fight, it exits with a crash.

Emuelec doesn't include more 32x emulators, so is not possible to try with other cores.

It crashed since EmuELEC 3.X, but I waited and now, in 4.4 is still crashing.

**Comment by miwasp** [comment]
Try disabling "Dynamic Recompilers" in the performance options of the core.

**Comment by qbertaddict** [comment]
Turning off dynamic recompilers and setting the system to pal fixed it for me

**Comment by shantigilbert** [comment]
This is not an EmuELEC issue
