### ISSUE TITLE
Experience the latest v4.4 issues

### ISSUE THREAD

**Issue by kukufeng** [EmuELEC/EmuELEC#890]
Experience the latest v4.4 version issues

The video player does not play 2k video smoothly, 1080p is smooth.

  If there are 1080p or above videos in the theme, it will also freeze, if it is below 720p, it will not. I hope the developers will see my report and continue to optimize

My box: MEKOO km9

**Comment by shantigilbert** [comment]
This is not a bug, there is no HW decoder for video enabled on Emuelec.
