### ISSUE TITLE
Just trying to compile EmuELEC 4.5 and got an error with Crystal:target

### ISSUE THREAD

**Issue by earth2004** [EmuELEC/EmuELEC#898]
**Hi there,

I got an update notice today and wanted to compile EmuELEC 4.5 since I am still on 4.3.
Got this error can anyone help?**

<<< Crystal:target seq 253 <<<
ERROR: /home/louis/EmuELEC/sources/Crystal/Crystal-81a33b8722bd7e4c990cbf59d1e0bfc0453af59d: failed to determine git HEAD
ERROR: /home/louis/EmuELEC/sources/Crystal/Crystal-81a33b8722bd7e4c990cbf59d1e0bfc0453af59d: failed to determine git HEAD
GET      Crystal (git)
    GIT PULL      Crystal
Already up to date.
There is no commit '81a33b8722bd7e4c990cbf59d1e0bfc0453af59d' on branch 'master' of package 'Crystal'! Aborting!
*********** FAILED COMMAND ***********
. "${get_handler}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/get "${PKG_NAME}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install Crystal:target has failed!

**Thanks
Louis**

**Comment by shantigilbert** [comment]
Please github is only for BUGS not general questions, use the forum or discord.
