### ISSUE TITLE
4.5 reicast

### ISSUE THREAD

**Issue by MrFrank365** [EmuELEC/EmuELEC#899]
On Emuelec 4.5 Dreamcast and Naomi reicast emulator it lags on intro loading screen, gameplay is fine, RetroArch reicast try Marvel vs Capcom 2.

i use flycast and it works fine, but regular reicast with RetroArch no good.
GT King.

**Comment by shantigilbert** [comment]
Reicast is not included in EmuELEC

**Comment by MrFrank365** [comment]
My bad the "Libretro: Flycast" is having some slow downs on games such as Marvel vs Capcom 2.

"FlycastSA" is working well.
