### ISSUE TITLE
WIFI issue in Mecool M8S Pro + (9082xs chip)

### ISSUE THREAD

**Issue by minimalnetwork** [EmuELEC/EmuELEC#90]
Hello! Congrats for your work! I have installed EmuELEC in my Mecool M8S Pro + and works great! I have tested this distro and I found that WIFI doesn't work. Doing a 'ifconfig' wlan0 or similar doesn't appear. Doing a `udevadm info /sys/bus/sdio/devices/sdio*`, I obtain this result:
`P: /devices/d0070000.sdio/mmc_host/sdio/sdio:0001/sdio:0001:1`
`L: 0`
`E: DEVPATH=/devices/d0070000.sdio/mmc_host/sdio/sdio:0001/sdio:0001:1`
`E: SDIO_CLASS=07`
`E: SDIO_ID=02E7:9082`
`E: MODALIAS=sdio:c07v02E7d9082`
`E: SUBSYSTEM=sdio`
I think that my hardware have a 9082xs chip. There is not source code available for this chip, but in Libreelec forum, there is a build that includes 9082xs's pre compiled module and it works (https://forum.libreelec.tv/thread/5457-s905x-unknown-wlan-chip/?postID=73122#post73122). Do you know if in a future it will be supported?
Thank you!

**Comment by shantigilbert** [comment]
Not likely, from that post : 

"when kernel is updated, support will probably be dropped"
without the source/drivers its going to be hard to implement.
