### ISSUE TITLE
[4.5] Frontend music does not work on S905W

### ISSUE THREAD

**Issue by d-apps** [EmuELEC/EmuELEC#910]
I have a folder called BGM inside roms folder with a lots of .ogg files and I can play them on pc.

I turned on the Frontend music option on menu, when I press select, the label "**Skip to next song**" is showed and "**Now playing**" says the current song that should be playing but there is no sound.

![WhatsApp Image 2022-04-30 at 03 25 45](https://user-images.githubusercontent.com/20110433/166094512-1f99918e-3ea2-4bcc-ab25-eaaa5bccb3a6.jpeg)

Sound in games is working.

Logs:
http://ix.io/3WCU
or
[logs.txt](https://github.com/EmuELEC/EmuELEC/files/8596260/logs.txt)

**Comment by shantigilbert** [comment]
Duplicate: #868
