### ISSUE TITLE
[4.5][S905M2 rev d][saturn] Sega Saturn is not working: emuelecRunEmu.sh: line 441: 10707 Aborted 

### ISSUE THREAD

**Issue by d-apps** [EmuELEC/EmuELEC#913]
/usr/bin/emuelecRunEmu.sh: line 441: 10707 Aborted                 ${RABIN} $VERBOSE -L /tmp/cores/${EMU}.so --config ${RACONF} "${ROMNAME}"
exit 134
exit bios 0

[sega saturn emuelec.log](https://github.com/EmuELEC/EmuELEC/files/8628150/sega.saturn.emuelec.log)

**Comment by Langerz82** [comment]
I'm not so sure s905m chipsets are supported on 4.5. What dtb file are you using?

**Comment by d-apps** [comment]
> I'm not so sure s905m chipsets are supported on 4.5. What dtb file are you using?

But the message about 4.4/4.5 is:

"IMPORTANT: S905 (GXBB, p201) for the moment is no longer supported. If you have one of those devices **(s905 no letter after the 5)** DO NOT UPDATE, stay in 4.3."

Mine there is a letter "**M**" after "**5**" so I assume that it should work.

I used **gxl_p281_1g** dtb.

Most of other cores are working.

**Comment by shantigilbert** [comment]
> Most of other cores are working.

But Yabasanshiro is not one of them.

**Comment by d-apps** [comment]
> > Most of other cores are working.
> 
> But Yabasanshiro is not one of them.

Sorry but I didn't understand why you closed this.

It won't be fixed in future updates?

**Comment by shantigilbert** [comment]
No, Yabasanshiro does not work on older devices, there is nothing for me to fix
