### ISSUE TITLE
[4.5][OGA/OGS] Launch Terminal is not working

### ISSUE THREAD

**Issue by british-choi** [EmuELEC/EmuELEC#915]
Device : OGA / OGS
Version : 4.5

Precondition : none
Test step : Run "Launch Terminal" menu in Setup scripts

Terminal window is not shown.

**Comment by shantigilbert** [comment]
logs?

**Comment by british-choi** [comment]
Unfortunately, no log occurred.
But, it happens every time.

**Comment by british-choi** [comment]
I found error message while executing "kmscon"

xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb

**Comment by shantigilbert** [comment]
> kmscon

figures :/

**Comment by Langerz82** [comment]
Tested on a 4.6 with an OGA build on a different device, same build and terminal opens up ok.

Closing Issue, if need re-open let me know.
