### ISSUE TITLE
ps3 controller ppsspp 、drastic work not fine

### ISSUE THREAD

**Issue by zouplus** [EmuELEC/EmuELEC#916]
1.emuelec controller setting ,all button can work(I try 3.9 & 4.5)
2.ppsspp the center menu button (whitch mapping hotkey button) at 3.9 work fine,but 4.5 cannot be recognized
3.drastic cannot controll menu : up / down / left / right ；I had config the extern setting in drastic menu up / down / left / down,I am sure the setting is work,because the left ,right ,...A B... can controlle the games

**Comment by Langerz82** [comment]
Did you do a clean install of 4.5 or upgrade?
Also try in EmulationStation re-mapping your game controller again. From what I understand PPSSPP uses the config from gamecontrollerdb.txt.
Also please provide more info such as your device, and the name of the game controller.

**Comment by zouplus** [comment]
> Did you do a clean install of 4.5 or upgrade?
> Also try in EmulationStation re-mapping your game controller again. From what I understand PPSSPP uses the config from gamecontrollerdb.txt.
> Also please provide more info such as your device, and the name of the game controller.

my controller is ps3 controller and I do clean install of 4.5，I fomate usb flash；I try many times to mapping controller the menu button
 still not work at ppsspp but ee work okey；my box is 900v22d，controller is ps3 controller

**Comment by zouplus** [comment]
and the box get error when boot！
；It hanppend boot with usb ，but tf card is okey！the box is 900v 22d ，s905l3a （905x2）

**Comment by zouplus** [comment]
![WechatIMG39](https://user-images.githubusercontent.com/100817707/167679647-6428b736-054d-4261-b994-3407ddaa988b.jpeg)
![WechatIMG40](https://user-images.githubusercontent.com/100817707/167679669-866e6f47-59cc-4c09-a9ec-2cedf928990d.jpeg)
![WechatIMG41](https://user-images.githubusercontent.com/100817707/167679694-5b14eda9-2a1c-4611-8a5b-f760cd3eb891.jpeg)

--------------
the ps button not work at ppsspp at 4.5 but 3.9 work fine（only that button），and the ps3 controller at 3.9 default mapping  
is right，but 4.5 should remapping the controller。

**Comment by Langerz82** [comment]
I cant even get the dpad working in drastic, not for the menu screen below or for the actual game.
What controller do you use that works? can you provide the files in /storage/.config/emulationstation/scripts/drastic/config ?

**Comment by zouplus** [comment]
sorry i am so late to reply, you can use keyboard to set drastic，the different controller may not work，you can press “M” key to set.

**Comment by 7Ji** [comment]
S905L3A/L3B (S905L, version 3, step A/B) is not supported and none of our existing DTBs are for these SoCs. You can boot them with dtbs of S905X2, but many components on the SoC do not work as intended --- they are NOT some simple reskined S905X2 or either S905X3 (they're more like downgraded X3, not X2), not as simple as S905L downgraded from S905X, and do expect major breaks when you force an incompatible dtb onto a different SoC.

As long as we are still using the 4.9 kernel, devices equiped with these SoCs (E900V3c, CM118, etc) can never be supported and don't expect any support as no one of the team has such hardware

**Comment by Langerz82** [comment]
What version had drastic? It seems we dont have it included anymore.

**Comment by Langerz82** [comment]
I forgot you had to install drastic from the settings menu.

Jus a note on these issues:
1. PPSSPP the control.ini did not change, therefore it is most likely a source bug and should be raised in there github.
2. Drastic is closed source so you would have to raise the issue with them.
