### ISSUE TITLE
Unable to boot EmuELEC 4.5 on Phicomm N1(S905D) box

### ISSUE THREAD

**Issue by alifare** [EmuELEC/EmuELEC#918]
From the official NOTE, S905D is supported by EmuELEC 4.5, even if S905 is not.

> IMPORTANT: S905 (GXBB, p201) for the moment is no longer supported. If you have one of those devices (s905 no letter after the 5) DO NOT UPDATE, stay in 4.3.

I downloaded `EmuELEC-Amlogic-ng.aarch64-4.5-Generic.img.gz` and flashed it into a USB disk. Unfortunately, however, I failed to boot EmuELEC 4.5 from USB on my Phicomm N1(S905D) box, even if I replaced the files(dtb.img, aml_autoscript and others) with some patch packages downloaded from Internet, which is said to work well on older EmuELEC versions like 4.3.

So I am asking is there any way to boot EmuELEC 4.5 on Phicomm N1(S905D), or can any one give me any working directions to fix this problem?

I am willing to do it myself, and I have rich experience in Linux and programming skills. But I know nothing about S905D and EmuELEC.

**Comment by AlienatedDiego** [comment]
Duplicate/same issue https://emuelec.discourse.group/t/unable-to-boot-emuelec-4-5-on-phicomm-n1-s905d/1137

**Comment by maskedeken** [comment]
> From the official NOTE, S905D is supported by EmuELEC 4.5, even if S905 is not.
> 
> > IMPORTANT: S905 (GXBB, p201) for the moment is no longer supported. If you have one of those devices (s905 no letter after the 5) DO NOT UPDATE, stay in 4.3.
> 
> I downloaded `EmuELEC-Amlogic-ng.aarch64-4.5-Generic.img.gz` and flashed it into a USB disk. Unfortunately, however, I failed to boot EmuELEC 4.5 from USB on my Phicomm N1(S905D) box, even if I replaced the files(dtb.img, aml_autoscript and others) with some patch packages downloaded from Internet, which is said to work well on older EmuELEC versions like 4.3.
> 
> So I am asking is there any way to boot EmuELEC 4.5 on Phicomm N1(S905D), or can any one give me any working directions to fix this problem?
> 
> I am willing to do it myself, and I have rich experience in Linux and programming skills. But I know nothing about S905D and EmuELEC.

@alifare you can fix this with my patches. Please refer to [https://www.right.com.cn/forum/thread-8226482-1-1.html](https://www.right.com.cn/forum/thread-8226482-1-1.html)

**Comment by alifare** [comment]
> 

Thanks for your help. I will give it a try

**Comment by shantigilbert** [comment]
> @alifare you can fix this with my patches. Please refer to https://www.right.com.cn/forum/thread-8226482-1-1.html

Since those are binaries, What did you change on the source code to make it work?

**Comment by alifare** [comment]
> > From the official NOTE, S905D is supported by EmuELEC 4.5, even if S905 is not.
> > > IMPORTANT: S905 (GXBB, p201) for the moment is no longer supported. If you have one of those devices (s905 no letter after the 5) DO NOT UPDATE, stay in 4.3.
> > 
> > 
> > I downloaded `EmuELEC-Amlogic-ng.aarch64-4.5-Generic.img.gz` and flashed it into a USB disk. Unfortunately, however, I failed to boot EmuELEC 4.5 from USB on my Phicomm N1(S905D) box, even if I replaced the files(dtb.img, aml_autoscript and others) with some patch packages downloaded from Internet, which is said to work well on older EmuELEC versions like 4.3.
> > So I am asking is there any way to boot EmuELEC 4.5 on Phicomm N1(S905D), or can any one give me any working directions to fix this problem?
> > I am willing to do it myself, and I have rich experience in Linux and programming skills. But I know nothing about S905D and EmuELEC.
> 
> @alifare you can fix this with my patches. Please refer to https://www.right.com.cn/forum/thread-8226482-1-1.html

I tried to switch from Android TV to EmuELEC, but failed. My television looks like this:
![LibreELEC](https://user-images.githubusercontent.com/8717131/168854300-04487556-3d9b-4544-ac70-9fb1f79194b9.jpg)
![boot](https://user-images.githubusercontent.com/8717131/168854331-adb0fb6b-4e3b-4ca9-86e1-228ac19acad8.jpg)

**Comment by maskedeken** [comment]
> 

check if aml_autoscript.zip exists on boot parition of your usb disk, if not, just create an empty file named 'aml_autoscript.zip', and try again

**Comment by maskedeken** [comment]
> > @alifare you can fix this with my patches. Please refer to https://www.right.com.cn/forum/thread-8226482-1-1.html
> 
> Since those are binaries, What did you change on the source code to make it work?

I just extracted the uncompressed kernel and ramdisk from the original KERNEL, since Phicomm N1 can only boot an uncompressed kernel

**Comment by alifare** [comment]
> 

Yes, aml_autoscript.zip exists on boot partition because I copied ALL files from your patches. Actually, I was confused why there is an empty file like that, but I still copied it to the boot partition.

Maybe something happened after running Android TV and files or partitions in USB were changed?

**Comment by maskedeken** [comment]
> > 
> 
> Yes, aml_autoscript.zip exists on boot partition because I copied ALL files from your patches. Actually, I was confused why there is an empty file like that, but I still copied it to the boot partition.
> 
> Maybe something happened after running Android TV and files or partitions in USB were changed?

try to run 'adb reboot update' ?

**Comment by alifare** [comment]
> 

From where ?

**Comment by maskedeken** [comment]
adb connect <your tv box ip>

then 

adb reboot update

**Comment by alifare** [comment]
> adb connect xx.xx.xx.xx (your tv box ip)
> 
> then
> 
> adb reboot update

I understant the command `adb reboot update` is to update reboot command in my android TV box. 

Will the update affect my TV box? Can I still use my box to watch TV?

**Comment by maskedeken** [comment]
'adb reboot update' just forces your box to boot from usb, it won't affect your tv box

**Comment by alifare** [comment]
> 
If that is the case, I have to run `adb reboot update` each time when I switch from TV box to EmuELEC ?

**Comment by maskedeken** [comment]
> > 
> 
> If that is the case, do I have to run `adb reboot update` each time when switching from TV box to EmuELEC ?

just give it a try

**Comment by alifare** [comment]
> > > 
> > 
> > 
> > If that is the case, do I have to run `adb reboot update` each time when switching from TV box to EmuELEC ?
> 
> just give it a try

It still doesn't work, so sad

**Comment by alifare** [comment]
> > > > > 
> > > > 
> > > > 
> > > > If that is the case, do I have to run `adb reboot update` each time when switching from TV box to EmuELEC ?
> > > 
> > > 
> > > just give it a try
> > 
> > 
> > It still doesn't work after running command `adb reboot update`, so sad ![boot2](https://user-images.githubusercontent.com/8717131/169187180-96fc4c66-3d41-4ac3-9de4-9843a81aec75.jpg)
> 
> how did you run it successfully for the first time?

The fresh burnt EmuELEC 4.5 (in USB disk) works, and I even played some games in it.

But after I switched from EmuELEC to Android TV by running `REBOOT FROM NAND`, and switched back from Android TV to EmuELEC by running `LibreELEC`, it faild to boot and my television showde this :
![boot2](https://user-images.githubusercontent.com/8717131/169192535-cdb082a7-f7aa-4f93-a393-79f3bc9192be.jpg)

**Comment by shantigilbert** [comment]
This is clearly not a bug on EmuELEC so please continue this on the forum there is already a discussion opened there : 
https://emuelec.discourse.group/t/unable-to-boot-emuelec-4-5-on-phicomm-n1-s905d/1137
