### ISSUE TITLE
Request: RK322X Support.

### ISSUE THREAD

**Issue by AstaFatherSatan** [EmuELEC/EmuELEC#929]
Please add RK322X Support. I linked images below as a reference to it can be done easily.

**Comment by AstaFatherSatan** [comment]
https://github.com/EmuELEC/EmuELEC/commit/0e939189579e2700e970e2eaaa89630cad2dd173
https://github.com/knaerzche/LibreELEC.tv/releases/tag/RK322x-le92-0bca75f
https://forum.armbian.com/topic/12656-csc-armbian-for-rk322x-tv-boxes/
https://drive.google.com/file/d/1oRv1aglURg_EYcHsUAjOamfxomz27ZJU/view
https://bit.ly/3qVLkFt

**Comment by shantigilbert** [comment]
No, sorry.
