### ISSUE TITLE
Wiimote

### ISSUE THREAD

**Issue by b0b33140** [EmuELEC/EmuELEC#93]
Wiimotes do not want to associate in the ES menu. The connection works in SSH but the handling is to be redone each time the controller is connected.

**Comment by shantigilbert** [comment]
I have no Wiimotes so I cannot test this, sorry

**Comment by durstboiler** [comment]
Hello, I can connect the wiimote from emulationstation on emuelec 3.9, but the motion capture does not work. Apparently now there are a lot of emulators that support the Wiimote in light gun by simulating a mouse, on PSX-rearmed, snes, mame2003, advenceMAME, flycast ... but no way to get there on emuelec.
