### ISSUE TITLE
S905w dtb that works?

### ISSUE THREAD

**Issue by nickvasallo** [EmuELEC/EmuELEC#94]
Hello, I tried the s902x2_2g, s905x3_2g, and p281_2g DTB's (the p281 I found on Google). Nothing worked. Is there a DTB for the s905w chipset that will work with EmuELEC? thanks

**Comment by shantigilbert** [comment]
Why were you trying DTBs for s905x2 on S905w??? you need to read the Wiki, and please do not use random DTBs. 

most likely you are burning the Amlogic-ng image which will NOT work on S905w

**Comment by nickvasallo** [comment]
You're right, thanks. I tried the non -ng version. works

**Comment by shantigilbert** [comment]
:) closing this issue now
