### ISSUE TITLE
Pressing reset button in Odroid Go Super does not work. May be no event listener in Emuelec

### ISSUE THREAD

**Issue by stuart1975** [EmuELEC/EmuELEC#965]
When I click on the reset button with a pencil on the backside of the handheld Odroid Go Super no reset happens. Maybe there is no event listener programed in Emuelec.
Please can you add a reaction of this click making a memory reset. Sometimes Emulec became unresponsive and no button press makes a reaction on the screen. It is not easy to remove the battery in a Odroid Go Super to make a hard reset so I have to wait the battery becames empty to have a reset. 

Thank you
Used Emuelec version 4.5.

**Comment by miwasp** [comment]
What makes you think this is a reset button? The purpose of this button is described here: https://wiki.odroid.com/odroid_go_advance/application_note/forced_sd_boot

If you want to force a power off, the wiki says:
```
If you have any problem with your ODROID-GO-Super, you will try to switch off.
You can switch off ODROID-GO-Super by pushing the on/off buttons for about 6 seconds.
```
(source: https://wiki.odroid.com/odroid_go_super/start)
