### ISSUE TITLE
4.5 Multiple handles cannot switch the order on ES

### ISSUE THREAD

**Issue by zouplus** [EmuELEC/EmuELEC#968]
EE4.5 ，I use multiple controllers to switch the handle order in Es, but no matter how I adjust the order, it is not correct. The same method is normal to switch to the lower version (4.3, 3.9). If this problem has been fixed, can you tell 4.5 how to solve it by modifying certain configurations or recompiling some dependencies!

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/EmuELEC/issues/604

**Comment by zouplus** [comment]
I seem to have found the same public problem as the wiki. Do I need to provide logs?
