### ISSUE TITLE
Emuelec 4.6-TEST-07082022  Bluetooth game controller

### ISSUE THREAD

**Issue by haha496744** [EmuELEC/EmuELEC#986]
EmuELEC version:

Version [e.g. 4.6-TEST]

SOC: [e.g. S905x3]
Brand: [e.g. x96max+]
Model [e.g. x96max+]
Version [e.g. 4.6-TEST]
Bluetooth game controller（gamepadplus）e can work normally only when it is connected at power on
When the Bluetooth game controller is connected again, it will not work, and the key will not work
It can be recognized as a game controller in the emulec interface, but it cannot be recognized in the key mapping in retroarch
It can work normally on emulec 4.5.

**Comment by 7Ji** [comment]
> # DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!
And you surely didn't read that at all, you need to delete things **ABOVE** that line and fill in the remaining infos:

>**Describe the bug**
>A clear and concise description of what the bug is.
>
>**To Reproduce**
>Steps to reproduce the behavior:
>1. Go to '...'
>2. Click on '....'
>3. Scroll down to '....'
>4. See error
>
>**Expected behavior**
>A clear and concise description of what you expected to happen.
>
>**Screenshots**
>If applicable, add screenshots to help explain your problem.
>
>**EmuELEC version:**
> - Version [e.g. 22]
>
>**Device (please complete the following information):**
> - SOC: [e.g. S095x3]
> - Brand: [e.g. Beelink]
> - Model [e.g. mini g1]
> - Version [e.g. 22]
>
>**Additional context**
>Add any other context about the problem here.

And please, even you can't follow the template, at least describe your issues clearly
> Bluetooth handle

What do you even mean by that? Bluetooth game controller? 

What device you're using? Don't tell me you are using S905L3A/B boxes (E900V3C/D, CM131), they are **not** supported at all and the bluetooth not functioning properly is expected since we don't even have a dtb for it.

**Comment by haha496744** [comment]
> > # DELETE EVERYTHING ABOVE THIS LINE (INCLUDING THIS LINE) BEFORE SUBMITTING TO MAKE SURE YOU'VE READ THIS!
> 
> And you surely didn't read that at all, you need to delete things **ABOVE** that line and fill in the remaining infos:
> 
> > **Describe the bug**
> > A clear and concise description of what the bug is.
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Expected behavior**
> > A clear and concise description of what you expected to happen.
> > **Screenshots**
> > If applicable, add screenshots to help explain your problem.
> > **EmuELEC version:**
> > 
> > * Version [e.g. 22]
> > 
> > **Device (please complete the following information):**
> > 
> > * SOC: [e.g. S095x3]
> > * Brand: [e.g. Beelink]
> > * Model [e.g. mini g1]
> > * Version [e.g. 22]
> > 
> > **Additional context**
> > Add any other context about the problem here.
> 
> And please, even you can't follow the template, at least describe your issues clearly
> 
> > Bluetooth handle
> 
> What do you even mean by that? Bluetooth game controller?
> 
> What device you're using? Don't tell me you are using S905L3A/B boxes (E900V3C/D, CM131), they are **not** supported at all and the bluetooth not functioning properly is expected since we don't even have a dtb for it.


Sorry for that, I've reverted to version 4.5    。 big brother ， are  you  chinese？
